const phpLessons = [
  {
    slug: "php-introducere-echo",
    title: "1. Introducere PHP + echo",
    order: 1,
    theory: [
      {
        order: 1,
        title: "Ce este PHP și de ce îl mai folosim în 2024?",
        content: "Imaginează-ți că ai un restaurant. Clientul (browserul) vede sala și meniul — asta e HTML și CSS. Dar în bucătărie (server) cineva gătește mâncarea, verifică stocul, calculează prețurile. Acea persoană din bucătărie este **PHP**.\n\nPHP rulează pe server, prepară datele, și trimite **HTML gata făcut** clientului. Browserul nu vede niciun cod PHP — vede doar rezultatul.\n\n```\nClient (Browser)          Server\n     |                       |\n     |--- Request GET / ---->|\n     |                       | ← PHP rulează aici\n     |                       |   consultă baza de date\n     |                       |   generează HTML\n     |<-- Response HTML -----|  \n     |                       |\n```\n\n**De ce PHP?** Lumea web rulează în mare parte pe PHP:\n• **WordPress** — 43% din toate site-urile de pe internet\n• **Facebook** — a pornit 100% PHP (acum au limbajul propriu Hack)\n• **Wikipedia** — MediaWiki e PHP\n• **Laravel, Symfony, CodeIgniter** — framework-uri PHP în top 10 mondial\n\n**PHP vs. JavaScript:** JavaScript rulează în browser (front-end). Node.js rulează în server dar e tot JS. PHP a fost creat special pentru server de la început, în 1994 de Rasmus Lerdorf.\n\n**La interviu** te pot întreba: *\"Care e diferența dintre client-side și server-side scripting?\"* — Răspuns: PHP procesează pe server, rezultatul HTML ajunge la browser. JavaScript procesează în browser, fără un round-trip la server.",
      },
      {
        order: 2,
        title: "Prima pagină PHP — echo și structura fișierului",
        content: "Fiecare fișier PHP are extensia `.php` și codul stă **între taguri speciale** — PHP și HTML pot fi intercalate liber:\n\n```php\n<?php\necho \"Bună ziua!\";\n?>\n```\n\nTagul `?>` de închidere este **opțional** în fișierele PHP pure. De fapt, standardul PSR (PHP Standard Recommendations) recomandă să nu îl pui, ca să eviți whitespace accidental.\n\n**echo** este comanda de bază pentru a afișa ceva:\n```php\n<?php\necho \"Salut, lume!\";             // text\necho 42;                          // număr\necho 3.14;                        // float\necho \"<h1>Titlu HTML</h1>\";       // HTML valid!\necho \"Prima\", \" \", \"pagina\";     // mai multe argumente\necho \"Suma: \" . (5 + 3);          // concatenare cu punct → Suma: 8\n```\n\n**print** e similar dar returnează 1 (poate fi folosit în expresii):\n```php\n<?php\n$ok = print \"Salut\";  // afișează Salut, $ok = 1\n```\n\n**Short echo tag** — shorthand pentru template-uri:\n```php\n<!DOCTYPE html>\n<html>\n<body>\n  <h1><?= \"Titlul paginii\" ?></h1>\n  <p>Data: <?= date(\"d.m.Y\") ?></p>\n</body>\n</html>\n```\n\n**Regula de aur:** Fiecare instrucțiune PHP se termină cu **;** (punct și virgulă). Dacă lipsește → fatal error.\n\n**Ce se întâmplă la execuție?** PHP parsează fișierul de sus în jos, execută codul, și tot ce iese din echo/print merge direct în răspunsul HTTP. HTML din afara `<?php ?>` e trimis ca atare.",
      },
      {
        order: 3,
        title: "Tipuri de date și var_dump — ce ține PHP în memorie",
        content: "PHP e un limbaj **dinamic** — nu declari tipul variabilei, PHP îl deduce singur din valoarea asignată. E ca și cum ai lăsa pe cineva să ghicească ce conține cutia în loc să scrii pe etichetă.\n\n**Cele 8 tipuri de date PHP:**\n\n```php\n<?php\n// Scalare:\n$intreg    = 42;           // integer — numere întregi\n$negativ   = -100;         // integer negativ\n$real      = 3.14;         // float / double\n$text      = \"Salut\";      // string\n$boolean   = true;         // boolean: true sau false\n$nimic     = null;         // null — absența valorii\n\n// Compuse:\n$lista     = [1, 2, 3];    // array\n$obiect    = new stdClass();// object\n```\n\n**var_dump()** — cel mai bun prieten la debugging:\n```php\n<?php\nvar_dump(42);           // int(42)\nvar_dump(3.14);         // float(3.14)\nvar_dump(\"PHP\");        // string(3) \"PHP\"\nvar_dump(true);         // bool(true)\nvar_dump(false);        // bool(false)\nvar_dump(null);         // NULL\nvar_dump([1, \"doi\"]);   // array(2) { [0]=> int(1) [1]=> string(3) \"doi\" }\n```\n\n**gettype()** vs **is_*()** — pentru verificare în cod real:\n```php\n<?php\n$x = 42;\necho gettype($x);        // \"integer\"\nvar_dump(is_int($x));    // bool(true)\nvar_dump(is_string($x)); // bool(false)\nvar_dump(is_null(null)); // bool(true)\nvar_dump(isset($y));     // bool(false) — $y nu există\n```\n\n**Constante** — valori fixe fără `$`, nu pot fi schimbate:\n```php\n<?php\ndefine(\"DB_HOST\", \"localhost\");  // runtime\nconst DB_PORT = 3306;            // compile time (în clase e obligatoriu)\n\necho DB_HOST;  // localhost — fără $!\necho DB_PORT;  // 3306\n\n// PHP are și constante predefinite:\necho PHP_VERSION;    // ex: 8.2.10\necho PHP_EOL;        // newline cross-platform\necho PHP_INT_MAX;    // 9223372036854775807\n```",
      },
      {
        order: 4,
        title: "Comentarii, PHP mixt cu HTML și debugging de bază",
        content: "**Tipuri de comentarii în PHP:**\n```php\n<?php\n// Comentariu pe o linie (recomandat)\n\n# Și acesta e valid (stil bash — mai rar folosit)\n\n/*\n * Comentariu pe mai multe linii\n * Ideal pentru documentarea funcțiilor\n */\n\n/** \n * PHPDoc — standard pentru documentare profesională:\n * @param string $nume Numele utilizatorului\n * @return string Mesajul de salut\n */\nfunction saluta(string $nume): string {\n    return \"Bună, $nume!\";\n}\n```\n\n**PHP intercalat cu HTML** — puterea PHP în template-uri:\n```php\n<!DOCTYPE html>\n<html lang=\"ro\">\n<head>\n    <title><?= \"TaskForge\" ?></title>\n</head>\n<body>\n    <?php\n    $utilizatori = [\"Ana\", \"Ion\", \"Maria\"];\n    $total = count($utilizatori);\n    ?>\n    <h1>Utilizatori înregistrați: <?= $total ?></h1>\n    <ul>\n    <?php foreach ($utilizatori as $user): ?>\n        <li><?= htmlspecialchars($user) ?></li>\n    <?php endforeach; ?>\n    </ul>\n</body>\n</html>\n```\n\n**Debugging în PHP — unelte esențiale:**\n```php\n<?php\n// 1. var_dump — arată tip + valoare:\nvar_dump($variabila);\n\n// 2. print_r — arată array-uri lizibil:\nprint_r([\"a\" => 1, \"b\" => 2]);\n\n// 3. die() / exit() — oprește execuția (util la debug rapid):\ndie(\"A ajuns până aici!\");\n\n// 4. error_log — scrie în log fără a afecta output-ul:\nerror_log(\"Valoarea e: \" . $x);\n\n// 5. error_reporting — activează toate erorile (în dev):\nerror_reporting(E_ALL);\nini_set('display_errors', 1);\n```\n\n**La interviu:** Diferența dintre `echo` și `print`? Echo poate afișa mai multe argumente separate prin virgulă, print returnează întotdeauna 1. În practică: echo e folosit aproape exclusiv.",
      },
    ],
    tasks: [
      {
        number: 1,
        name: "Tag PHP",
        question: "Care este tagul de deschidere corect pentru cod PHP?",
        options: ["<php>", "<?php", "<script type=\"php\">", "<%php"],
        answer: "<?php",
        explanation: "Codul PHP se scrie întotdeauna după tagul <?php. Tagul de închidere ?> e opțional în fișierele PHP pure.",
        difficulty: "easy",
      },
      {
        number: 2,
        name: "Echo basic",
        question: "Ce afișează `echo \"Bună ziua!\";`?",
        options: ["\"Bună ziua!\"", "Bună ziua!", "echo Bună ziua!", "Eroare"],
        answer: "Bună ziua!",
        explanation: "echo afișează conținutul fără ghilimele.",
        difficulty: "easy",
      },
      {
        number: 3,
        name: "Concatenare",
        question: "Care operator se folosește în PHP pentru a lipi două șiruri?",
        options: ["+", ".", "&", "++"],
        answer: ".",
        explanation: "În PHP, operatorul . (punct) concatenează șiruri. JavaScript folosește + dar PHP folosește .",
        difficulty: "easy",
      },
      {
        number: 4,
        name: "Terminare instrucțiune",
        question: "Cu ce se termină fiecare instrucțiune PHP?",
        options: [".", ":", ";", "newline"],
        answer: ";",
        explanation: "Punct și virgulă (;) termină fiecare instrucțiune PHP. Lipsa lui provoacă eroare fatală de sintaxă.",
        difficulty: "easy",
      },
      {
        number: 5,
        name: "Unde rulează PHP",
        question: "Unde rulează codul PHP?",
        options: ["În browser", "Pe server", "În baza de date", "În terminal client"],
        answer: "Pe server",
        explanation: "PHP e un limbaj server-side — rulează pe server și trimite HTML gata procesat la browser. Browserul nu vede codul PHP.",
        difficulty: "easy",
      },
      {
        number: 6,
        name: "var_dump",
        question: "Ce afișează `var_dump(\"PHP\");`?",
        options: ["PHP", "string PHP", "string(3) \"PHP\"", "text(3) PHP"],
        answer: "string(3) \"PHP\"",
        explanation: "var_dump() afișează tipul și valoarea. string(3) înseamnă string de 3 caractere.",
        difficulty: "medium",
      },
      {
        number: 7,
        name: "Boolean echo",
        question: "Ce afișează `echo true;` în PHP?",
        options: ["true", "TRUE", "1", "yes"],
        answer: "1",
        explanation: "echo true afișează 1 în PHP. echo false afișează un string gol (nimic vizibil). Asta e un comportament specific PHP.",
        difficulty: "medium",
      },
      {
        number: 8,
        name: "Short echo",
        question: "Ce face `<?= \"Salut\" ?>`?",
        options: [
          "Produce eroare — sintaxă greșită",
          "Echivalent cu <?php echo \"Salut\"; ?>",
          "Definește o variabilă",
          "Comentează codul",
        ],
        answer: "Echivalent cu <?php echo \"Salut\"; ?>",
        explanation: "<?= este shorthand pentru <?php echo. E frecvent folosit în template-uri PHP pentru cod mai curat.",
        difficulty: "medium",
      },
      {
        number: 9,
        name: "Constantă PHP",
        question: "Cum definești o constantă numită MAX_SIZE cu valoarea 100?",
        options: [
          "const $MAX_SIZE = 100;",
          "define(\"MAX_SIZE\", 100);",
          "$MAX_SIZE = const 100;",
          "constant MAX_SIZE = 100;",
        ],
        answer: "define(\"MAX_SIZE\", 100);",
        explanation: "define() sau const definesc constante. Constantele nu au $ în față și nu pot fi modificate ulterior.",
        difficulty: "medium",
      },
      {
        number: 10,
        name: "PHP_VERSION",
        question: "Ce conține constanta predefinită `PHP_VERSION`?",
        options: ["Numărul de linie curent", "Versiunea PHP instalată", "Versiunea Apache", "Data build-ului"],
        answer: "Versiunea PHP instalată",
        explanation: "PHP_VERSION e una din constantele predefinite. Alte exemple: PHP_INT_MAX, PHP_EOL, PHP_OS.",
        difficulty: "easy",
      },
    ],
  },
  {
    slug: "php-variabile-tipuri",
    title: "2. Variabile și tipuri de date",
    order: 2,
    theory: [
      {
        order: 1,
        title: "Variabilele PHP — dolarul e obligatoriu și de ce",
        content: "Variabila e o **cutie cu etichetă**. Eticheta e numele variabilei, conținutul e valoarea. În PHP, TOATE etichetele încep cu `$` — asta îi permite parser-ului PHP să distingă variabilele de cuvintele cheie și funcții.\n\n```php\n<?php\n$varsta = 25;          // cutia \"varsta\" conține 25\n$nume = \"Ana\";         // cutia \"nume\" conține \"Ana\"\n$pret = 9.99;          // cutia \"pret\" conține 9.99\n$activ = true;         // cutia \"activ\" conține true\n\necho $varsta;  // 25\necho $nume;    // Ana\n```\n\n**Reguli pentru nume de variabile:**\n```\nValide:\n$varsta           ← simplu\n$numeComplet      ← camelCase (recomandat)\n$pret_total       ← snake_case (acceptat)\n$_dataSistem      ← cu underscore la start\n\nNEvalide:\n$2variabila       ← nu poate începe cu cifră\n$variabila-mea    ← cratima e operator minus!\n$class            ← cuvânt rezervat PHP\n```\n\n**Variabilele sunt case-sensitive!** $Varsta ≠ $varsta:\n```php\n<?php\n$Varsta = 30;   // variabilă diferită!\n$varsta = 25;\necho $Varsta;   // 30\necho $varsta;   // 25\n```\n\n**Asignare prin referință (interviu!)** — două variabile la aceeași valoare în memorie:\n```php\n<?php\n$a = 10;\n$b = &$a;   // $b pointează la aceeași locație ca $a\n$b = 20;\necho $a;    // 20 — s-a schimbat prin $b!\nunset($b);  // dezleagă referința, $a rămâne 20\necho $a;    // 20\n```",
      },
      {
        order: 2,
        title: "Type Juggling — PHP schimbă tipurile automat",
        content: "PHP e **loosely typed**: nu declari tipul și PHP îl schimbă automat în funcție de context. Asta se numește **type juggling** (jonglerie cu tipuri) și e o sursă majoră de bug-uri pentru cei care nu știu cum funcționează.\n\n```php\n<?php\n// PHP convertește string → int când aduni:\n$x = \"5\" + 3;      // \"5\" devine 5 → rezultat: int(8)\n$y = \"5.5\" + 1.5;  // \"5.5\" devine 5.5 → rezultat: float(7)\n$z = \"5abc\" + 2;   // \"5abc\" devine 5 → rezultat: int(7)\n$w = \"abc\" + 1;    // \"abc\" devine 0 → rezultat: int(1)\n\nvar_dump($x);  // int(8)\n```\n\n**Compararea e CRITICĂ la interviu — == vs ===:**\n```php\n<?php\n// == (loose) — compară DOAR valori, convertind tipurile:\nvar_dump(0 == \"foo\");    // PHP 7: true(!), PHP 8: false\nvar_dump(0 == \"\");       // PHP 7: true(!), PHP 8: false\nvar_dump(\"1\" == 1);      // true — string \"1\" devine int 1\nvar_dump(\"1\" == true);   // true\nvar_dump(\"\" == false);   // true\nvar_dump(null == false); // true\n\n// === (strict) — compară valori ȘI tipuri:\nvar_dump(\"1\" === 1);     // false — tip diferit\nvar_dump(1 === 1);       // true\nvar_dump(null === false); // false — tipuri diferite\n```\n\n**Regula de aur:** Folosește ÎNTOTDEAUNA `===` în loc de `==`. Salvează-te de bug-uri obscure!\n\n**Tabelă de conversie automată:**\n```\nValoare → bool:  0, \"0\", \"\", null, [] → false; orice altceva → true\nValoare → int:   true → 1, false → 0, null → 0, \"42abc\" → 42\nValoare → string: true → \"1\", false → \"\", null → \"\"\n```",
      },
      {
        order: 3,
        title: "Casting explicit și funcțiile is_* și isset/empty",
        content: "Uneori vrei tu să controlezi conversia tipurilor, nu să lași PHP să o facă automat — **casting explicit**:\n\n```php\n<?php\n$sir = \"42\";\n\n// Metoda 1 — cast cu paranteze:\n$numar = (int)$sir;       // 42\n$float = (float)\"3.14\";  // 3.14\n$bool  = (bool)0;         // false\n$arr   = (array)\"text\";  // [\"text\"]\n\n// Metoda 2 — funcții de conversie:\n$n = intval(\"42abc\");    // 42 (citește de la stânga)\n$f = floatval(\"3.14x\");  // 3.14\n$s = strval(123);         // \"123\"\n$b = boolval(\"0\");        // false\n```\n\n**Funcții de verificare — is_*():**\n```php\n<?php\nvar_dump(is_int(42));        // true\nvar_dump(is_integer(42));    // true (alias)\nvar_dump(is_float(3.14));    // true\nvar_dump(is_string(\"text\")); // true\nvar_dump(is_bool(true));     // true\nvar_dump(is_null(null));     // true\nvar_dump(is_array([1,2]));   // true\nvar_dump(is_numeric(\"42\"));  // true — string numeric!\nvar_dump(is_numeric(\"42x\")); // false\n```\n\n**isset() vs empty() — diferențe importante:**\n```php\n<?php\n$x = 0;\n$y = \"\";\n$z = null;\n// $w nu există\n\nvar_dump(isset($x));  // true  — există și nu e null\nvar_dump(isset($z));  // false — e null\nvar_dump(isset($w));  // false — nu există\n\nvar_dump(empty($x));  // true  — 0 e considerat empty\nvar_dump(empty($y));  // true  — \"\" e considerat empty\nvar_dump(empty($z));  // true  — null e considerat empty\n// empty = true pentru: 0, 0.0, \"0\", \"\", null, false, []\n\n// ATENȚIE: isset() nu aruncă warning, empty() nici atât:\nvar_dump(empty($variabilaInexistenta)); // true — fără warning!\n```",
      },
      {
        order: 4,
        title: "Scope și variabilele superglobale",
        content: "**Scope** (domeniu de vizibilitate) în PHP e diferit față de JavaScript — variabilele globale NU sunt automat disponibile în funcții!\n\n```php\n<?php\n$mesaj = \"Salut global\";\n\nfunction afiseaza() {\n    echo $mesaj;  // Warning: Undefined variable $mesaj!\n}\n\nfunction afiseazaCorect() {\n    global $mesaj;  // importă explicit variabila globală\n    echo $mesaj;    // Salut global\n}\n\n// Alternativă — prin parametru (recomandat):\nfunction afiseazaCurat(string $m) {\n    echo $m;\n}\nafiseazaCurat($mesaj);\n```\n\n**static** — variabilă locală care persistă între apeluri:\n```php\n<?php\nfunction incrementeaza(): int {\n    static $contor = 0;  // se inițializează o singură dată!\n    return ++$contor;\n}\necho incrementeaza();  // 1\necho incrementeaza();  // 2\necho incrementeaza();  // 3\n```\n\n**Variabilele superglobale** — disponibile oriunde, automat:\n```php\n<?php\n// Date din cerere:\n$_GET[\"id\"]     // din URL: ?id=5\n$_POST[\"email\"] // din form POST\n$_REQUEST       // GET + POST + COOKIE combinate\n\n// Informații server:\n$_SERVER[\"REQUEST_METHOD\"]  // \"GET\" sau \"POST\"\n$_SERVER[\"HTTP_HOST\"]       // \"example.com\"\n$_SERVER[\"REQUEST_URI\"]     // \"/pagina?id=5\"\n$_SERVER[\"REMOTE_ADDR\"]     // IP-ul clientului\n\n// Sesiuni și cookies:\n$_SESSION[\"user_id\"]        // date sesiune\n$_COOKIE[\"preferinta\"]      // cookies browser\n\n// Upload fișiere:\n$_FILES[\"avatar\"]           // date fișier uploadat\n\n// Toate variabilele globale:\n$GLOBALS[\"variabila\"]       // accesează orice global\n```\n\n**La interviu:** *\"De ce e recomandat să eviți variabilele globale?\"* — Răspuns: Creează coupling implicit, fac codul greu de testat și depanare dificilă. Preferă injectarea prin parametri.",
      },
    ],
    tasks: [
      {
        number: 1,
        name: "Prefix variabilă",
        question: "Cum se declară corect o variabilă în PHP?",
        options: ["varsta = 25;", "var varsta = 25;", "$varsta = 25;", "int varsta = 25;"],
        answer: "$varsta = 25;",
        explanation: "În PHP orice variabilă trebuie să înceapă cu $. Nu se specifică tipul explicit (PHP e dinamic).",
        difficulty: "easy",
      },
      {
        number: 2,
        name: "Type juggling",
        question: "Ce valoare are `$x` după `$x = \"5\" + 3;`?",
        options: ["\"53\"", "53", "8", "Eroare"],
        answer: "8",
        explanation: "PHP convertește automat string-ul \"5\" la integer 5 și adună 3, rezultând int(8). Asta e type juggling.",
        difficulty: "medium",
      },
      {
        number: 3,
        name: "Comparare strictă",
        question: "Ce returnează `\"1\" === 1` în PHP?",
        options: ["true", "false", "1", "null"],
        answer: "false",
        explanation: "=== compară și tipul. \"1\" e string iar 1 e integer — tipuri diferite → false. Cu == ar fi true (loose comparison).",
        difficulty: "medium",
      },
      {
        number: 4,
        name: "isset vs empty",
        question: "Ce returnează `isset($x)` dacă `$x = 0`?",
        options: ["false — 0 e falsy", "true — există și nu e null", "null", "Eroare"],
        answer: "true — există și nu e null",
        explanation: "isset() returnează true dacă variabila există și nu e null. 0 există și nu e null → true. empty(0) ar fi false!",
        difficulty: "medium",
      },
      {
        number: 5,
        name: "empty()",
        question: "Care valoare NU face `empty($v)` să returneze true?",
        options: ["0", "\"\"", "\"hello\"", "false"],
        answer: "\"hello\"",
        explanation: "empty() returnează true pentru: 0, 0.0, \"\", \"0\", null, false, []. String non-gol \"hello\" e considerat non-empty.",
        difficulty: "medium",
      },
      {
        number: 6,
        name: "Global scope",
        question: "Cum accesezi o variabilă globală `$config` din interiorul unei funcții PHP?",
        options: [
          "Automat — PHP importă variabilele globale",
          "global $config;",
          "import $config;",
          "use $config;",
        ],
        answer: "global $config;",
        explanation: "În PHP variabilele globale nu sunt automat disponibile în funcții. Trebuie declarate cu global sau accesate prin $GLOBALS[\"config\"].",
        difficulty: "medium",
      },
      {
        number: 7,
        name: "Casting",
        question: "Ce afișează `echo (int)\"42abc\";`?",
        options: ["42abc", "Eroare", "42", "0"],
        answer: "42",
        explanation: "Casting (int) pe string extrage numărul de la început și se oprește la primul caracter non-numeric. \"42abc\" → 42.",
        difficulty: "medium",
      },
      {
        number: 8,
        name: "Referință",
        question: "Ce afișează `$a = 5; $b = &$a; $b = 10; echo $a;`?",
        options: ["5", "10", "Eroare", "null"],
        answer: "10",
        explanation: "$b = &$a înseamnă că $b și $a referă aceeași locație în memorie. Schimbând $b, se schimbă și $a.",
        difficulty: "hard",
      },
      {
        number: 9,
        name: "static variabilă",
        question: "Ce afișează a 3-a apelare a funcției: `function f() { static $n=0; echo ++$n; }`?",
        options: ["0", "1", "3", "Eroare"],
        answer: "3",
        explanation: "static $n se inițializează o singură dată. La fiecare apel valoarea persistă: apel 1→1, apel 2→2, apel 3→3.",
        difficulty: "hard",
      },
      {
        number: 10,
        name: "is_numeric",
        question: "Ce returnează `is_numeric(\"42\")` în PHP?",
        options: ["false — e string, nu număr", "true", "42", "Eroare"],
        answer: "true",
        explanation: "is_numeric() returnează true dacă valoarea reprezintă un număr valid (int sau float), indiferent că e string sau număr.",
        difficulty: "medium",
      },
    ],
  },
  {
    slug: "php-conditii",
    title: "3. Condiții — if, else, switch, match",
    order: 3,
    theory: [
      {
        order: 1,
        title: "if / elseif / else — luarea deciziilor în cod",
        content: "Condițiile sunt locul unde codul tău ia **decizii**. E ca un semafor: dacă e verde mergi, dacă e roșu oprești.\n\n```php\n<?php\n$ora = 14;\n\nif ($ora < 12) {\n    echo \"Bună dimineața!\";\n} elseif ($ora < 18) {\n    echo \"Bună ziua!\";      // aceasta se afișează\n} elseif ($ora < 22) {\n    echo \"Bună seara!\";\n} else {\n    echo \"Noapte bună!\";\n}\n```\n\n**Operatori de comparare:**\n```\n==   egal loose (evită!)\n===  egal strict (folosește asta!)\n!=   diferit loose\n!==  strict diferit\n>    mai mare\n<    mai mic\n>=   mai mare sau egal\n<=   mai mic sau egal\n```\n\n**Operatori logici — combini condiții:**\n```php\n<?php\n$varsta = 25;\n$are_permis = true;\n\n// && = AND — ambele trebuie true:\nif ($varsta >= 18 && $are_permis) {\n    echo \"Poate conduce\";\n}\n\n// || = OR — cel puțin una true:\nif ($varsta < 16 || !$are_permis) {\n    echo \"Nu poate conduce\";\n}\n\n// ! = negare:\nif (!$are_permis) {\n    echo \"Fără permis\";\n}\n```\n\n**Ternary — if pe o linie:**\n```php\n<?php\n$varsta = 20;\n$status = ($varsta >= 18) ? \"adult\" : \"minor\";\necho $status;  // adult\n\n// Nesting ternary e permis DAR ilizibil — evită:\n// $r = $a ? \"a\" : ($b ? \"b\" : \"c\");  ← greu de citit\n```",
      },
      {
        order: 2,
        title: "Null coalescing (??) și operatorul spaceship (<=>)",
        content: "PHP 7+ a adăugat operatori moderni care simplifică mult codul comun:\n\n**Null coalescing (??)** — valoare default dacă null sau inexistent:\n```php\n<?php\n// Situație comună: valoare din URL sau default:\n\n// Înainte de ??:\nif (isset($_GET[\"pagina\"])) {\n    $pagina = $_GET[\"pagina\"];\n} else {\n    $pagina = 1;\n}\n\n// Cu ?? (mult mai clar):\n$pagina = $_GET[\"pagina\"] ?? 1;\n\n// Se poate înlănțui:\n$val = $a ?? $b ?? $c ?? \"implicit\";\n\n// ??= assignment:\n$vizitatori ??= 0;  // echivalent: $vizitatori = $vizitatori ?? 0\n$vizitatori++;\n```\n\n**Spaceship operator (<=>)** — pentru comparare și sortare:\n```php\n<?php\n// Returnează -1 dacă stânga < dreapta\n//            0 dacă egale\n//            1 dacă stânga > dreapta\n\necho 1 <=> 2;   // -1\necho 5 <=> 5;   // 0\necho 8 <=> 3;   // 1\n\n// Cel mai util: sortare cu usort:\n$produse = [\n    [\"nume\" => \"Laptop\",  \"pret\" => 3000],\n    [\"nume\" => \"Mouse\",   \"pret\" => 80],\n    [\"nume\" => \"Monitor\", \"pret\" => 1500],\n];\n\nusort($produse, fn($a, $b) => $a[\"pret\"] <=> $b[\"pret\"]);\n// Sortate crescător după preț: Mouse, Monitor, Laptop\n\n// Sortare descrescătoare:\nusort($produse, fn($a, $b) => $b[\"pret\"] <=> $a[\"pret\"]);\n```",
      },
      {
        order: 3,
        title: "switch vs match — vechi și nou",
        content: "**switch** — structura clasică pentru valori multiple:\n```php\n<?php\n$zi = \"luni\";\nswitch ($zi) {\n    case \"luni\":\n    case \"marti\":\n    case \"miercuri\":\n    case \"joi\":\n    case \"vineri\":\n        echo \"Zi lucrătoare\";\n        break;   // ESENȚIAL: fără break, continuă la cazul următor!\n    case \"sambata\":\n    case \"duminica\":\n        echo \"Weekend\";\n        break;\n    default:\n        echo \"Zi necunoscută\";\n}\n```\n\n**3 probleme cu switch:**\n1. **Fallthrough** fără break — execuția continuă la case-urile următoare\n2. **Compară cu ==** (loose) — risc de type juggling\n3. Nu e o expresie — nu poți asigna rezultatul direct\n\n**match** — versiunea PHP 8 care rezolvă toate problemele:\n```php\n<?php\n$cod = 404;\n\n// match e o EXPRESIE — returnează valoarea:\n$mesaj = match($cod) {\n    200      => \"OK\",\n    301, 302 => \"Redirect\",\n    404      => \"Not Found\",\n    500      => \"Server Error\",\n    default  => \"Unknown Status\",\n};\necho $mesaj;  // Not Found\n\n// Avantajele match față de switch:\n// 1. Folosește === (strict) — mai sigur\n// 2. Nu are fallthrough — fiecare arm e independent\n// 3. E o expresie — poate fi asignat sau returnat\n// 4. Aruncă UnhandledMatchError fără default — nu tace greșelile\n```\n\n**La interviu:** *\"Când preferi match în loc de switch?\"* — Răspuns: Când compari o valoare cu mai multe posibilități și vrei tipizare strictă. match e mai sigur și mai clar.",
      },
      {
        order: 4,
        title: "Valori truthy și falsy — ce PHP consideră true/false",
        content: "Înțelegerea valorilor truthy/falsy e esențială pentru a evita bug-uri ascunse:\n\n**Valori FALSY în PHP** — sunt tratate ca false în condiții:\n```php\n<?php\n// Aceste valori toate → false:\nif (0)       { }  // NU intră\nif (0.0)     { }  // NU intră\nif (\"\")      { }  // NU intră — string gol\nif (\"0\")     { }  // NU intră — atenție! string zero\nif (null)    { }  // NU intră\nif (false)   { }  // NU intră\nif ([])      { }  // NU intră — array gol\n```\n\n**Valori TRUTHY** — tot ce nu e în lista de sus:\n```php\n<?php\nif (1)          { }  // intră\nif (-1)         { }  // intră — negativele sunt truthy!\nif (\"0.0\")      { }  // intră — string \"0.0\" e truthy (doar \"0\" e falsy!)\nif (\"false\")    { }  // intră — string non-gol e truthy\nif ([0])        { }  // intră — array cu un element, chiar dacă e 0\nif (new stdClass()) { }  // intră — obiectele sunt truthy\n```\n\n**Capcanele comune:**\n```php\n<?php\n$rezultate = [];  // array gol\nif ($rezultate) {\n    // NU intră — array gol e falsy!\n}\n// Corect:\nif (count($rezultate) > 0) { ... }\n// sau:\nif (!empty($rezultate)) { ... }\n\n$id = 0;\nif ($id) {\n    // NU intră — 0 e falsy!\n    // Bug dacă aștepți id=0 valid\n}\n// Corect:\nif ($id !== null) { ... }\nif (isset($id)) { ... }\n```\n\n**La interviu:** *\"Ce înseamnă că PHP e loosely typed?\"* — Răspuns: Tipul variabilelor se schimbă automat în funcție de context (type juggling), iar comparațiile cu == pot da rezultate surprinzătoare. De aceea folosim === și type hints în cod modern.",
      },
    ],
    tasks: [
      {
        number: 1,
        name: "Condiție simplă",
        question: "Ce afișează codul:\n```php\n$x = 10;\nif ($x > 5) {\n    echo \"mare\";\n} else {\n    echo \"mic\";\n}\n```",
        options: ["mic", "mare", "10", "Eroare"],
        answer: "mare",
        explanation: "10 > 5 este true, deci se execută ramura if și se afișează \"mare\".",
        difficulty: "easy",
      },
      {
        number: 2,
        name: "Ternary",
        question: "Ce afișează `echo (5 > 3) ? \"da\" : \"nu\";`?",
        options: ["da", "nu", "true", "1"],
        answer: "da",
        explanation: "5 > 3 este true, deci operatorul ternary returnează primul termen: \"da\".",
        difficulty: "easy",
      },
      {
        number: 3,
        name: "Null coalescing",
        question: "Ce afișează `echo $_GET[\"id\"] ?? \"niciun id\";` dacă nu există parametrul id în URL?",
        options: ["null", "Eroare", "niciun id", "0"],
        answer: "niciun id",
        explanation: "?? returnează valoarea din dreapta dacă stânga e null sau variabila nu există.",
        difficulty: "medium",
      },
      {
        number: 4,
        name: "break în switch",
        question: "Ce se întâmplă în switch dacă uiți `break` la un case?",
        options: [
          "Eroare de compilare",
          "Se oprește automat la next case",
          "Execuția continuă și în case-urile următoare (fallthrough)",
          "Nimic — se oprește la default",
        ],
        answer: "Execuția continuă și în case-urile următoare (fallthrough)",
        explanation: "Fără break, PHP continuă să execute case-urile de dedesubt chiar dacă nu se potrivesc — comportament numit fallthrough.",
        difficulty: "medium",
      },
      {
        number: 5,
        name: "match strict",
        question: "Care e diferența principală între match și switch în PHP?",
        options: [
          "match folosește == (loose), switch folosește ===",
          "match folosește === (strict), switch folosește ==",
          "Ambele folosesc ===",
          "match nu are default",
        ],
        answer: "match folosește === (strict), switch folosește ==",
        explanation: "match compară strict (tip + valoare), mai sigur. switch folosește == cu risc de type juggling.",
        difficulty: "medium",
      },
      {
        number: 6,
        name: "Falsy values",
        question: "Care dintre valorile de mai jos este TRUTHY în PHP?",
        options: ["0", "\"0\"", "[]", "\"-1\""],
        answer: "\"-1\"",
        explanation: "String-ul \"-1\" e truthy — e un string non-gol care nu e \"0\". 0, \"0\", și [] sunt falsy.",
        difficulty: "hard",
      },
      {
        number: 7,
        name: "Spaceship operator",
        question: "Ce returnează `5 <=> 2`?",
        options: ["3", "1", "-1", "true"],
        answer: "1",
        explanation: "Spaceship <=> returnează 1 dacă stânga > dreapta, -1 dacă stânga < dreapta, 0 dacă egale.",
        difficulty: "medium",
      },
      {
        number: 8,
        name: "match UnhandledMatchError",
        question: "Ce se întâmplă dacă nicio ramură din match nu se potrivește și nu există `default`?",
        options: [
          "Returnează null",
          "Aruncă UnhandledMatchError",
          "Execută prima ramură",
          "Nu se întâmplă nimic",
        ],
        answer: "Aruncă UnhandledMatchError",
        explanation: "Spre deosebire de switch, match e strict — dacă nicio valoare nu se potrivește fără default, PHP aruncă excepție.",
        difficulty: "medium",
      },
      {
        number: 9,
        name: "Null coalescing assignment",
        question: "Ce face `$contor ??= 0;`?",
        options: [
          "Setează $contor la 0 întotdeauna",
          "Setează $contor la 0 doar dacă e null sau nedefinit",
          "Verifică dacă $contor e 0",
          "Eroare de sintaxă",
        ],
        answer: "Setează $contor la 0 doar dacă e null sau nedefinit",
        explanation: "??= e echivalent cu $contor = $contor ?? 0. Asignează valoarea default doar dacă variabila e null/inexistentă.",
        difficulty: "medium",
      },
      {
        number: 10,
        name: "Condiție compusă",
        question: "Ce afișează: `$v = 25; echo ($v >= 18 && $v < 65) ? \"angajabil\" : \"nu\";`",
        options: ["nu", "angajabil", "25", "Eroare"],
        answer: "angajabil",
        explanation: "25 >= 18 este true ȘI 25 < 65 este true, deci condiția && e true → \"angajabil\".",
        difficulty: "easy",
      },
    ],
  },
  {
    slug: "php-bucle",
    title: "4. Bucle — for, while, foreach",
    order: 4,
    theory: [
      {
        order: 1,
        title: "for și while — când și cum le folosești",
        content: "Buclele sunt mecanismul prin care codul repetă acțiuni. E ca o mașină de spălat: trece prin fiecare etapă de mai multe ori.\n\n**for** — când știi EXACT de câte ori:\n```php\n<?php\n// Structura: for (init; condiție; pas)\nfor ($i = 0; $i < 5; $i++) {\n    echo $i . \" \";     // 0 1 2 3 4\n}\n\n// Inversare:\nfor ($i = 10; $i >= 0; $i -= 2) {\n    echo $i . \" \";     // 10 8 6 4 2 0\n}\n\n// Pasuri mai mari:\nfor ($i = 0; $i <= 100; $i += 10) {\n    echo $i . \" \";     // 0 10 20 ... 100\n}\n```\n\n**while** — când nu știi de câte ori, dar ai o condiție:\n```php\n<?php\n// Citește pagini dintr-o API până nu mai sunt:\n$pagina = 1;\n$mai_sunt = true;\nwhile ($mai_sunt) {\n    $date = getDateAPI($pagina);\n    if (empty($date)) {\n        $mai_sunt = false;\n    } else {\n        proceseaza($date);\n        $pagina++;\n    }\n}\n\n// Exemplu simplu:\n$n = 1;\nwhile ($n <= 5) {\n    echo $n * $n . \" \";  // pătrate: 1 4 9 16 25\n    $n++;\n}\n```\n\n**do-while** — garantează cel puțin O execuție:\n```php\n<?php\n// Util pentru validare input:\ndo {\n    $input = readline(\"Introdu un număr pozitiv: \");\n} while ((int)$input <= 0);\n\n// Exemplu cu număr:\n$n = 100;\ndo {\n    echo $n . \" \";\n    $n++;\n} while ($n < 5);\n// Afișează 100 — execuție o singură dată, condiția e false din start\n```",
      },
      {
        order: 2,
        title: "foreach — pentru arrays și obiecte",
        content: "**foreach** e cel mai folosit loop în PHP — parcurge automat fiecare element dintr-un array:\n\n```php\n<?php\n$fructe = [\"mar\", \"para\", \"pruna\", \"cireasa\"];\n\n// Fără index — când ai nevoie doar de valori:\nforeach ($fructe as $fruct) {\n    echo $fruct . \"\\n\";\n}\n\n// Cu index — când ai nevoie și de poziție:\nforeach ($fructe as $i => $fruct) {\n    echo \"$i: $fruct\\n\";\n}\n// 0: mar, 1: para, etc.\n\n// Array asociativ:\n$user = [\"id\" => 1, \"nume\" => \"Ana\", \"rol\" => \"admin\"];\nforeach ($user as $cheie => $valoare) {\n    echo \"$cheie => $valoare\\n\";\n}\n// id => 1, nume => Ana, rol => admin\n\n// Array de obiecte/arrays (cel mai comun în practică):\n$produse = [\n    [\"id\" => 1, \"nume\" => \"Laptop\",  \"pret\" => 3000],\n    [\"id\" => 2, \"nume\" => \"Mouse\",   \"pret\" => 80],\n    [\"id\" => 3, \"nume\" => \"Monitor\", \"pret\" => 1500],\n];\nforeach ($produse as $produs) {\n    echo \"{$produs['nume']}: {$produs['pret']} RON\\n\";\n}\n```\n\n**Modificare cu referință** — schimbi valorile direct:\n```php\n<?php\n$preturi = [100, 200, 300];\n\n// Aplică TVA 19%:\nforeach ($preturi as &$pret) {  // & = referință\n    $pret = round($pret * 1.19);\n}\nunset($pret);  // IMPORTANT: eliberează referința după loop!\n\nprint_r($preturi);  // [119, 238, 357]\n```\n\n**De ce unset după &?** Fără unset, `$pret` rămâne referință la ultimul element. Dacă mai folosești `$pret` după, vei modifica accidental ultimul element din array!",
      },
      {
        order: 3,
        title: "break și continue — control avansat al buclelor",
        content: "**break** — iese complet din buclă:\n```php\n<?php\n// Caută primul produs scump:\n$produse = [50, 120, 80, 2500, 300];\n$gasit = null;\n\nforeach ($produse as $pret) {\n    if ($pret > 1000) {\n        $gasit = $pret;\n        break;  // am găsit, nu mai parcurgem restul\n    }\n}\necho $gasit;  // 2500\n\n// break cu nivel — iese din mai multe bucle:\nfor ($i = 0; $i < 5; $i++) {\n    for ($j = 0; $j < 5; $j++) {\n        if ($i + $j > 5) {\n            break 2;  // iese din AMBELE bucle\n        }\n        echo \"$i,$j \";\n    }\n}\n```\n\n**continue** — sare iterația curentă:\n```php\n<?php\n// Procesează doar produsele active:\n$produse = [\n    [\"nume\" => \"A\", \"activ\" => true],\n    [\"nume\" => \"B\", \"activ\" => false],\n    [\"nume\" => \"C\", \"activ\" => true],\n];\n\nforeach ($produse as $p) {\n    if (!$p[\"activ\"]) continue;  // sare produsele inactive\n    proceseaza($p);\n}\n\n// Numere impare:\nfor ($i = 1; $i <= 10; $i++) {\n    if ($i % 2 === 0) continue;  // sare parele\n    echo $i . \" \";  // 1 3 5 7 9\n}\n```",
      },
      {
        order: 4,
        title: "Performanță în bucle — greșeli comune la interviu",
        content: "La interviuri tehnice sunt întrebări despre eficiența buclelor. Iată ce trebuie să știi:\n\n**1. count() în condiție — cea mai comună greșeală:**\n```php\n<?php\n// GREȘIT — count() se apelează la FIECARE iterație:\nfor ($i = 0; $i < count($array); $i++) {\n    // ...\n}\n\n// CORECT — calculat o singură dată:\n$n = count($array);\nfor ($i = 0; $i < $n; $i++) {\n    // ...\n}\n\n// Cu foreach — cel mai bun în PHP (iterează intern eficient):\nforeach ($array as $elem) {\n    // ...\n}\n```\n\n**2. Bucle imbricate (nested) — O(n²):**\n```php\n<?php\n// Slab — O(n²):\nforeach ($users as $user) {\n    foreach ($roles as $role) {\n        if ($user[\"role_id\"] === $role[\"id\"]) {\n            $user[\"role_name\"] = $role[\"name\"];\n        }\n    }\n}\n\n// Bine — O(n) cu hash map:\n$roleMap = array_column($roles, \"name\", \"id\");  // id => name\nforeach ($users as &$user) {\n    $user[\"role_name\"] = $roleMap[$user[\"role_id\"]] ?? \"unknown\";\n}\n```\n\n**3. Construirea stringului în buclă:**\n```php\n<?php\n// Slab — concatenare repetată:\n$html = \"\";\nforeach ($items as $item) {\n    $html .= \"<li>$item</li>\";  // re-alocă memoria la fiecare iterație\n}\n\n// Bine — colectezi și unești la final:\n$parts = [];\nforeach ($items as $item) {\n    $parts[] = \"<li>$item</li>\";\n}\n$html = implode(\"\\n\", $parts);\n\n// Și mai bine — array_map:\n$html = implode(\"\\n\", array_map(fn($i) => \"<li>$i</li>\", $items));\n```\n\n**La interviu:** *\"Ce e mai eficient: for sau foreach?\"* — Răspuns: În PHP, foreach e de obicei preferabil pentru arrays — e mai lizibil și PHP optimizează iterarea intern. for e mai potrivit când ai nevoie de index sau pas arbitrar.",
      },
    ],
    tasks: [
      {
        number: 1,
        name: "for basic",
        question: "Câte iterații face `for ($i = 0; $i < 5; $i++)`?",
        options: ["4", "5", "6", "0"],
        answer: "5",
        explanation: "Bucla rulează pentru i = 0, 1, 2, 3, 4 — adică 5 iterații. Se oprește când i ajunge la 5 (5 < 5 e false).",
        difficulty: "easy",
      },
      {
        number: 2,
        name: "foreach asociativ",
        question: "Care sintaxă foreach parcurge și cheile unui array asociativ?",
        options: [
          "foreach ($arr as $val)",
          "foreach ($arr as $key => $val)",
          "foreach ($arr, $key, $val)",
          "for ($arr as [$key, $val])",
        ],
        answer: "foreach ($arr as $key => $val)",
        explanation: "Sintaxa $key => $val în foreach îți dă acces atât la cheie cât și la valoare simultan.",
        difficulty: "easy",
      },
      {
        number: 3,
        name: "do-while",
        question: "Care e diferența principală dintre while și do-while?",
        options: [
          "do-while e mai rapid",
          "do-while se execută cel puțin o dată chiar dacă condiția e false de la început",
          "while verifică la sfârșit",
          "Nu există diferență",
        ],
        answer: "do-while se execută cel puțin o dată chiar dacă condiția e false de la început",
        explanation: "do-while execută codul ÎNAINTE de a verifica condiția, deci rulează garantat minim o dată.",
        difficulty: "medium",
      },
      {
        number: 4,
        name: "continue",
        question: "Ce afișează:\n```php\nfor ($i = 1; $i <= 5; $i++) {\n    if ($i == 3) continue;\n    echo $i . \" \";\n}\n```",
        options: ["1 2 3 4 5", "1 2 4 5", "3", "1 2 3"],
        answer: "1 2 4 5",
        explanation: "continue sare iterația curentă (i=3) și continuă de la i=4. Rezultat: 1 2 4 5.",
        difficulty: "medium",
      },
      {
        number: 5,
        name: "break nivel",
        question: "Ce face `break 2;` din interiorul unei bucle imbricate?",
        options: [
          "Iese din bucla interioară de 2 ori",
          "Iese din 2 niveluri de bucle",
          "Sare 2 iterații",
          "Produce eroare",
        ],
        answer: "Iese din 2 niveluri de bucle",
        explanation: "break N iese din N niveluri de bucle simultan. break 2 iese din bucla curentă și din cea exterioară.",
        difficulty: "medium",
      },
      {
        number: 6,
        name: "Referință foreach",
        question: "De ce e important `unset($n)` după `foreach ($arr as &$n)`?",
        options: [
          "Eliberează memoria",
          "Fără unset, $n rămâne referință la ultimul element și poate fi modificat accidental",
          "Resetează array-ul",
          "Nu e necesar",
        ],
        answer: "Fără unset, $n rămâne referință la ultimul element și poate fi modificat accidental",
        explanation: "Fără unset, variabila $n continuă să pointeze la ultimul element. Dacă o reutilizezi, modifici accidental array-ul.",
        difficulty: "hard",
      },
      {
        number: 7,
        name: "count în buclă",
        question: "De ce e o problemă să apelezi `count($array)` direct în condiția unui for?",
        options: [
          "count() nu funcționează în for",
          "count() se apelează la fiecare iterație, irosind resurse",
          "Produce rezultate incorecte",
          "Nu e nicio problemă",
        ],
        answer: "count() se apelează la fiecare iterație, irosind resurse",
        explanation: "count() e apelat de N ori în loc de 1. Salvează rezultatul înainte de buclă: $n = count($arr); for ($i=0; $i<$n; $i++).",
        difficulty: "medium",
      },
      {
        number: 8,
        name: "array_map vs foreach",
        question: "Care e alternativa funcțională la un foreach care transformă fiecare element?",
        options: ["array_filter()", "array_map()", "array_reduce()", "array_walk()"],
        answer: "array_map()",
        explanation: "array_map() aplică o funcție pe fiecare element și returnează array-ul transformat — mai concis decât un foreach cu array nou.",
        difficulty: "medium",
      },
      {
        number: 9,
        name: "while infinit",
        question: "Ce se întâmplă cu `while (true) { echo \"A\"; }`?",
        options: [
          "Afișează A o singură dată",
          "Produce eroare de sintaxă",
          "Rulează la infinit (loop infinit) până e oprit manual",
          "Nu rulează deloc",
        ],
        answer: "Rulează la infinit (loop infinit) până e oprit manual",
        explanation: "while(true) rulează la nesfârșit. Se oprește doar cu break, exit() sau dacă serverul atinge time_limit.",
        difficulty: "easy",
      },
      {
        number: 10,
        name: "foreach output",
        question: "Ce afișează:\n```php\n$a = [\"x\" => 1, \"y\" => 2];\nforeach ($a as $k => $v) echo \"$k:$v \";\n```",
        options: ["x y", "1 2", "x:1 y:2", "0:1 1:2"],
        answer: "x:1 y:2",
        explanation: "foreach cu => parcurge cheie:valoare. Afișează \"x:1 y:2 \" (cu spațiu la final).",
        difficulty: "medium",
      },
    ],
  },
  {
    slug: "php-functii",
    title: "5. Funcții",
    order: 5,
    theory: [
      {
        order: 1,
        title: "Funcții — reutilizarea codului",
        content: "O funcție e ca o **rețetă de bucătărie**: o scrii o dată, o urmezi ori de câte ori vrei. Fără funcții, codul repetat ar fi un coșmar de menținut.\n\n```php\n<?php\n// Fără funcție — duplicare de cod:\n$rezultat1 = ($a1 + $b1) / 2;\n$rezultat2 = ($a2 + $b2) / 2;\n$rezultat3 = ($a3 + $b3) / 2;\n\n// Cu funcție — o singură sursă a adevărului:\nfunction medie(float $a, float $b): float {\n    return ($a + $b) / 2;\n}\n$r1 = medie(10, 20);  // 15\n$r2 = medie(5, 15);   // 10\n$r3 = medie(3, 7);    // 5\n```\n\n**Structura completă a unei funcții:**\n```php\n<?php\n//         ↓ tip return    ↓ parametri cu tipuri\nfunction saluta(string $nume, string $salut = \"Bună\"): string {\n    //                                   ↑ valoare implicită\n    return \"$salut, $nume!\";\n}\n\necho saluta(\"Ana\");          // Bună, Ana!\necho saluta(\"Ion\", \"Salut\"); // Salut, Ion!\necho saluta(salut: \"Hey\", nume: \"Maria\");  // Named args (PHP 8+)\n```\n\n**PHP permite apelarea funcțiilor ÎNAINTE de definire** (hoisting de funcții):\n```php\n<?php\necho dublu(5);  // 10 — funcționează!\n\nfunction dublu(int $n): int {\n    return $n * 2;\n}\n```\n\n**Variadic — număr variabil de argumente:**\n```php\n<?php\nfunction suma(int ...$numere): int {\n    return array_sum($numere);\n}\necho suma(1, 2, 3, 4, 5);  // 15\n\n// Spread operator — trimite array ca argumente:\n$args = [1, 2, 3];\necho suma(...$args);  // 6\n```",
      },
      {
        order: 2,
        title: "Type hints și strict_types — cod mai sigur",
        content: "**Type hints** (PHP 7+) — specifici tipul parametrilor și valorii returnate. Codul devine documentat automat și erorile sunt prinse mai devreme:\n\n```php\n<?php\n// Fără type hints — orice poate intra:\nfunction dublu($n) {\n    return $n * 2;\n}\ndublu(\"hello\");  // Surprise: funcționează! Returns \"hellohello\" sau 0\n\n// Cu type hints — PHP verifică:\nfunction dublu(int $n): int {\n    return $n * 2;\n}\ndublu(\"hello\");  // TypeError: Argument must be int\n```\n\n**Tipuri disponibile:**\n```php\n<?php\nfunction exemplu(\n    int $a,\n    float $b,\n    string $c,\n    bool $d,\n    array $e,\n    ?string $f = null,  // ? = nullable, poate fi null\n    int|string $g = 0,  // union types (PHP 8+)\n): void {              // void = nu returnează nimic\n    // ...\n}\n```\n\n**declare(strict_types=1)** — forțează tipizarea strictă:\n```php\n<?php\ndeclare(strict_types=1);  // TREBUIE să fie prima linie!\n\nfunction aduna(int $a, int $b): int {\n    return $a + $b;\n}\n\necho aduna(3, 5);       // 8 ✓\necho aduna(\"3\", \"5\");   // TypeError! Cu strict_types, nu face conversie\necho aduna(3.7, 2.1);   // TypeError! Float nu e int\n```\n\n**Fără strict_types**, PHP face conversie silențioasă: `aduna(\"3\", \"5\")` → 8. Cu strict_types ești forțat să trimiți tipurile corecte.",
      },
      {
        order: 3,
        title: "Closures și Arrow Functions — funcții de primă clasă",
        content: "În PHP, funcțiile sunt **first-class citizens** — pot fi asignate la variabile, trimise ca argumente, returnate din alte funcții:\n\n**Closures (funcții anonime):**\n```php\n<?php\n// Asignată la variabilă:\n$patrat = function(int $n): int {\n    return $n * $n;\n};\necho $patrat(5);   // 25\necho $patrat(10);  // 100\n\n// Closure cu use — capturează variabile din exterior:\n$taxa = 0.19;\n$cuTVA = function(float $pret) use ($taxa): float {\n    return $pret * (1 + $taxa);\n};\necho $cuTVA(100);  // 119\n\n// use by reference — poate modifica variabila exterioară:\n$total = 0;\n$adaugaLaTotal = function(float $suma) use (&$total): void {\n    $total += $suma;\n};\n$adaugaLaTotal(100);\n$adaugaLaTotal(200);\necho $total;  // 300\n```\n\n**Arrow functions (PHP 7.4+)** — mai concise, capturează automat:\n```php\n<?php\n$taxa = 0.19;\n\n// Closure clasică:\n$cuTVA = function($p) use ($taxa) { return $p * (1 + $taxa); };\n\n// Arrow function — CAPTEAZĂ AUTOMAT variabilele din exterior:\n$cuTVA = fn($p) => $p * (1 + $taxa);  // nu trebuie use($taxa)!\n\n// Cel mai comun: array_map / array_filter cu arrow:\n$preturi = [100, 200, 300, 400];\n$cuTVA = array_map(fn($p) => round($p * 1.19), $preturi);\n// [119, 238, 357, 476]\n\n$scumpe = array_filter($preturi, fn($p) => $p > 150);\n// [200, 300, 400]\n```",
      },
      {
        order: 4,
        title: "Recursivitate și funcții built-in esențiale",
        content: "**Recursivitate** — funcție care se apelează pe sine. Ca Matrioșka: deschizi păpușa și găsești o păpușă mai mică.\n\n```php\n<?php\nfunction factorial(int $n): int {\n    if ($n <= 1) return 1;               // caz de bază — oprire\n    return $n * factorial($n - 1);      // apel recursiv\n}\n// factorial(5) = 5 * factorial(4)\n//               = 5 * 4 * factorial(3)\n//               = 5 * 4 * 3 * factorial(2)\n//               = 5 * 4 * 3 * 2 * factorial(1)\n//               = 5 * 4 * 3 * 2 * 1 = 120\necho factorial(5);  // 120\n\n// Parcurgere arbore recursiv:\nfunction afiseazaFolderuri(string $path, int $nivel = 0): void {\n    $prefix = str_repeat(\"  \", $nivel);\n    echo $prefix . basename($path) . \"\\n\";\n    if (is_dir($path)) {\n        foreach (scandir($path) as $fisier) {\n            if ($fisier === '.' || $fisier === '..') continue;\n            afiseazaFolderuri($path . '/' . $fisier, $nivel + 1);\n        }\n    }\n}\n```\n\n**Funcții built-in importante la interviu:**\n```php\n<?php\n// Math:\nabs(-42)          // 42\nmax(3, 7, 1)      // 7\nmin(3, 7, 1)      // 1\nround(3.567, 2)   // 3.57\nfloor(3.9)        // 3\nceil(3.1)         // 4\npow(2, 10)        // 1024\nsqrt(16)          // 4\nrand(1, 100)      // număr random între 1 și 100\narray_sum([1,2,3,4,5])  // 15\n\n// Verificare:\nis_numeric(\"42\")   // true\nis_numeric(\"42x\")  // false\n\n// Date:\ndate(\"Y-m-d\")              // \"2024-01-15\"\ndate(\"d.m.Y H:i:s\")        // \"15.01.2024 14:30:00\"\ntime()                      // unix timestamp (secunde de la 1970)\nstrtotime(\"+7 days\")        // timestamp peste 7 zile\nstrtotime(\"2024-12-31\")    // timestamp pentru data dată\n```",
      },
    ],
    tasks: [
      {
        number: 1,
        name: "Definire funcție",
        question: "Care este sintaxa corectă pentru a defini o funcție în PHP?",
        options: [
          "func saluta($n) { }",
          "function saluta($n) { }",
          "def saluta($n): { }",
          "fun saluta($n) => { }",
        ],
        answer: "function saluta($n) { }",
        explanation: "PHP folosește cuvântul cheie function. JavaScript modern folosește și el function, iar Python def.",
        difficulty: "easy",
      },
      {
        number: 2,
        name: "Valoare implicită",
        question: "Ce afișează: `function f($x = 5) { echo $x; } f();`?",
        options: ["Eroare", "null", "0", "5"],
        answer: "5",
        explanation: "Când apelezi f() fără argument, se folosește valoarea implicită 5.",
        difficulty: "easy",
      },
      {
        number: 3,
        name: "Return null implicit",
        question: "Ce returnează o funcție PHP dacă nu are instrucțiunea return?",
        options: ["0", "false", "null", "Eroare"],
        answer: "null",
        explanation: "O funcție PHP fără return returnează implicit null. Dacă ai declarat tipul de return ca altceva, primești TypeError.",
        difficulty: "easy",
      },
      {
        number: 4,
        name: "strict_types",
        question: "Ce face `declare(strict_types=1)` la începutul unui fișier PHP?",
        options: [
          "Activează toate tipurile de date",
          "Forțează respectarea strictă a type hints — fără conversie automată",
          "Dezactivează type juggling global",
          "Activează modul debug",
        ],
        answer: "Forțează respectarea strictă a type hints — fără conversie automată",
        explanation: "Cu strict_types=1, dacă trimiți un string unde se așteaptă int, PHP aruncă TypeError în loc să facă conversia silențioasă.",
        difficulty: "medium",
      },
      {
        number: 5,
        name: "Closure use",
        question: "Cum capturează o funcție anonimă o variabilă din exterior în PHP?",
        options: [
          "Automat, ca în JavaScript",
          "Prin keyword-ul use: function() use ($var) {}",
          "Prin keyword-ul capture",
          "Nu poate captura variabile externe",
        ],
        answer: "Prin keyword-ul use: function() use ($var) {}",
        explanation: "Closure-urile PHP nu captează automat variabilele din scope exterior — trebuie use($var). Arrow functions (fn) captează automat.",
        difficulty: "medium",
      },
      {
        number: 6,
        name: "Arrow function",
        question: "Ce avantaj are o arrow function (fn) față de o closure obișnuită?",
        options: [
          "E mai rapidă în execuție",
          "Captează automat variabilele din exterior fără use",
          "Poate modifica variabilele exterioare",
          "Suportă mai mulți parametri",
        ],
        answer: "Captează automat variabilele din exterior fără use",
        explanation: "Arrow functions (fn() =>) captează implicit variabilele din scope-ul exterior, fără a scrie use().",
        difficulty: "medium",
      },
      {
        number: 7,
        name: "Variadic",
        question: "Cum definești o funcție care acceptă un număr variabil de argumente?",
        options: [
          "function f($args[]) { }",
          "function f(...$args) { }",
          "function f(*args) { }",
          "function f($args = []) { }",
        ],
        answer: "function f(...$args) { }",
        explanation: "Operatorul ... (splat) colectează argumentele extra într-un array $args.",
        difficulty: "medium",
      },
      {
        number: 8,
        name: "Recursivitate",
        question: "Ce returnează `factorial(4)` cu factorial(n) = n * factorial(n-1) și factorial(1) = 1?",
        options: ["4", "8", "16", "24"],
        answer: "24",
        explanation: "factorial(4) = 4 × 3 × 2 × 1 = 24.",
        difficulty: "medium",
      },
      {
        number: 9,
        name: "Named arguments",
        question: "Ce avantaj oferă named arguments (PHP 8+) ca `saluta(salut: \"Hey\", nume: \"Ana\")`?",
        options: [
          "Funcția rulează mai repede",
          "Poți trimite argumentele în orice ordine, specificând numele lor",
          "Permite mai mulți parametri",
          "Elimină necesitatea type hints",
        ],
        answer: "Poți trimite argumentele în orice ordine, specificând numele lor",
        explanation: "Named arguments îți permit să omiti parametrii opționali din mijloc și să trimiți argumentele în orice ordine.",
        difficulty: "medium",
      },
      {
        number: 10,
        name: "void return type",
        question: "Ce semnifică tipul de return `:void` la o funcție PHP?",
        options: [
          "Funcția returnează null",
          "Funcția returnează 0",
          "Funcția nu returnează nicio valoare — return cu valoare aruncă eroare",
          "Funcția poate returna orice tip",
        ],
        answer: "Funcția nu returnează nicio valoare — return cu valoare aruncă eroare",
        explanation: "void înseamnă că funcția nu returnează nimic. Poți scrie return; (fără valoare) dar return $x; aruncă TypeError.",
        difficulty: "medium",
      },
    ],
  },
  {
    slug: "php-arrays",
    title: "6. Arrays",
    order: 6,
    theory: [
      {
        order: 1,
        title: "Arrays în PHP — indexate și asociative",
        content: "Un array PHP e ca un **sertar cu compartimente**. Fiecare compartiment are un număr (array indexat) sau o etichetă (array asociativ).\n\n```php\n<?php\n// Array indexat — compartimente numerice (0, 1, 2...):\n$culori = [\"roșu\", \"verde\", \"albastru\"];\necho $culori[0];  // roșu\necho $culori[2];  // albastru\n\n// Array asociativ — compartimente cu etichete:\n$user = [\n    \"id\"    => 42,\n    \"nume\"  => \"Ana Popescu\",\n    \"email\" => \"ana@exemplu.ro\",\n    \"rol\"   => \"admin\",\n];\necho $user[\"nume\"];   // Ana Popescu\necho $user[\"email\"];  // ana@exemplu.ro\n\n// Adăugare elemente:\n$culori[] = \"galben\";           // adaugă cu index auto (devine index 3)\n$user[\"varsta\"] = 28;           // adaugă cheie nouă\n$culori[10] = \"portocaliu\";     // index specific (hole array!)\n\n// Verificare cheie:\nif (isset($user[\"email\"])) echo \"Are email\";\nif (array_key_exists(\"rol\", $user)) echo \"Are rol\";\n```\n\n**Array-urile PHP sunt ORDONATE** — ordinea de inserare e garantată (spre deosebire de hash maps din alte limbaje).\n\n**Funcții de bază:**\n```php\n<?php\n$a = [3, 1, 4, 1, 5, 9, 2, 6];\n\ncount($a);              // 8 — câte elemente\nin_array(5, $a);        // true — există valoarea?\nin_array(5, $a, true);  // al 3-lea param = strict (===)\narray_search(4, $a);    // 2 — indexul primei apariții a lui 4\narray_key_exists(0, $a); // true\n```",
      },
      {
        order: 2,
        title: "Modificare, sortare, slicing",
        content: "```php\n<?php\n$a = [3, 1, 4, 1, 5];\n\n// Adăugare:\narray_push($a, 9, 2);   // adaugă la final: [3,1,4,1,5,9,2]\n$a[] = 6;               // echivalent, mai rapid\narray_unshift($a, 0);   // adaugă la început: [0,3,1,4,1,5,9,2,6]\n\n// Eliminare:\n$ultim  = array_pop($a);    // elimină și returnează ultimul\n$primul = array_shift($a);  // elimină și returnează primul\nunset($a[2]);               // elimină elementul de la index 2 (hole!)\n$a = array_values($a);      // reindexează după unset\n\n// Sortare (modifică array-ul in-place):\nsort($a);   // crescător — reindexează\nrsort($a);  // descrescător — reindexează\nasort($a);  // crescător — PĂSTREAZĂ cheile (arrays asociative)\nksort($a);  // sortează după chei\n\n// Personalizată:\nusort($a, fn($x, $y) => $x <=> $y);   // cu callback\n\n// Extragere porțiuni:\n$slice = array_slice($a, 1, 3);   // de la index 1, 3 elemente\n\n// Transformare:\n$unice  = array_unique([1, 2, 2, 3, 3, 3]);  // [1, 2, 3]\n$rev    = array_reverse([1, 2, 3, 4]);        // [4, 3, 2, 1]\n$merged = array_merge([1, 2], [3, 4]);        // [1, 2, 3, 4]\n$flat   = array_merge(...[[1,2],[3,4],[5,6]]); // [1,2,3,4,5,6]\n```",
      },
      {
        order: 3,
        title: "array_map, array_filter, array_reduce — programare funcțională",
        content: "Aceste trei funcții reprezintă o abordare **funcțională** a manipulării arrays — mai clară, mai testabilă decât buclele manuale:\n\n```php\n<?php\n$numere = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];\n\n// array_map — transformă fiecare element:\n$patrate  = array_map(fn($n) => $n ** 2, $numere);\n// [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]\n\n$cu_tva   = array_map(fn($p) => round($p * 1.19, 2), [100, 200, 300]);\n// [119.0, 238.0, 357.0]\n\n// array_filter — păstrează elementele care trec filtrul:\n$pare     = array_filter($numere, fn($n) => $n % 2 === 0);\n// [2, 4, 6, 8, 10] — ATENȚIE: păstrează cheile originale!\n$pare     = array_values($pare);  // reindexează: [2, 4, 6, 8, 10]\n\n$activi   = array_filter($users, fn($u) => $u[\"activ\"] === true);\n\n// array_reduce — combină toate elementele în una:\n$suma     = array_reduce($numere, fn($acc, $n) => $acc + $n, 0);\n// 55\n\n$produs   = array_reduce($numere, fn($acc, $n) => $acc * $n, 1);\n// 3628800 = 10!\n\n$max      = array_reduce($numere, fn($acc, $n) => max($acc, $n), PHP_INT_MIN);\n// 10\n```\n\n**array_column** — extrage o coloană din array multidimensional:\n```php\n<?php\n$users = [\n    [\"id\" => 1, \"nume\" => \"Ana\",   \"email\" => \"ana@test.com\"],\n    [\"id\" => 2, \"nume\" => \"Ion\",   \"email\" => \"ion@test.com\"],\n    [\"id\" => 3, \"nume\" => \"Maria\", \"email\" => \"maria@test.com\"],\n];\n\n$emailuri = array_column($users, \"email\");\n// [\"ana@test.com\", \"ion@test.com\", \"maria@test.com\"]\n\n// Indexat după id (hash map rapid!):\n$byId = array_column($users, null, \"id\");\n// [1 => [\"id\"=>1,...], 2 => [\"id\"=>2,...], 3 => [\"id\"=>3,...]]\n\n// Lookup O(1) în loc de loop:\n$user = $byId[2];  // direct, fără foreach!\n```",
      },
      {
        order: 4,
        title: "Arrays multidimensionale și spread operator",
        content: "**Arrays multidimensionale** — arrays care conțin alte arrays. Uzual pentru tabele de date:\n\n```php\n<?php\n$produse = [\n    [\"id\" => 1, \"categorie\" => \"IT\",  \"nume\" => \"Laptop\",  \"pret\" => 3000, \"stoc\" => 5],\n    [\"id\" => 2, \"categorie\" => \"IT\",  \"nume\" => \"Mouse\",   \"pret\" => 80,   \"stoc\" => 50],\n    [\"id\" => 3, \"categorie\" => \"MBL\", \"nume\" => \"Monitor\", \"pret\" => 1500, \"stoc\" => 12],\n    [\"id\" => 4, \"categorie\" => \"IT\",  \"nume\" => \"Tastatura\",\"pret\" => 200, \"stoc\" => 30],\n];\n\n// Filtrare — produse din IT sub 500 RON:\n$ieftine_it = array_filter(\n    $produse,\n    fn($p) => $p[\"categorie\"] === \"IT\" && $p[\"pret\"] < 500\n);\n\n// Transformare — extrage doar id și pret:\n$pret_list = array_map(\n    fn($p) => [\"id\" => $p[\"id\"], \"pret\" => $p[\"pret\"]],\n    $produse\n);\n\n// Sortare după preț descrescător:\nusort($produse, fn($a, $b) => $b[\"pret\"] <=> $a[\"pret\"]);\n\n// Grupare după categorie:\n$grupe = [];\nforeach ($produse as $p) {\n    $grupe[$p[\"categorie\"]][] = $p;\n}\n```\n\n**Spread operator** — despachetează arrays:\n```php\n<?php\n$a = [1, 2, 3];\n$b = [4, 5, 6];\n\n$combinat = [...$a, ...$b];       // [1, 2, 3, 4, 5, 6]\n$cu_extra = [0, ...$a, ...$b, 7]; // [0, 1, 2, 3, 4, 5, 6, 7]\n\n// Cu asociative (PHP 8.1+):\n$defaults = [\"culoare\" => \"roșu\", \"marime\" => \"M\", \"stoc\" => 0];\n$produs   = [\"stoc\" => 15, \"pret\" => 99];  // suprascrie stoc\n$final    = [...$defaults, ...$produs];\n// [\"culoare\" => \"roșu\", \"marime\" => \"M\", \"stoc\" => 15, \"pret\" => 99]\n```",
      },
    ],
    tasks: [
      {
        number: 1,
        name: "Index array",
        question: "Care e valoarea `$arr[1]` dacă `$arr = [\"a\", \"b\", \"c\"]`?",
        options: ["a", "b", "c", "Eroare"],
        answer: "b",
        explanation: "Arrays indexate pornesc de la 0. Deci: $arr[0]=\"a\", $arr[1]=\"b\", $arr[2]=\"c\".",
        difficulty: "easy",
      },
      {
        number: 2,
        name: "count",
        question: "Ce returnează `count([1, 2, 3, 4, 5])`?",
        options: ["4", "5", "6", "0"],
        answer: "5",
        explanation: "count() returnează numărul de elemente. Array-ul are 5 elemente.",
        difficulty: "easy",
      },
      {
        number: 3,
        name: "array_push vs []",
        question: "Care e diferența dintre `array_push($a, $v)` și `$a[] = $v`?",
        options: [
          "array_push e mai rapid",
          "Sunt funcțional identice — $a[] = $v e mai scurt și ușor mai rapid",
          "$a[] = $v adaugă la început",
          "array_push nu funcționează cu string-uri",
        ],
        answer: "Sunt funcțional identice — $a[] = $v e mai scurt și ușor mai rapid",
        explanation: "$a[] = $v e preferabil — mai concis și evită overhead-ul apelului de funcție.",
        difficulty: "medium",
      },
      {
        number: 4,
        name: "array_map",
        question: "Ce returnează `array_map(fn($n) => $n * 2, [1, 2, 3])`?",
        options: [
          "Filtrează elementele pare",
          "[2, 4, 6]",
          "Suma: 12",
          "Sortează array-ul",
        ],
        answer: "[2, 4, 6]",
        explanation: "array_map aplică funcția pe fiecare element: 1×2=2, 2×2=4, 3×2=6.",
        difficulty: "medium",
      },
      {
        number: 5,
        name: "array_filter chei",
        question: "Ce face `array_filter` cu cheile elementelor rămase?",
        options: [
          "Le reindexează de la 0",
          "Păstrează cheile originale — trebuie array_values() dacă vrei reindexare",
          "Le convertește la string",
          "Aruncă eroare",
        ],
        answer: "Păstrează cheile originale — trebuie array_values() dacă vrei reindexare",
        explanation: "array_filter păstrează cheile. Dacă filtrez [0=>1, 1=>2, 2=>3] și rămâne [1,3], cheile sunt [0, 2].",
        difficulty: "medium",
      },
      {
        number: 6,
        name: "array_column",
        question: "Ce returnează `array_column($users, \"email\")` pentru un array de useri?",
        options: [
          "Primul email",
          "Un array cu toate câmpurile email",
          "Numărul de useri cu email",
          "Eroare dacă lipsesc emailuri",
        ],
        answer: "Un array cu toate câmpurile email",
        explanation: "array_column extrage un câmp specific din fiecare element. E echivalentul SQL: SELECT email FROM users.",
        difficulty: "medium",
      },
      {
        number: 7,
        name: "array_reduce",
        question: "Ce returnează `array_reduce([1,2,3,4], fn($acc, $n) => $acc + $n, 0)`?",
        options: ["10", "24", "0", "4"],
        answer: "10",
        explanation: "array_reduce acumulează: 0+1=1, 1+2=3, 3+3=6, 6+4=10.",
        difficulty: "medium",
      },
      {
        number: 8,
        name: "array_unique",
        question: "Ce returnează `array_unique([1, 2, 2, 3, 1, 4])`?",
        options: ["[1, 2, 3, 4]", "[1, 2, 3, 4] cu cheile originale", "[2, 1]", "Eroare"],
        answer: "[1, 2, 3, 4] cu cheile originale",
        explanation: "array_unique elimină duplicatele și PĂSTREAZĂ cheile originale. Cheile rezultat: 0, 1, 3, 5.",
        difficulty: "medium",
      },
      {
        number: 9,
        name: "usort",
        question: "Cum sortezi un array de produse după preț crescător cu usort?",
        options: [
          "usort($p, fn($a, $b) => $a[\"pret\"] - $b[\"pret\"]);",
          "usort($p, fn($a, $b) => $a[\"pret\"] <=> $b[\"pret\"]);",
          "sort($p[\"pret\"]);",
          "array_sort($p, \"pret\");",
        ],
        answer: "usort($p, fn($a, $b) => $a[\"pret\"] <=> $b[\"pret\"]);",
        explanation: "usort cu spaceship <=> e idiomul corect. Returnează -1/0/1 — exact ce usort necesită.",
        difficulty: "medium",
      },
      {
        number: 10,
        name: "Spread array",
        question: "Ce conține `$c` după `$a = [1,2]; $b = [3,4]; $c = [...$a, ...$b];`?",
        options: ["[[1,2],[3,4]]", "[1, 2, 3, 4]", "[1, 2]", "Eroare"],
        answer: "[1, 2, 3, 4]",
        explanation: "Spread operator ... despachetează arrays. Rezultatul e un array unificat [1, 2, 3, 4].",
        difficulty: "medium",
      },
    ],
  },
  {
    slug: "php-string-functions",
    title: "7. Funcții pentru șiruri de caractere",
    order: 7,
    theory: [
      {
        order: 1,
        title: "Operații fundamentale pe stringuri",
        content: "PHP are peste 100 de funcții built-in pentru stringuri. Vei folosi aceleași 20 în 90% din cazuri:\n\n**Dimensiune și curățare:**\n```php\n<?php\n$s = \"  Salut, Lume!  \";\n\necho strlen($s);         // 17 (cu spații)\necho strlen(trim($s));   // 13 (fără spații)\n\ntrim($s);            // elimină spații din AMBELE capete\nltrim($s);           // Left trim — doar stânga\nrtrim($s);           // Right trim — doar dreapta\ntrim($s, \"!\");       // elimină ! din capete (nu spații!)\ntrim($s, \" !,.\");    // elimină oricare din aceste caractere\n```\n\n**Transformare case:**\n```php\n<?php\nstrtolower(\"SALUT PHP\");    // \"salut php\"\nstrtoupper(\"salut php\");    // \"SALUT PHP\"\nucfirst(\"ana popescu\");      // \"Ana popescu\" — prima literă\nucwords(\"ana maria popescu\"); // \"Ana Maria Popescu\" — fiecare cuvânt\n\n// Verificare conținut:\nctype_alpha(\"Salut\");    // true — doar litere\nctype_digit(\"12345\");    // true — doar cifre\nctype_alnum(\"abc123\");   // true — litere + cifre\n```\n\n**Interpolarea variabilelor în string-uri cu \"\":**\n```php\n<?php\n$nume = \"Ana\";\n$varsta = 25;\n\n// Interpolat — mai clar:\necho \"Bună, $nume! Ai $varsta de ani.\";\n// vs concatenat:\necho \"Bună, \" . $nume . \"! Ai \" . $varsta . \" de ani.\";\n\n// Expresii complexe cu {}:\n$arr = [\"nr\" => 42];\necho \"Numărul este: {$arr['nr']}\";  // 42\n\n// Heredoc — string multi-linie:\n$html = <<<HTML\n<div class=\"user\">\n    <h2>$nume</h2>\n    <p>Vârsta: $varsta</p>\n</div>\nHTML;\n```",
      },
      {
        order: 2,
        title: "Căutare, înlocuire și poziționare",
        content: "```php\n<?php\n$text = \"PHP este un limbaj PHP popular pentru web PHP.\";\n\n// Găsire poziție:\n$pos = strpos($text, \"PHP\");    // 0 — prima apariție\n$pos = strrpos($text, \"PHP\");   // 38 — ultima apariție\n$cnt = substr_count($text, \"PHP\");  // 3 — câte apariții\n\n// ATENȚIE CRITICĂ la strpos:\nif (strpos($text, \"PHP\") === false) {  // CORECT cu ===\n    echo \"Nu găsit\";\n} else {\n    echo \"Găsit!\";\n}\n// GREȘIT: if (strpos($text, \"PHP\") == false)\n// Dacă e la poziția 0, strpos returnează 0\n// și 0 == false este true → fals negative!\n\n// Verificare modernă (PHP 8+):\nstr_contains($text, \"PHP\");         // true\nstr_starts_with($text, \"PHP\");      // true\nstr_ends_with($text, \"PHP.\");       // true\n\n// Înlocuire:\n$nou = str_replace(\"PHP\", \"Python\", $text);\n$nou = str_ireplace(\"php\", \"Go\", $text);   // case-insensitive\n\n// Numărul de înlocuiri (al 4-lea param):\n$count = 0;\nstr_replace(\"PHP\", \"Go\", $text, $count);\necho $count;  // 3\n\n// Înlocuire multiplă:\n$nou = str_replace(\n    [\"PHP\", \"limbaj\", \"web\"],\n    [\"Python\", \"language\", \"internet\"],\n    $text\n);\n```",
      },
      {
        order: 3,
        title: "Extragere, împărțire și unire",
        content: "```php\n<?php\n// substr — extrage o porțiune:\n$s = \"Hello, World!\";\nsubstr($s, 7);       // \"World!\" — de la index 7\nsubstr($s, 0, 5);    // \"Hello\" — primele 5 caractere\nsubstr($s, -6);      // \"orld!\" — ultimele 6 caractere  \nsubstr($s, 7, 5);    // \"World\" — 5 caractere de la index 7\n\n// explode — split după separator:\n$csv = \"Ana,Ion,Maria,Elena\";\n$names = explode(\",\", $csv);\n// [\"Ana\", \"Ion\", \"Maria\", \"Elena\"]\n\n// Cu limită:\n$email = \"user.name@sub.example.com\";\n[$utilizator, $domeniu] = explode(\"@\", $email, 2);\necho $utilizator;  // user.name\necho $domeniu;     // sub.example.com\n\n// Parsare URL:\n$parts = parse_url(\"https://api.example.com/v1/users?id=5\");\necho $parts[\"host\"];   // api.example.com\necho $parts[\"path\"];   // /v1/users\necho $parts[\"query\"];  // id=5\n\n// implode — unire cu separator:\necho implode(\", \", [\"Ana\", \"Ion\", \"Maria\"]);\n// Ana, Ion, Maria\n\necho implode(\" | \", array_column($produse, \"nume\"));\n// Laptop | Mouse | Monitor\n\n// str_split — împarte în caractere sau chunk-uri:\n$chars = str_split(\"Salut\");     // [\"S\",\"a\",\"l\",\"u\",\"t\"]\n$chunks = str_split(\"Salut\", 2);  // [\"Sa\",\"lu\",\"t\"]\n```",
      },
      {
        order: 4,
        title: "Formatare, hashing și securitate XSS",
        content: "```php\n<?php\n// sprintf — formatare avansată:\n$pret    = sprintf(\"%.2f RON\", 9.9);   // \"9.90 RON\"\n$padded  = sprintf(\"%05d\", 42);        // \"00042\" — 5 caractere\n$hex     = sprintf(\"%x\", 255);         // \"ff\" — hexazecimal\n$percent = sprintf(\"%.1f%%\", 66.667);  // \"66.7%\"\n\n// number_format — numere cu separator mii:\necho number_format(1234567.891, 2, \".\", \",\");\n// 1,234,567.89\n\n// Padding:\necho str_pad(\"42\", 5, \"0\", STR_PAD_LEFT);    // \"00042\"\necho str_pad(\"Test\", 12, \"-\", STR_PAD_BOTH); // \"----Test----\"\n\n// Repetare și inversare:\necho str_repeat(\"=-\", 5);     // =-=-=-=-=-=-\necho strrev(\"Hello\");          // olleH\n```\n\n**Hashing și securitate — ESENȚIAL la interviu:**\n```php\n<?php\n// MD5 și SHA1 — NU pentru parole!\necho md5(\"parola123\");   // hash 32 hex — se poate sparge cu rainbow tables!\necho sha1(\"parola123\");  // hash 40 hex — la fel de nesigur\n\n// CORECT: password_hash() cu bcrypt/argon2:\n$hash = password_hash(\"parola123\", PASSWORD_BCRYPT);\n// $2y$10$... — bcrypt cu salt aleator, greu de spart\n\n$ok = password_verify(\"parola123\", $hash);  // true\n$ok = password_verify(\"altaParola\", $hash); // false\n\n// XSS Prevention — OBLIGATORIU la output:\n$input = \"<script>document.cookie</script>\";\necho htmlspecialchars($input, ENT_QUOTES, \"UTF-8\");\n// &lt;script&gt;document.cookie&lt;/script&gt;\n// Browser-ul afișează textul, nu execută scriptul!\n\n// Niciodată:\necho $_POST[\"comentariu\"];  // XSS!\n// Mereu:\necho htmlspecialchars($_POST[\"comentariu\"], ENT_QUOTES, \"UTF-8\");\n```",
      },
    ],
    tasks: [
      {
        number: 1,
        name: "strlen",
        question: "Ce returnează `strlen(\"PHP\")`?",
        options: ["2", "3", "4", "0"],
        answer: "3",
        explanation: "strlen() numără caracterele din string. \"PHP\" are 3 caractere: P, H, P.",
        difficulty: "easy",
      },
      {
        number: 2,
        name: "strtoupper",
        question: "Ce afișează `echo strtoupper(\"php 8\");`?",
        options: ["Php 8", "PHP 8", "php 8", "PHP8"],
        answer: "PHP 8",
        explanation: "strtoupper() convertește toate literele la majuscule. Cifrele și spațiile rămân neschimbate.",
        difficulty: "easy",
      },
      {
        number: 3,
        name: "strpos strict",
        question: "De ce trebuie să compari rezultatul strpos cu `===` și nu cu `==`?",
        options: [
          "Performanță mai bună",
          "strpos returnează 0 pentru match la poziția 0, iar 0 == false este true — fals negative!",
          "strpos returnează string, nu int",
          "Nu e nevoie, == funcționează la fel",
        ],
        answer: "strpos returnează 0 pentru match la poziția 0, iar 0 == false este true — fals negative!",
        explanation: "Dacă pattern e chiar la poziția 0, strpos returnează 0. Cu ==, 0 == false este true și spui că nu l-ai găsit.",
        difficulty: "medium",
      },
      {
        number: 4,
        name: "str_contains",
        question: "Ce returnează `str_contains(\"Bună ziua\", \"ziua\")` în PHP 8?",
        options: ["0", "1", "true", "Eroare — funcția nu există"],
        answer: "true",
        explanation: "str_contains() a fost adăugat în PHP 8. Returnează bool true dacă substring există în string.",
        difficulty: "easy",
      },
      {
        number: 5,
        name: "explode",
        question: "Ce returnează `explode(\",\", \"a,b,c\")`?",
        options: ["\"abc\"", "[\"a,b,c\"]", "[\"a\", \"b\", \"c\"]", "Eroare"],
        answer: "[\"a\", \"b\", \"c\"]",
        explanation: "explode() împarte un string după separator și returnează un array.",
        difficulty: "easy",
      },
      {
        number: 6,
        name: "implode",
        question: "Ce afișează `echo implode(\"-\", [\"a\", \"b\", \"c\"]);`?",
        options: ["a,b,c", "abc", "a-b-c", "[a-b-c]"],
        answer: "a-b-c",
        explanation: "implode() unește elementele array-ului cu separatorul dat ca primul argument.",
        difficulty: "easy",
      },
      {
        number: 7,
        name: "substr negativ",
        question: "Ce returnează `substr(\"Laravel\", -3)`?",
        options: ["Lar", "vel", "avel", "Eroare"],
        answer: "vel",
        explanation: "Index negativ la substr numără de la coadă. -3 = ultimele 3 caractere din \"Laravel\" = \"vel\".",
        difficulty: "medium",
      },
      {
        number: 8,
        name: "htmlspecialchars",
        question: "De ce trebuie să folosești `htmlspecialchars()` înainte de a afișa date de la utilizator?",
        options: [
          "Pentru a face textul mai scurt",
          "Pentru a preveni XSS — escaparea caracterelor HTML periculoase",
          "Pentru a converti la UTF-8",
          "Pentru a elimina spațiile",
        ],
        answer: "Pentru a preveni XSS — escaparea caracterelor HTML periculoase",
        explanation: "htmlspecialchars() convertește <, >, &, ', \" în entități HTML. Previne injectarea de <script> tags în pagină.",
        difficulty: "medium",
      },
      {
        number: 9,
        name: "sprintf formatare",
        question: "Ce returnează `sprintf(\"%.2f\", 3.1)`?",
        options: ["3", "3.1", "3.10", "3.100"],
        answer: "3.10",
        explanation: "%.2f formatează float cu exact 2 zecimale. 3.1 are o zecimală, sprintf adaugă 0 → 3.10.",
        difficulty: "medium",
      },
      {
        number: 10,
        name: "password_hash vs md5",
        question: "La interviu: de ce NU trebuie să folosești md5() pentru a stoca parole în baza de date?",
        options: [
          "md5() e prea lent",
          "md5() produce hash prea lung",
          "md5() e rapid și vulnerabil la rainbow tables — folosește password_hash()",
          "md5() nu funcționează în PHP 8",
        ],
        answer: "md5() e rapid și vulnerabil la rainbow tables — folosește password_hash()",
        explanation: "MD5 e rapid (deci ușor de brute-forced), nu folosește salt și există rainbow tables precalculate. password_hash() cu bcrypt e corect: lent, salt automat, one-way.",
        difficulty: "hard",
      },
    ],
  },
  {
    slug: "php-formulare-get-post",
    title: "8. Formulare GET și POST",
    order: 8,
    theory: [
      {
        order: 1,
        title: "GET vs POST — diferențe pe care trebuie să le știi la interviu",
        content: "GET și POST sunt cele două metode HTTP fundamentale pentru trimiterea datelor. La ORICE interviu de backend vei fi întrebat despre ele:\n\n```\nCriteriu        | GET                          | POST\n----------------|------------------------------|-----------------------------\nDate în         | URL: ?id=5&page=2            | Body-ul cererii (ascuns)\nVizibilitate    | Vizibil în URL, browser hist | Ascuns de utilizator\nLungime max     | ~2000 caractere              | Practic nelimitată\nCacheable       | DA — browserul poate cachea  | NU\nIdempotent      | DA — același rezultat repetat| NU neapărat\nBookmarkable    | DA                           | NU\nUzul tipic      | Căutare, filtrare, paginare  | Login, înregistrare, upload\n```\n\n```php\n<?php\n// Accesare date GET (din URL ?id=5&activ=1):\n$id     = $_GET[\"id\"] ?? null;\n$pagina = (int)($_GET[\"pagina\"] ?? 1);\n\n// Accesare date POST (din formular):\n$email  = $_POST[\"email\"] ?? \"\";\n$parola = $_POST[\"parola\"] ?? \"\";\n\n// Detectare metodă — pattern standard:\nif ($_SERVER[\"REQUEST_METHOD\"] === \"POST\") {\n    // procesează formularul\n} else {\n    // afișează formularul\n}\n\n// Informații utile din $_SERVER:\necho $_SERVER[\"REQUEST_METHOD\"];  // GET sau POST\necho $_SERVER[\"REQUEST_URI\"];     // /pagina.php?id=5\necho $_SERVER[\"HTTP_HOST\"];       // example.com\necho $_SERVER[\"REMOTE_ADDR\"];     // IP utilizator\n```",
      },
      {
        order: 2,
        title: "Formulare HTML + procesare PHP complet",
        content: "Fluxul complet: formular HTML → trimite date → PHP procesează → redirect sau răspuns:\n\n```html\n<!-- formular.html -->\n<form method=\"POST\" action=\"/proceseaza.php\" enctype=\"multipart/form-data\">\n    <input type=\"text\"     name=\"nume\"     required>\n    <input type=\"email\"    name=\"email\"    required>\n    <input type=\"password\" name=\"parola\"   required>\n    <input type=\"file\"     name=\"avatar\">\n    <button type=\"submit\">Înregistrare</button>\n</form>\n```\n\n```php\n<?php\n// proceseaza.php\nif ($_SERVER[\"REQUEST_METHOD\"] !== \"POST\") {\n    header(\"Location: /formular.html\");\n    exit;\n}\n\n// 1. Extrage și curăță datele:\n$nume  = trim($_POST[\"nume\"]  ?? \"\");\n$email = trim($_POST[\"email\"] ?? \"\");\n\n// 2. Validează:\n$erori = [];\nif (strlen($nume) < 2) {\n    $erori[] = \"Numele trebuie să aibă minim 2 caractere\";\n}\nif (!filter_var($email, FILTER_VALIDATE_EMAIL)) {\n    $erori[] = \"Email invalid\";\n}\n\n// 3. Dacă sunt erori, înapoi la formular:\nif (!empty($erori)) {\n    // afișează erorile\n    die(implode(\"<br>\", array_map(\"htmlspecialchars\", $erori)));\n}\n\n// 4. Procesează (salvează în DB, trimite email, etc.):\n// ...\n\n// 5. Redirect după succes (PRG pattern — Post/Redirect/Get):\nheader(\"Location: /succes.php\");\nexit;  // ESENȚIAL după header redirect!\n```",
      },
      {
        order: 3,
        title: "Validare și sanitizare — securitate obligatorie",
        content: "**Regula de aur: Nu ai NICIODATĂ încredere în datele de la utilizator!**\n\nFiecare câmp trebuie validat (formatul e corect?) și sanitizat (e sigur de folosit?):\n\n```php\n<?php\n// filter_var — validare și sanitizare built-in:\n\n// VALIDARE — returnează valoarea sau false:\nfilter_var($email, FILTER_VALIDATE_EMAIL);\nfilter_var($url,   FILTER_VALIDATE_URL);\nfilter_var($ip,    FILTER_VALIDATE_IP);\nfilter_var($int,   FILTER_VALIDATE_INT);\nfilter_var($varsta, FILTER_VALIDATE_INT, [\n    \"options\" => [\"min_range\" => 18, \"max_range\" => 120]\n]);\n\n// SANITIZARE — curăță și returnează:\nfilter_var($email, FILTER_SANITIZE_EMAIL);    // elimină caractere ilegale\nfilter_var($url,   FILTER_SANITIZE_URL);\nstrip_tags($html);                             // elimină taguri HTML\nhtmlspecialchars($text, ENT_QUOTES, \"UTF-8\"); // escapează HTML\n\n// Regex custom pentru validări speciale:\nif (!preg_match('/^[a-zA-Z ]{2,50}$/', $nume)) {\n    $erori[] = \"Numele conține caractere invalide\";\n}\nif (!preg_match('/^[0-9]{10}$/', $telefon)) {\n    $erori[] = \"Telefonul trebuie să aibă 10 cifre\";\n}\n```\n\n**SQL Injection — atacul cel mai periculos:**\n```php\n<?php\n// PERICULOS — permite SQL injection!\n$id  = $_GET[\"id\"];  // dacă id = \"1 OR 1=1 --\"\n$sql = \"SELECT * FROM users WHERE id = $id\";\n// Devine: SELECT * FROM users WHERE id = 1 OR 1=1 --\n// Returnează TOȚI userii din baza de date!\n\n// CORECT — Prepared Statements:\n$stmt = $pdo->prepare(\"SELECT * FROM users WHERE id = ?\");\n$stmt->execute([$_GET[\"id\"]]);\n$user = $stmt->fetch();\n```",
      },
      {
        order: 4,
        title: "Sesiuni, cookies și redirect corect",
        content: "**Sesiuni** — păstrezi date între cereri HTTP (HTTP e stateless):\n```php\n<?php\n// session_start() TREBUIE să fie înainte de orice output!\nsession_start();\n\n// Autentificare:\nif ($parola_corecta) {\n    $_SESSION[\"user_id\"] = $user[\"id\"];\n    $_SESSION[\"rol\"]     = $user[\"rol\"];\n    $_SESSION[\"login_time\"] = time();\n}\n\n// Pe orice altă pagină:\nsession_start();\nif (!isset($_SESSION[\"user_id\"])) {\n    header(\"Location: /login.php\");\n    exit;  // ESENȚIAL!\n}\necho \"Bun venit, user \" . $_SESSION[\"user_id\"];\n\n// Logout CORECT:\nsession_start();\n$_SESSION = [];              // golește datele sesiunii\nsession_destroy();           // distruge sesiunea pe server\n// Opțional — șterge cookie-ul de sesiune:\nsetcookie(session_name(), \"\", time() - 3600);\nheader(\"Location: /login.php\");\nexit;\n```\n\n**Cookies:**\n```php\n<?php\n// setcookie TREBUIE înainte de orice output!\nsetcookie(\n    \"tema\",         // nume\n    \"dark\",         // valoare\n    time() + 86400 * 30,  // expiră în 30 zile (86400 = 1 zi în secunde)\n    \"/\",            // path — disponibil pe tot site-ul\n    \"\",             // domain\n    true,           // secure — doar HTTPS\n    true            // httpOnly — nu accesibil din JavaScript!\n);\n\n// Citire:\n$tema = $_COOKIE[\"tema\"] ?? \"light\";\n```\n\n**PRG Pattern (Post/Redirect/Get)** — pattern standard anti-duplicate:\n```\nUtilizator → POST /formular → procesare → Redirect 302 → GET /succes\n\nFără PRG: refresh pagina → re-trimite formularul → comandă dublată!\nCu PRG: refresh la /succes → safe GET, nu re-trimite POST\n```",
      },
    ],
    tasks: [
      {
        number: 1,
        name: "GET vs POST",
        question: "Care metodă HTTP este potrivită pentru un formular de login (username + parolă)?",
        options: [
          "GET — e mai rapid",
          "POST — datele nu apar în URL și nu sunt loggate de server",
          "PUT — e pentru update",
          "DELETE",
        ],
        answer: "POST — datele nu apar în URL și nu sunt loggate de server",
        explanation: "POST ascunde datele sensibile în body. Cu GET, parola ar apărea în URL, browser history și server logs.",
        difficulty: "easy",
      },
      {
        number: 2,
        name: "REQUEST_METHOD",
        question: "Cum verifici că o cerere PHP este de tip POST?",
        options: [
          "if (POST) { }",
          "if ($_POST) { }",
          "if ($_SERVER[\"REQUEST_METHOD\"] === \"POST\") { }",
          "if (method() === \"POST\") { }",
        ],
        answer: "if ($_SERVER[\"REQUEST_METHOD\"] === \"POST\") { }",
        explanation: "$_SERVER[\"REQUEST_METHOD\"] conține metoda HTTP curentă. E verificarea standard și corectă.",
        difficulty: "medium",
      },
      {
        number: 3,
        name: "filter_var email",
        question: "Ce returnează `filter_var(\"nu-e-email\", FILTER_VALIDATE_EMAIL)`?",
        options: ["true", "false", "null", "\"nu-e-email\""],
        answer: "false",
        explanation: "FILTER_VALIDATE_EMAIL returnează valoarea dacă e email valid, sau false dacă nu e. \"nu-e-email\" nu are @domain.",
        difficulty: "medium",
      },
      {
        number: 4,
        name: "session_start timing",
        question: "Când trebuie apelat `session_start()` în PHP?",
        options: [
          "La finalul fișierului",
          "Înainte de orice output HTML sau echo",
          "Nu contează ordinea",
          "Doar în fișierul index.php",
        ],
        answer: "Înainte de orice output HTML sau echo",
        explanation: "session_start() trimite un header HTTP Set-Cookie. Header-ele trebuie trimise ÎNAINTE de body. Output înainte → eroare \"Cannot modify header information\".",
        difficulty: "medium",
      },
      {
        number: 5,
        name: "exit după redirect",
        question: "De ce e esențial `exit;` după `header(\"Location: /pagina.php\")`?",
        options: [
          "Fără exit, header() nu funcționează",
          "Fără exit, PHP continuă să execute codul următor chiar și după redirect",
          "exit() salvează sesiunea",
          "Nu e necesar — PHP oprește automat",
        ],
        answer: "Fără exit, PHP continuă să execute codul următor chiar și după redirect",
        explanation: "header() trimite redirect-ul dar PHP continuă execuția. Fără exit, codul de mai jos poate rula și returnează date neașteptate.",
        difficulty: "medium",
      },
      {
        number: 6,
        name: "SQL injection",
        question: "De ce NU trebuie să scrii `$sql = \"SELECT * FROM users WHERE id = \" . $_GET['id'];`?",
        options: [
          "Sintaxă PHP greșită",
          "Permite SQL injection — atacatorul modifică query-ul cu date malițioase",
          "$_GET returnează array",
          "SELECT nu funcționează cu variabile PHP",
        ],
        answer: "Permite SQL injection — atacatorul modifică query-ul cu date malițioase",
        explanation: "Dacă id=\"1 OR 1=1 --\", query-ul returnează toți userii. Folosește prepared statements: $stmt = $pdo->prepare(\"... WHERE id = ?\"); $stmt->execute([$id]);",
        difficulty: "medium",
      },
      {
        number: 7,
        name: "XSS prevention",
        question: "Care e funcția corectă pentru a preveni XSS la afișarea datelor de la utilizator?",
        options: [
          "strip_tags($input)",
          "htmlspecialchars($input, ENT_QUOTES, \"UTF-8\")",
          "md5($input)",
          "trim($input)",
        ],
        answer: "htmlspecialchars($input, ENT_QUOTES, \"UTF-8\")",
        explanation: "htmlspecialchars() cu ENT_QUOTES escapează <, >, &, ', \" — prevenind injectarea de script-uri.",
        difficulty: "medium",
      },
      {
        number: 8,
        name: "Cookie expirat",
        question: "Ce înseamnă `time() + 86400` la setcookie()?",
        options: [
          "Cookie expiră în 86400 minute",
          "Cookie expiră în 1 zi (86400 secunde de la acum)",
          "Cookie nu expiră niciodată",
          "Cookie expiră la sessiune",
        ],
        answer: "Cookie expiră în 1 zi (86400 secunde de la acum)",
        explanation: "86400 = 24 ore × 60 minute × 60 secunde = 1 zi. time() e timestamp-ul curent.",
        difficulty: "medium",
      },
      {
        number: 9,
        name: "PRG Pattern",
        question: "Ce problemă rezolvă pattern-ul PRG (Post/Redirect/Get)?",
        options: [
          "Securitate împotriva SQL injection",
          "Previne re-trimiterea formularului la refresh după un POST",
          "Optimizare performanță",
          "Compatibilitate browser",
        ],
        answer: "Previne re-trimiterea formularului la refresh după un POST",
        explanation: "Fără PRG, refresh după POST re-trimite formularul → comandă duplicată. Cu PRG: POST → procesare → redirect GET → utilizatorul vede pagina GET sigură.",
        difficulty: "hard",
      },
      {
        number: 10,
        name: "httpOnly cookie",
        question: "Ce face flag-ul `httpOnly = true` la un cookie?",
        options: [
          "Cookie-ul funcționează doar cu HTTPS",
          "Cookie-ul nu e accesibil din JavaScript — protecție XSS",
          "Cookie-ul nu expiră niciodată",
          "Cookie-ul e disponibil doar pe pagina curentă",
        ],
        answer: "Cookie-ul nu e accesibil din JavaScript — protecție XSS",
        explanation: "httpOnly ascunde cookie-ul de document.cookie în JavaScript. Chiar dacă atacatorul injectează JS, nu poate fura cookie-ul de sesiune.",
        difficulty: "hard",
      },
    ],
  },
];

module.exports = { phpLessons };
