const sqlLessons = [
  {
    slug: "sql-introducere-select",
    title: "1. Introducere SQL + SELECT",
    order: 1,
    theory: [
      {
        order: 1,
        title: "Ce este SQL și de ce e obligatoriu pentru orice developer",
        content: "**SQL** (Structured Query Language) e limbajul cu care comunici cu bazele de date relaționale. E ca o limbă universală — dacă știi SQL, poți lucra cu MySQL, PostgreSQL, SQLite, SQL Server, Oracle fără a schimba aproape nimic.\n\nGândește-ți aplicația ca un **restaurant**:\n• **Baza de date** = depozitul cu ingrediente și rețete\n• **Tabelele** = rafturile (clienți, comenzi, produse)\n• **SQL** = comenzile pe care le dai chelnerului (cauta, adaugă, actualizează, șterge)\n\n**Unde e folosit SQL în practică:**\n```\nMySQL       → WordPress, Laravel, e-commerce (cel mai popular)\nPostgreSQL  → Heroku, startup-uri moderne, date complexe\nSQLite      → Aplicații mobile, browser-e, fișiere locale\nSQL Server  → Ecosistem Microsoft, .NET\nOracle      → Banking, corporații mari, sisteme enterprise\n```\n\n**La interviuri** — ORICINE în tech va fi întrebat SQL:\n• Frontend? „Scrie un query care returnează userii activi sortat după dată\"\n• Backend? „Explică diferența dintre INNER JOIN și LEFT JOIN\"\n• Data Analyst? 80% din job e SQL\n\n```sql\n-- Primul tău query:\nSELECT * FROM utilizatori;\n-- Citit: \"Selectează toate coloanele din tabela utilizatori\"\n-- * = toate coloanele, fără WHERE = toate rândurile\n```",
      },
      {
        order: 2,
        title: "Structura unei tabele și SELECT fundament",
        content: "O **tabelă** e ca un Excel: coloane (câmpuri) + rânduri (înregistrări). Fiecare rând are un ID unic (Primary Key).\n\n**Tabela `produse` — exemplu cu care lucrăm:**\n```\n┌────┬─────────────────┬────────┬─────────────┬──────┐\n│ id │ nume            │ pret   │ categorie   │ stoc │\n├────┼─────────────────┼────────┼─────────────┼──────┤\n│  1 │ Laptop Dell     │ 3500   │ electronics │   15 │\n│  2 │ Mouse Logitech  │   120  │ electronics │   50 │\n│  3 │ Birou IKEA      │   800  │ furniture   │    8 │\n│  4 │ Scaun Gaming    │  1200  │ furniture   │    3 │\n│  5 │ Monitor 27\"     │  1800  │ electronics │   12 │\n└────┴─────────────────┴────────┴─────────────┴──────┘\n```\n\n**SELECT — alege ce vrei să vezi:**\n```sql\n-- Toate coloanele (evită în producție — trafic inutil):\nSELECT * FROM produse;\n\n-- Coloane specifice (recomandat):\nSELECT id, nume, pret FROM produse;\n\n-- Alias (redenumire în rezultat):\nSELECT \n    id,\n    nume AS produs,\n    pret AS cost_ron\nFROM produse;\n\n-- Expresii și calcule:\nSELECT \n    nume,\n    pret,\n    pret * 1.19         AS pret_cu_tva,\n    pret * 0.9          AS pret_dupa_reducere,\n    ROUND(pret * 1.19, 2) AS tva_rotunjit\nFROM produse;\n```\n\n**Ordinea clauzelor SQL — trebuie memorată:**\n```sql\nSELECT   -- ce coloane\nFROM     -- din ce tabelă\nJOIN     -- combinate cu ce alte tabele\nWHERE    -- filtrat cum\nGROUP BY -- grupat după ce\nHAVING   -- grupul filtrat cum\nORDER BY -- sortat cum\nLIMIT    -- câte rânduri maximum\n```",
      },
      {
        order: 3,
        title: "WHERE — filtrarea datelor",
        content: "**WHERE** e filtrul tău — ca un portar care lasă să treacă doar ce vrei:\n\n```sql\n-- Condiție simplă:\nSELECT * FROM produse WHERE pret > 500;\n\n-- String cu ghilimele SIMPLE (obligatoriu în SQL):\nSELECT * FROM produse WHERE categorie = 'electronics';\n\n-- Multiple condiții:\nSELECT * FROM produse\nWHERE categorie = 'electronics'\n  AND pret < 200;       -- AND: ambele condiții trebuie adevărate\n\nSELECT * FROM produse\nWHERE stoc = 0\n   OR pret > 3000;      -- OR: cel puțin una adevărată\n\nSELECT * FROM produse\nWHERE NOT categorie = 'furniture';\n```\n\n**Operatori speciali:**\n```sql\n-- BETWEEN — interval incluziv (include capetele!):\nSELECT * FROM produse WHERE pret BETWEEN 100 AND 1000;\n-- Echivalent cu: pret >= 100 AND pret <= 1000\n\n-- IN — lista de valori acceptate:\nSELECT * FROM produse WHERE id IN (1, 3, 5);\nSELECT * FROM produse WHERE categorie IN ('electronics', 'furniture');\n\n-- LIKE — pattern matching cu wildcards:\nSELECT * FROM produse WHERE nume LIKE '%gaming%'; -- conține 'gaming'\nSELECT * FROM produse WHERE nume LIKE 'L%';       -- începe cu L\nSELECT * FROM produse WHERE cod LIKE 'AB___';     -- AB + exact 3 caractere\n\n-- NULL — valori lipsă (ATENȚIE: nu poți folosi = null!):\nSELECT * FROM produse WHERE descriere IS NULL;     -- corect\nSELECT * FROM produse WHERE descriere IS NOT NULL;\n-- GREȘIT: WHERE descriere = NULL (nu returnează nimic!)\n```\n\n**La interviu:** *„De ce nu funcționează WHERE col = NULL?\"* — Răspuns: NULL nu e o valoare, e absența valorii. NULL nu e egal cu nimic, nici măcar cu el însuși. Trebuie IS NULL.",
      },
      {
        order: 4,
        title: "ORDER BY, LIMIT, DISTINCT — sortare și paginare",
        content: "**ORDER BY** — sortarea rezultatelor:\n```sql\n-- Crescător (default = ASC):\nSELECT * FROM produse ORDER BY pret;       -- idem cu ASC\nSELECT * FROM produse ORDER BY pret ASC;\n\n-- Descrescător:\nSELECT * FROM produse ORDER BY pret DESC;\n\n-- Multiple coloane — sortare ierarhică:\nSELECT * FROM produse\nORDER BY categorie ASC, pret DESC;\n-- Sortează categoriile alfabetic,\n-- iar în cadrul aceleași categorii: prețul descrescător\n\n-- Sortare după alias:\nSELECT nume, pret * 1.19 AS pret_tva\nFROM produse\nORDER BY pret_tva DESC;\n```\n\n**LIMIT + OFFSET — paginare:**\n```sql\n-- Primele 10:\nSELECT * FROM produse LIMIT 10;\n\n-- Paginare (pagina 3, 10 pe pagină):\nSELECT * FROM produse\nORDER BY id\nLIMIT 10 OFFSET 20;\n-- OFFSET = sari primele 20, ia următoarele 10\n-- Formula: OFFSET = (pagina - 1) * per_pagina\n\n-- Top 3 cele mai scumpe:\nSELECT * FROM produse\nORDER BY pret DESC\nLIMIT 3;\n```\n\n**DISTINCT — valori unice:**\n```sql\n-- Lista de categorii (fără duplicate):\nSELECT DISTINCT categorie FROM produse;\n-- Fără DISTINCT ar apărea 'electronics' de 3 ori\n\n-- DISTINCT pe multiple coloane:\nSELECT DISTINCT categorie, producator FROM produse;\n```\n\n**La interviu:** Diferența dintre LIMIT și TOP? MySQL/PostgreSQL folosesc LIMIT, SQL Server folosește TOP 10, Oracle folosește ROWNUM sau FETCH FIRST 10 ROWS ONLY.",
      },
    ],
    tasks: [
      {
        number: 1,
        name: "SELECT *",
        question: "Ce returnează `SELECT * FROM produse`?",
        options: [
          "Primul rând",
          "Toate coloanele și toate rândurile din tabelă",
          "Doar coloana id",
          "Numărul de rânduri",
        ],
        answer: "Toate coloanele și toate rândurile din tabelă",
        explanation: "* = toate coloanele. Fără WHERE = toate rândurile. Evită SELECT * în producție — specifică coloanele necesare.",
        difficulty: "easy",
      },
      {
        number: 2,
        name: "SELECT coloane",
        question: "Cum selectezi doar `nume` și `pret` din tabela `produse`?",
        options: [
          "SELECT produse(nume, pret)",
          "SELECT nume, pret FROM produse",
          "GET nume, pret FROM produse",
          "SELECT FROM produse WHERE col IN (nume, pret)",
        ],
        answer: "SELECT nume, pret FROM produse",
        explanation: "Specifici coloanele după SELECT separate prin virgulă, apoi FROM tabelă.",
        difficulty: "easy",
      },
      {
        number: 3,
        name: "WHERE egal",
        question: "Cum filtrezi produsele din categoria 'electronics'?",
        options: [
          "SELECT * FROM produse IF categorie = 'electronics'",
          "SELECT * FROM produse WHERE categorie = 'electronics'",
          "SELECT * FROM produse FILTER categorie = 'electronics'",
          "FIND * FROM produse WHERE categorie IS 'electronics'",
        ],
        answer: "SELECT * FROM produse WHERE categorie = 'electronics'",
        explanation: "WHERE filtrează rândurile. String-urile în SQL se pun între ghilimele SIMPLE (nu duble).",
        difficulty: "easy",
      },
      {
        number: 4,
        name: "ORDER BY DESC",
        question: "Cum selectezi produsele sortate de la cel mai scump la cel mai ieftin?",
        options: [
          "SELECT * FROM produse ORDER BY pret",
          "SELECT * FROM produse SORT pret DESC",
          "SELECT * FROM produse ORDER BY pret DESC",
          "SELECT * FROM produse ORDER DESC pret",
        ],
        answer: "SELECT * FROM produse ORDER BY pret DESC",
        explanation: "ORDER BY coloana DESC = descrescător (de la mare la mic). ASC (default) = crescător.",
        difficulty: "easy",
      },
      {
        number: 5,
        name: "LIMIT",
        question: "Cum obții primele 10 produse?",
        options: [
          "SELECT * FROM produse TOP 10",
          "SELECT * FROM produse LIMIT 10",
          "SELECT FIRST 10 FROM produse",
          "SELECT * FROM produse WHERE count <= 10",
        ],
        answer: "SELECT * FROM produse LIMIT 10",
        explanation: "LIMIT N restricționează la N rânduri. SQL Server folosește TOP 10, Oracle FETCH FIRST 10 ROWS ONLY.",
        difficulty: "easy",
      },
      {
        number: 6,
        name: "LIKE pattern",
        question: "Ce face `WHERE nume LIKE '%gaming%'`?",
        options: [
          "Caută exact 'gaming'",
          "Caută rânduri unde nume conține 'gaming' oriunde în șir",
          "Caută rânduri care încep cu 'gaming'",
          "Returnează eroare",
        ],
        answer: "Caută rânduri unde nume conține 'gaming' oriunde în șir",
        explanation: "% = orice șir (0+ caractere). '%gaming%' = gaming oriunde. 'gaming%' = începe cu gaming. '_aming' = 1 caracter + aming.",
        difficulty: "medium",
      },
      {
        number: 7,
        name: "BETWEEN",
        question: "Ce face `WHERE pret BETWEEN 100 AND 500`?",
        options: [
          "Prețuri sub 100 sau peste 500",
          "Prețuri exact 100 sau 500",
          "Prețuri inclusiv între 100 și 500 (100 <= pret <= 500)",
          "Eroare de sintaxă",
        ],
        answer: "Prețuri inclusiv între 100 și 500 (100 <= pret <= 500)",
        explanation: "BETWEEN include AMBELE capete. Echivalent cu pret >= 100 AND pret <= 500.",
        difficulty: "medium",
      },
      {
        number: 8,
        name: "DISTINCT",
        question: "Ce face `SELECT DISTINCT categorie FROM produse`?",
        options: [
          "Selectează toate categoriile inclusiv duplicate",
          "Returnează lista unică de categorii — fără duplicate",
          "Sortează categoriile alfabetic",
          "Numără câte categorii există",
        ],
        answer: "Returnează lista unică de categorii — fără duplicate",
        explanation: "DISTINCT elimină duplicatele. Dacă sunt 50 produse în 3 categorii, DISTINCT returnează 3 rânduri.",
        difficulty: "medium",
      },
      {
        number: 9,
        name: "NULL comparare",
        question: "De ce `WHERE email = NULL` nu returnează nimic?",
        options: [
          "Sintaxă greșită",
          "NULL nu e o valoare — nu poți compara cu =. Folosește IS NULL",
          "Email nu poate fi NULL",
          "= NULL funcționează doar în MySQL",
        ],
        answer: "NULL nu e o valoare — nu poți compara cu =. Folosește IS NULL",
        explanation: "NULL reprezintă absența valorii. NULL != NULL chiar și NULL. Singurul mod corect: IS NULL sau IS NOT NULL.",
        difficulty: "medium",
      },
      {
        number: 10,
        name: "Paginare OFFSET",
        question: "Cum obții rândurile 21-30 (pagina 3, 10 pe pagină)?",
        options: [
          "SELECT * FROM t LIMIT 10 PAGE 3",
          "SELECT * FROM t LIMIT 10 OFFSET 20",
          "SELECT * FROM t LIMIT 20, 10",
          "SELECT * FROM t SKIP 20 TAKE 10",
        ],
        answer: "SELECT * FROM t LIMIT 10 OFFSET 20",
        explanation: "OFFSET 20 sare primele 20 rânduri, LIMIT 10 ia următoarele 10. Formula: OFFSET = (pagina-1) × per_pagina.",
        difficulty: "medium",
      },
    ],
  },
  {
    slug: "sql-insert-update-delete",
    title: "2. INSERT, UPDATE, DELETE și tranzacții",
    order: 2,
    theory: [
      {
        order: 1,
        title: "INSERT — adaugă date noi",
        content: "**INSERT** adaugă rânduri noi într-o tabelă. E ca un formular de înregistrare — completezi câmpurile și salvezi.\n\n```sql\n-- INSERT clasic — specifici coloanele și valorile:\nINSERT INTO produse (nume, pret, categorie, stoc)\nVALUES ('Tastatura Mecanica', 350, 'electronics', 25);\n\n-- Fără a specifica coloanele — PERICULOASĂ:\n-- trebuie să pui TOATE valorile în ordinea exactă a coloanelor:\nINSERT INTO produse\nVALUES (NULL, 'Tastatura Mecanica', 350, 'electronics', 25);\n-- NULL = generează ID automat (AUTO_INCREMENT)\n\n-- INSERT multiple rânduri simultan (mai eficient!):\nINSERT INTO produse (nume, pret, categorie, stoc)\nVALUES\n    ('Tastatura Mecanica', 350, 'electronics', 25),\n    ('Webcam HD', 200, 'electronics', 18),\n    ('Suport Monitor', 150, 'accessories', 40);\n\n-- INSERT cu SELECT — copiezi date dintr-o altă tabelă:\nINSERT INTO arhiva_produse (id, nume, pret)\nSELECT id, nume, pret FROM produse WHERE stoc = 0;\n```\n\n**RETURNING** (PostgreSQL) — returnează datele inserate:\n```sql\nINSERT INTO produse (nume, pret)\nVALUES ('Noua placa video', 2500)\nRETURNING id, nume;  -- returnează id-ul generat automat\n```",
      },
      {
        order: 2,
        title: "UPDATE și DELETE — modificare și ștergere",
        content: "**UPDATE** — modifică rânduri existente. **ATENȚIE MAXIMĂ: fără WHERE, actualizezi TOATĂ tabela!**\n\n```sql\n-- Actualizare cu WHERE (corect):\nUPDATE produse\nSET pret = 3200, stoc = 10\nWHERE id = 1;\n\n-- Actualizare bazată pe valoare curentă:\nUPDATE produse\nSET pret = pret * 0.9   -- reducere 10%\nWHERE categorie = 'electronics';\n\n-- DEZASTRU — fără WHERE modifici TOATE rândurile!\nUPDATE produse SET pret = 0;   -- toate prețurile → 0!\n\n-- Pattern sigur: testezi cu SELECT înainte:\nSELECT * FROM produse WHERE id = 5;  -- verifici ce vei modifica\nUPDATE produse SET stoc = 0 WHERE id = 5;  -- acum modifici\n```\n\n**DELETE — ștergere:**\n```sql\n-- Șterge un rând specific:\nDELETE FROM produse WHERE id = 5;\n\n-- Șterge cu condiție:\nDELETE FROM produse WHERE stoc = 0 AND categorie = 'accessories';\n\n-- DEZASTRU — șterge TOATE rândurile!\nDELETE FROM produse;  -- tabela rămâne goală!\n\n-- TRUNCATE — mai rapid decât DELETE ALL, resetează și AUTO_INCREMENT:\nTRUNCATE TABLE produse;  -- nu se poate face ROLLBACK!\n```\n\n**La interviu:** *Diferența DELETE vs TRUNCATE?*\n```\nDELETE:   filtreaza cu WHERE, logat în tranzacție, poate ROLLBACK\nTRUNCATE: șterge tot, mai rapid, resetează auto_increment, fără ROLLBACK\n```",
      },
      {
        order: 3,
        title: "Tranzacții — ACID și atomicitate",
        content: "O **tranzacție** e un grup de operații care fie se execută TOT, fie NIMIC. E ca transferul bancar:\n\n```\n// Transfer de 100 RON de la Ana la Ion:\nScade 100 din contul Anei     → \nAdaugă 100 în contul lui Ion  →  Dacă al 2-lea pică, primul trebuie anulat!\n```\n\n**Comenzi de tranzacție:**\n```sql\nBEGIN;  -- sau START TRANSACTION; — deschide tranzacția\n\n-- Operațiile tale:\nUPDATE conturi SET sold = sold - 100 WHERE user_id = 1;\nUPDATE conturi SET sold = sold + 100 WHERE user_id = 2;\n\nCOMMIT;  -- confirmi — salvează toate modificările\n-- SAU\nROLLBACK;  -- anulezi — revii la starea inițială\n```\n\n**Exemplu practic cu tratare erori:**\n```sql\nBEGIN;\n\nUPDATE stoc SET cantitate = cantitate - 5 WHERE produs_id = 1;\n\n-- Verifici dacă stocul a ajuns negativ:\nSELECT cantitate FROM stoc WHERE produs_id = 1;\n-- Dacă cantitate < 0:\nROLLBACK;  -- anulezi comanda\n-- Altfel:\nINSERT INTO comenzi (user_id, produs_id, cant) VALUES (42, 1, 5);\nCOMMIT;  -- confirmi\n```\n\n**ACID — proprietățile unei tranzacții corecte:**\n```\nA — Atomicity:   Tot sau nimic (COMMIT/ROLLBACK)\nC — Consistency: Baza de date trece dintr-o stare validă în alta\nI — Isolation:   Tranzacțiile paralele nu se interferează\nD — Durability:  Ce e COMMIT-at rămâne salvat chiar și la crash\n```\n\n**La interviu:** ACID e întrebat clasic la orice job backend/DB.",
      },
      {
        order: 4,
        title: "Constrângeri — integritatea datelor",
        content: "**Constrângerile** (constraints) sunt reguli care protejează calitatea datelor. Baza de date refuză orice operație care le încalcă:\n\n```sql\nCREATE TABLE utilizatori (\n    id       INT PRIMARY KEY AUTO_INCREMENT,\n    email    VARCHAR(255) UNIQUE NOT NULL,     -- unic, obligatoriu\n    username VARCHAR(50)  UNIQUE NOT NULL,\n    varsta   INT          CHECK(varsta >= 0),  -- trebuie să fie pozitiv\n    rol      ENUM('user','admin') DEFAULT 'user',\n    creat_la TIMESTAMP    DEFAULT CURRENT_TIMESTAMP\n);\n```\n\n**Tipuri de constrângeri:**\n```sql\nPRIMARY KEY    -- identificator unic al rândului, nu poate fi NULL\nFOREIGN KEY    -- referință la alt tabel (integritate referențială)\nUNIQUE         -- valorile trebuie să fie unice în coloană\nNOT NULL       -- câmpul nu poate fi NULL\nCHECK          -- condiție personalizată (CHECK(pret > 0))\nDEFAULT        -- valoare implicită dacă nu e furnizată\n```\n\n**FOREIGN KEY cu CASCADE:**\n```sql\nCREATE TABLE comenzi (\n    id        INT PRIMARY KEY AUTO_INCREMENT,\n    user_id   INT NOT NULL,\n    FOREIGN KEY (user_id) REFERENCES utilizatori(id)\n        ON DELETE CASCADE   -- șterge comenzile dacă userul e șters\n        ON UPDATE CASCADE   -- actualizează id dacă userul e redenumit\n);\n\n-- Opțiuni ON DELETE:\n-- CASCADE     — șterge și rândurile copil\n-- RESTRICT    — nu permite ștergerea dacă există copii (implicit)\n-- SET NULL    — setează FK la NULL\n-- SET DEFAULT — setează la valoarea default\n```",
      },
    ],
    tasks: [
      {
        number: 1,
        name: "INSERT syntax",
        question: "Cum inserezi un produs nou cu nume='Mouse' și pret=80 în tabela produse?",
        options: [
          "ADD INTO produse VALUES ('Mouse', 80)",
          "INSERT INTO produse (nume, pret) VALUES ('Mouse', 80)",
          "INSERT produse SET nume='Mouse', pret=80",
          "CREATE ROW produse (nume='Mouse', pret=80)",
        ],
        answer: "INSERT INTO produse (nume, pret) VALUES ('Mouse', 80)",
        explanation: "Sintaxa INSERT INTO tabel (col1, col2) VALUES (val1, val2). Specifică coloanele explicit — mai sigur dacă se adaugă coloane noi.",
        difficulty: "easy",
      },
      {
        number: 2,
        name: "UPDATE cu WHERE",
        question: "Ce se întâmplă dacă scrii `UPDATE produse SET pret = 0` fără WHERE?",
        options: [
          "Eroare — UPDATE necesită WHERE",
          "Actualizează primul rând",
          "Actualizează TOATE rândurile din tabelă",
          "Nu face nimic",
        ],
        answer: "Actualizează TOATE rândurile din tabelă",
        explanation: "Fără WHERE, UPDATE afectează TOATE rândurile. Toate prețurile devin 0 — dezastru! Testează întotdeauna cu SELECT înainte.",
        difficulty: "easy",
      },
      {
        number: 3,
        name: "DELETE vs TRUNCATE",
        question: "Care e diferența principală dintre DELETE și TRUNCATE?",
        options: [
          "DELETE e mai rapid",
          "TRUNCATE poate fi filtrat cu WHERE",
          "DELETE poate fi ROLLBACK-at, TRUNCATE nu. DELETE filtrează cu WHERE, TRUNCATE șterge tot",
          "Nu există diferență",
        ],
        answer: "DELETE poate fi ROLLBACK-at, TRUNCATE nu. DELETE filtrează cu WHERE, TRUNCATE șterge tot",
        explanation: "TRUNCATE e DDL (nu DML) — nu se poate anula. DELETE e DML — e în tranzacție, poate fi anulat. TRUNCATE resetează și AUTO_INCREMENT.",
        difficulty: "medium",
      },
      {
        number: 4,
        name: "COMMIT",
        question: "Ce face `COMMIT` la finalul unei tranzacții?",
        options: [
          "Anulează modificările",
          "Salvează definitiv toate modificările din tranzacție",
          "Deschide o nouă tranzacție",
          "Verifică erorile",
        ],
        answer: "Salvează definitiv toate modificările din tranzacție",
        explanation: "COMMIT confirmă tranzacția — modificările sunt scrise permanent pe disk. Opusul e ROLLBACK care le anulează.",
        difficulty: "easy",
      },
      {
        number: 5,
        name: "ACID Atomicity",
        question: "Ce înseamnă 'A' din ACID (Atomicity)?",
        options: [
          "Datele sunt stocate automat",
          "Tranzacția fie se execută complet, fie deloc",
          "Accesul e restricționat",
          "Datele sunt indexate automat",
        ],
        answer: "Tranzacția fie se execută complet, fie deloc",
        explanation: "Atomicitate = tot sau nimic. Dacă oricare operație din tranzacție eșuează, toate sunt anulate (ROLLBACK automat).",
        difficulty: "medium",
      },
      {
        number: 6,
        name: "INSERT multiple",
        question: "Cum inserezi 3 rânduri cu un singur INSERT?",
        options: [
          "3 instrucțiuni INSERT separate",
          "INSERT INTO t (col) VALUES (v1), (v2), (v3)",
          "INSERT MULTIPLE INTO t VALUES ...",
          "BATCH INSERT INTO t ...",
        ],
        answer: "INSERT INTO t (col) VALUES (v1), (v2), (v3)",
        explanation: "Un singur INSERT poate insera multiple rânduri cu VALUES (v1), (v2), (v3). E mult mai eficient decât N INSERT-uri separate.",
        difficulty: "medium",
      },
      {
        number: 7,
        name: "PRIMARY KEY",
        question: "Ce garantează PRIMARY KEY la o coloană?",
        options: [
          "Valorile sunt sortate crescător",
          "Valorile sunt unice și nu pot fi NULL",
          "Coloana e indexată automat",
          "Valorile sunt unice și nu pot fi NULL, identificând unic fiecare rând",
        ],
        answer: "Valorile sunt unice și nu pot fi NULL, identificând unic fiecare rând",
        explanation: "PRIMARY KEY = UNIQUE + NOT NULL. Fiecare tabelă ar trebui să aibă un PK. E și indexat automat pentru căutări rapide.",
        difficulty: "medium",
      },
      {
        number: 8,
        name: "FOREIGN KEY CASCADE",
        question: "Ce face `ON DELETE CASCADE` la o FOREIGN KEY?",
        options: [
          "Interzice ștergerea rândului parinte dacă are copii",
          "Șterge automat rândurile copil când se șterge rândul parinte",
          "Setează FK la NULL",
          "Copiază rândul parinte",
        ],
        answer: "Șterge automat rândurile copil când se șterge rândul parinte",
        explanation: "ON DELETE CASCADE: dacă ștergi un user, se șterg automat toate comenzile lui. Alternativa RESTRICT interzice ștergerea dacă există copii.",
        difficulty: "medium",
      },
      {
        number: 9,
        name: "ROLLBACK",
        question: "Când folosești ROLLBACK?",
        options: [
          "La finalul fiecărei sesiuni",
          "Când vrei să anulezi modificările dintr-o tranzacție neterminată",
          "Înainte de SELECT",
          "La optimizarea query-urilor",
        ],
        answer: "Când vrei să anulezi modificările dintr-o tranzacție neterminată",
        explanation: "ROLLBACK anulează toate modificările de la ultimul BEGIN/COMMIT. E salvarea ta când detectezi o eroare în mijlocul unei tranzacții.",
        difficulty: "medium",
      },
      {
        number: 10,
        name: "UPDATE sigur",
        question: "Care e practica recomandată ÎNAINTE de a rula un UPDATE important?",
        options: [
          "Face backup automat",
          "Rulează SELECT cu aceleași condiții WHERE să verifici exact ce vei modifica",
          "Creează un index",
          "Oprești alte conexiuni",
        ],
        answer: "Rulează SELECT cu aceleași condiții WHERE să verifici exact ce vei modifica",
        explanation: "SELECT * FROM t WHERE id = 5 înainte de UPDATE t SET ... WHERE id = 5. Dacă SELECT returnează ce te aștepți, e sigur să faci UPDATE.",
        difficulty: "medium",
      },
    ],
  },
  {
    slug: "sql-aggregate-groupby",
    title: "3. Funcții agregate + GROUP BY",
    order: 3,
    theory: [
      {
        order: 1,
        title: "Funcții agregate — calculează statistici",
        content: "**Funcțiile agregate** fac calcule pe un set de rânduri și returnează o singură valoare. E ca un calculator care primește o coloană și returneazå un număr:\n\n```sql\n-- COUNT — numără rânduri:\nSELECT COUNT(*) FROM produse;                    -- total rânduri\nSELECT COUNT(DISTINCT categorie) FROM produse;   -- categorii unice\nSELECT COUNT(descriere) FROM produse;            -- rânduri unde descriere ≠ NULL\n-- COUNT(*) numără toate rândurile inclusiv cu NULL\n-- COUNT(coloana) ignoră valorile NULL!\n\n-- SUM — suma valorilor:\nSELECT SUM(pret) FROM produse;          -- suma tuturor prețurilor\nSELECT SUM(pret * stoc) AS valoare_stoc FROM produse;  -- valoare totală\n\n-- AVG — media aritmetică:\nSELECT AVG(pret) FROM produse;          -- prețul mediu\nSELECT ROUND(AVG(pret), 2) AS pret_mediu FROM produse;\n\n-- MIN și MAX:\nSELECT MIN(pret) AS cel_mai_ieftin FROM produse;\nSELECT MAX(pret) AS cel_mai_scump FROM produse;\nSELECT MIN(creat_la) AS primul_produs FROM produse;\n\n-- Combinate:\nSELECT\n    COUNT(*) AS nr_produse,\n    SUM(pret * stoc) AS valoare_totala,\n    ROUND(AVG(pret), 2) AS pret_mediu,\n    MIN(pret) AS minim,\n    MAX(pret) AS maxim\nFROM produse;\n```",
      },
      {
        order: 2,
        title: "GROUP BY — grupează și calculează pe grupuri",
        content: "**GROUP BY** împarte rândurile în grupuri după valoarea unei coloane, apoi aplică funcțiile agregate pe fiecare grup:\n\n```sql\n-- Statistici per categorie:\nSELECT\n    categorie,\n    COUNT(*)        AS nr_produse,\n    SUM(stoc)       AS stoc_total,\n    ROUND(AVG(pret), 2) AS pret_mediu,\n    MAX(pret)       AS cel_mai_scump\nFROM produse\nGROUP BY categorie;\n\n-- Rezultat:\n-- electronics | 3 | 77 | 1806.67 | 3500\n-- furniture   | 2 | 11 | 1000.00 | 1200\n\n-- Grupare după mai multe coloane:\nSELECT\n    an_fabricatie,\n    categorie,\n    COUNT(*) AS nr_produse\nFROM produse\nGROUP BY an_fabricatie, categorie\nORDER BY an_fabricatie DESC;\n```\n\n**Regula de aur GROUP BY:**\nÎn SELECT poți pune NUMAI:\n1. Coloanele din GROUP BY\n2. Funcții agregate (COUNT, SUM, AVG, MIN, MAX)\nNu poți pune alte coloane! (PostgreSQL e strict, MySQL mai indulgent)\n\n```sql\n-- GREȘIT (în PostgreSQL strict):\nSELECT categorie, nume, COUNT(*) FROM produse GROUP BY categorie;\n-- ERROR: 'nume' must appear in GROUP BY\n\n-- CORECT:\nSELECT categorie, COUNT(*) FROM produse GROUP BY categorie;\n```",
      },
      {
        order: 3,
        title: "HAVING — filtru pe grupuri (nu pe rânduri!)",
        content: "**HAVING** e ca WHERE dar pentru grupuri. WHERE filtrează rânduri înainte de grupare, HAVING filtrează grupuri după agregare:\n\n```sql\n-- Categoriile cu mai mult de 2 produse:\nSELECT\n    categorie,\n    COUNT(*) AS nr_produse\nFROM produse\nGROUP BY categorie\nHAVING COUNT(*) > 2;\n\n-- Categoriile cu prețul mediu > 500:\nSELECT\n    categorie,\n    ROUND(AVG(pret), 2) AS pret_mediu\nFROM produse\nGROUP BY categorie\nHAVING AVG(pret) > 500;\n\n-- WHERE și HAVING împreună:\nSELECT\n    categorie,\n    COUNT(*) AS nr_produse_active\nFROM produse\nWHERE stoc > 0                    -- WHERE: filtrează rânduri ÎNAINTE de grupare\nGROUP BY categorie\nHAVING COUNT(*) >= 2              -- HAVING: filtrează grupuri DUPĂ agregare\nORDER BY nr_produse_active DESC;\n```\n\n**Diferența cheie WHERE vs HAVING:**\n```\nWHERE   → rulează ÎNAINTE de GROUP BY, pe rânduri individuale\nHAVING  → rulează DUPĂ GROUP BY, pe grupuri agregate\n\nWHERE nu poate folosi funcții agregate:\nWHERE AVG(pret) > 500  ← EROARE\nHAVING AVG(pret) > 500 ← CORECT\n```",
      },
      {
        order: 4,
        title: "Ordinea completă a clauzelor SQL",
        content: "SQL are o ordine strictă de execuție. Înțelegerea ei explică de ce unele erori apar:\n\n**Ordinea de scriere** (sintaxă):\n```sql\nSELECT   col1, AGG(col2)\nFROM     tabela\nJOIN     alta_tabela ON ...\nWHERE    conditie_pe_randuri\nGROUP BY col1\nHAVING   conditie_pe_grupuri\nORDER BY col1\nLIMIT    n\nOFFSET   m;\n```\n\n**Ordinea de EXECUȚIE** (cum procesează baza de date):\n```\n1. FROM     — identifică tabelele\n2. JOIN     — combină tabelele\n3. WHERE    — filtrează rândurile\n4. GROUP BY — creează grupurile\n5. HAVING   — filtrează grupurile\n6. SELECT   — calculează expresiile și aliasele\n7. DISTINCT — elimină duplicatele\n8. ORDER BY — sortează (poate folosi aliasele din SELECT)\n9. LIMIT    — restricționează numărul de rânduri\n```\n\nDe aceea **nu poți folosi alias-ul din SELECT în WHERE**:\n```sql\n-- GREȘIT:\nSELECT pret * 1.19 AS pret_tva\nFROM produse\nWHERE pret_tva > 500;  -- ERROR: pret_tva nu există la pasul WHERE!\n\n-- CORECT:\nSELECT pret * 1.19 AS pret_tva\nFROM produse\nWHERE pret * 1.19 > 500;  -- repetă expresia\n-- SAU\nSELECT pret * 1.19 AS pret_tva\nFROM produse\nHAVING pret_tva > 500;  -- HAVING e după SELECT, aliasul e disponibil\n```\n\n**La interviu:** Explicarea ordinii de execuție arată că înțelegi SQL la un nivel profund.",
      },
    ],
    tasks: [
      {
        number: 1,
        name: "COUNT(*) vs COUNT(col)",
        question: "Diferența dintre `COUNT(*)` și `COUNT(email)`?",
        options: [
          "Identice",
          "COUNT(*) numără toate rândurile; COUNT(email) ignoră rândurile unde email e NULL",
          "COUNT(*) e mai rapid",
          "COUNT(email) numără caractere",
        ],
        answer: "COUNT(*) numără toate rândurile; COUNT(email) ignoră rândurile unde email e NULL",
        explanation: "COUNT(*) = total rânduri incluzând NULL. COUNT(coloana) = rândurile unde coloana nu e NULL.",
        difficulty: "medium",
      },
      {
        number: 2,
        name: "SUM",
        question: "Ce returnează `SELECT SUM(pret * stoc) FROM produse`?",
        options: [
          "Suma tuturor prețurilor",
          "Valoarea totală a stocului (pret × stoc pentru fiecare produs, totalizate)",
          "Numărul de produse",
          "Media prețurilor",
        ],
        answer: "Valoarea totală a stocului (pret × stoc pentru fiecare produs, totalizate)",
        explanation: "SUM(pret * stoc) calculează pret×stoc pentru fiecare rând, apoi sumează totul — valoarea monetară totală a stocului.",
        difficulty: "medium",
      },
      {
        number: 3,
        name: "GROUP BY",
        question: "Ce returnează `SELECT categorie, COUNT(*) FROM produse GROUP BY categorie`?",
        options: [
          "Toate produsele cu categoriile lor",
          "Câte produse există în fiecare categorie",
          "Categoriile unice",
          "Eroare",
        ],
        answer: "Câte produse există în fiecare categorie",
        explanation: "GROUP BY categorie creează un grup per categorie, COUNT(*) numără rândurile din fiecare grup.",
        difficulty: "easy",
      },
      {
        number: 4,
        name: "HAVING vs WHERE",
        question: "Cum filtrezi categoriile cu mai mult de 5 produse?",
        options: [
          "WHERE COUNT(*) > 5",
          "HAVING COUNT(*) > 5",
          "WHERE nr_produse > 5",
          "FILTER COUNT(*) > 5",
        ],
        answer: "HAVING COUNT(*) > 5",
        explanation: "HAVING filtrează GRUPURI după GROUP BY. WHERE nu poate folosi funcții agregate — se aplică înainte de grupare.",
        difficulty: "medium",
      },
      {
        number: 5,
        name: "AVG",
        question: "Ce face `SELECT ROUND(AVG(pret), 2) FROM produse`?",
        options: [
          "Returnează prețul median",
          "Returnează media aritmetică a prețurilor rotunjită la 2 zecimale",
          "Sortează prețurile",
          "Returnează prețul maxim",
        ],
        answer: "Returnează media aritmetică a prețurilor rotunjită la 2 zecimale",
        explanation: "AVG calculează media, ROUND(val, 2) rotunjește la 2 zecimale.",
        difficulty: "easy",
      },
      {
        number: 6,
        name: "GROUP BY regulă",
        question: "În SELECT cu GROUP BY, ce coloane poți pune?",
        options: [
          "Orice coloană din tabelă",
          "Numai coloanele din GROUP BY și/sau funcții agregate",
          "Numai funcții agregate",
          "Numai coloana din GROUP BY",
        ],
        answer: "Numai coloanele din GROUP BY și/sau funcții agregate",
        explanation: "Regula fundamentală: SELECT poate conține doar coloanele din GROUP BY + funcții agregate. Altfel PostgreSQL aruncă eroare.",
        difficulty: "medium",
      },
      {
        number: 7,
        name: "Ordinea execuție",
        question: "De ce nu poți folosi un alias definit în SELECT în clauza WHERE?",
        options: [
          "Sintaxă greșită",
          "WHERE se execută ÎNAINTE de SELECT — aliasul nu există încă",
          "Aliasul nu e valid în SQL standard",
          "Poți, dar e mai lent",
        ],
        answer: "WHERE se execută ÎNAINTE de SELECT — aliasul nu există încă",
        explanation: "Ordinea: FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY. SELECT (unde se definesc aliasele) vine după WHERE.",
        difficulty: "hard",
      },
      {
        number: 8,
        name: "MIN MAX",
        question: "Cum găsești simultan cel mai ieftin și cel mai scump produs?",
        options: [
          "SELECT MIN(pret), MAX(pret) FROM produse",
          "SELECT FIRST(pret), LAST(pret) FROM produse ORDER BY pret",
          "Necesită 2 query-uri separate",
          "SELECT RANGE(pret) FROM produse",
        ],
        answer: "SELECT MIN(pret), MAX(pret) FROM produse",
        explanation: "Funcțiile agregate se pot combina în același SELECT. Returnează un singur rând cu ambele valori.",
        difficulty: "easy",
      },
      {
        number: 9,
        name: "WHERE + HAVING",
        question: "Ce face WHERE în combinație cu GROUP BY?",
        options: [
          "WHERE filtrează grupurile formate",
          "WHERE filtrează rândurile ÎNAINTE de grupare",
          "WHERE e echivalent cu HAVING",
          "WHERE nu se poate folosi cu GROUP BY",
        ],
        answer: "WHERE filtrează rândurile ÎNAINTE de grupare",
        explanation: "WHERE rulează mai întâi și elimină rânduri. Apoi GROUP BY grupează rândurile rămase. HAVING filtrează grupurile rezultate.",
        difficulty: "medium",
      },
      {
        number: 10,
        name: "COUNT DISTINCT",
        question: "Cum numeri câte categorii distincte există în tabela produse?",
        options: [
          "SELECT COUNT(*) FROM produse GROUP BY categorie",
          "SELECT COUNT(DISTINCT categorie) FROM produse",
          "SELECT DISTINCT COUNT(categorie) FROM produse",
          "SELECT COUNT(categorie UNIQUE) FROM produse",
        ],
        answer: "SELECT COUNT(DISTINCT categorie) FROM produse",
        explanation: "COUNT(DISTINCT coloana) numără valorile unice. Returnează 1 număr — total categorii distincte.",
        difficulty: "medium",
      },
    ],
  },
  {
    slug: "sql-joins",
    title: "4. JOINs — combinarea tabelelor",
    order: 4,
    theory: [
      {
        order: 1,
        title: "De ce avem nevoie de JOINs — normalizarea datelor",
        content: "Bazele de date relaționale stochează datele în tabele **separate** pentru a evita duplicarea. Comenzile nu stochează datele complete ale userului — ci doar `user_id`. JOINs le combină la cerere:\n\n```\nTabela utilizatori:          Tabela comenzi:\n┌────┬──────┬──────────┐    ┌────┬─────────┬────────┐\n│ id │ nume │ email    │    │ id │ user_id │ total  │\n├────┼──────┼──────────┤    ├────┼─────────┼────────┤\n│  1 │ Ana  │ ana@...  │    │  1 │    1    │  250   │\n│  2 │ Ion  │ ion@...  │    │  2 │    1    │  180   │\n│  3 │ Maria│ maria@...│    │  3 │    2    │  420   │\n└────┴──────┴──────────┘    └────┴─────────┴────────┘\n```\n\nFără JOIN: știi comenzile dar nu știi cine le-a făcut.\nCu JOIN: combini tabelele și ai imaginea completă.\n\n**INNER JOIN — interesecția:**\n```sql\n-- Comenzile cu datele userilor:\nSELECT\n    u.nume,\n    u.email,\n    c.id    AS comanda_id,\n    c.total\nFROM comenzi c\nINNER JOIN utilizatori u ON c.user_id = u.id;\n-- Returnează NUMAI rândurile cu potrivire în AMBELE tabele\n-- Comenzile fără user NU apar, userii fără comenzi NU apar\n```\n\n**Aliasuri pentru tabele** — esențial când ai JOIN-uri:\n```sql\n-- u = utilizatori, c = comenzi, p = produse\nFROM comenzi c\nJOIN utilizatori u ON c.user_id = u.id\nJOIN produse p ON c.produs_id = p.id;\n```",
      },
      {
        order: 2,
        title: "LEFT JOIN și RIGHT JOIN — include și rândurile fără potrivire",
        content: "**LEFT JOIN** returnează TOT din tabela stângă + potrivirile din dreapta. Dacă nu există potrivire dreapta → NULL:\n\n```sql\n-- TOȚI userii, cu sau fără comenzi:\nSELECT\n    u.id,\n    u.nume,\n    COUNT(c.id) AS nr_comenzi,\n    COALESCE(SUM(c.total), 0) AS total_cheltuit\nFROM utilizatori u\nLEFT JOIN comenzi c ON c.user_id = u.id\nGROUP BY u.id, u.nume;\n\n-- Userii fără nicio comandă apar cu nr_comenzi=0, total_cheltuit=0\n\n-- Pattern clasic: găsirea rândurilor fără potrivire:\nSELECT u.id, u.nume\nFROM utilizatori u\nLEFT JOIN comenzi c ON c.user_id = u.id\nWHERE c.id IS NULL;  -- userii care NU au nicio comandă\n```\n\n**Comparație vizuală:**\n```\nTabela A:  1, 2, 3, 4\nTabela B:     2, 3,    5\n\nINNER JOIN:     2, 3         ← doar potrivirile\nLEFT JOIN:  1, 2, 3, 4       ← tot din A + potrivirile din B\nRIGHT JOIN:    2, 3,    5    ← tot din B + potrivirile din A\nFULL JOIN:  1, 2, 3, 4, 5   ← tot din ambele\n```\n\n**RIGHT JOIN** — rar folosit (se preferă LEFT JOIN cu tabelele inversate):\n```sql\n-- Echivalente:\nFROM a LEFT JOIN b  ON a.id = b.a_id\nFROM b RIGHT JOIN a ON a.id = b.a_id  -- idem, mai confuz\n```",
      },
      {
        order: 3,
        title: "JOIN cu GROUP BY, SELF JOIN și CROSS JOIN",
        content: "**JOIN cu GROUP BY** — combinație uzuală în practică:\n```sql\n-- Top 5 clienți după suma cheltuită:\nSELECT\n    u.id,\n    u.nume,\n    COUNT(c.id)       AS nr_comenzi,\n    SUM(c.total)      AS total_cheltuit,\n    AVG(c.total)      AS medie_comanda,\n    MAX(c.creat_la)   AS ultima_comanda\nFROM utilizatori u\nINNER JOIN comenzi c ON c.user_id = u.id\nGROUP BY u.id, u.nume\nORDER BY total_cheltuit DESC\nLIMIT 5;\n```\n\n**SELF JOIN** — o tabelă joined cu ea însăși. Uzual pentru ierarhii:\n```sql\n-- Tabela angajati: id, nume, manager_id (FK la același tabel)\nSELECT\n    a.nume      AS angajat,\n    m.nume      AS manager\nFROM angajati a\nLEFT JOIN angajati m ON a.manager_id = m.id;\n-- CEO apare cu manager NULL (LEFT JOIN include și el)\n```\n\n**CROSS JOIN** — produsul cartezian (fiecare rând cu fiecare):\n```sql\n-- Toate combinațiile posibile de culori și mărimi:\nSELECT c.culoare, m.marime\nFROM culori c\nCROSS JOIN marimi m;\n-- 3 culori × 4 mărimi = 12 combinații\n-- ATENȚIE: cu tabele mari produce milioane de rânduri!\n```",
      },
      {
        order: 4,
        title: "Performanță la JOIN-uri și greșeli comune",
        content: "**JOIN-urile sunt costisitoare** dacă nu ai indecși pe coloanele de join:\n\n```sql\n-- Fără index: baza de date scanează complet tabela la fiecare JOIN\nSELECT * FROM comenzi c\nJOIN utilizatori u ON c.user_id = u.id;\n-- Dacă comenzi are 1 milion rânduri și nu are index pe user_id → LENT!\n\n-- Adaugă index pe coloana de join:\nCREATE INDEX idx_comenzi_user_id ON comenzi(user_id);\n-- Acum JOIN-ul e de 100x mai rapid!\n```\n\n**Greșeli comune la interviuri:**\n```sql\n-- 1. JOIN fără ON — produce CROSS JOIN accidental:\nSELECT * FROM a, b WHERE a.id = b.a_id;  -- sintaxă veche\nSELECT * FROM a JOIN b ON a.id = b.a_id; -- sintaxă modernă și clară\n\n-- 2. Confuzie ON vs WHERE în LEFT JOIN:\nSELECT u.*, c.total\nFROM utilizatori u\nLEFT JOIN comenzi c ON c.user_id = u.id\nWHERE c.total > 100;  -- GREȘIT: WHERE transformă LEFT în INNER JOIN!\n-- (userii fără comenzi au c.total = NULL → NULL > 100 = false → dispar)\n\n-- CORECT: filtrul pe tabelul din dreapta merge în ON:\nFROM utilizatori u\nLEFT JOIN comenzi c ON c.user_id = u.id AND c.total > 100;\n-- Acum toți userii apar, dar joinuim NUMAI comenzile > 100\n```\n\n**La interviu:** Explicarea diferenței dintre filtrarea în ON vs WHERE la LEFT JOIN arată înțelegere profundă.",
      },
    ],
    tasks: [
      {
        number: 1,
        name: "INNER JOIN",
        question: "Ce returnează INNER JOIN dintre tabelele utilizatori și comenzi?",
        options: [
          "Toți userii, indiferent dacă au comenzi",
          "Toate comenzile cu datele userilor care le-au plasat — NUMAI potrivirile",
          "Toate comenzile, indiferent dacă userul există",
          "Produsul cartezian",
        ],
        answer: "Toate comenzile cu datele userilor care le-au plasat — NUMAI potrivirile",
        explanation: "INNER JOIN returnează NUMAI rândurile cu potrivire în ambele tabele. Userii fără comenzi și comenzile fără user NU apar.",
        difficulty: "easy",
      },
      {
        number: 2,
        name: "LEFT JOIN",
        question: "Ce diferențiază LEFT JOIN de INNER JOIN?",
        options: [
          "LEFT JOIN e mai rapid",
          "LEFT JOIN returnează TOT din tabela stângă, chiar dacă nu există potrivire în dreapta",
          "LEFT JOIN returnează tot din ambele tabele",
          "LEFT JOIN poate fi folosit cu mai mult de 2 tabele",
        ],
        answer: "LEFT JOIN returnează TOT din tabela stângă, chiar dacă nu există potrivire în dreapta",
        explanation: "LEFT JOIN include toate rândurile din tabela stângă. Dacă nu există potrivire în dreapta, coloanele drepte apar ca NULL.",
        difficulty: "easy",
      },
      {
        number: 3,
        name: "JOIN ON sintaxă",
        question: "Care e sintaxa corectă pentru un INNER JOIN?",
        options: [
          "FROM a JOIN b WHERE a.id = b.a_id",
          "FROM a INNER JOIN b ON a.id = b.a_id",
          "FROM a, b WITH a.id = b.a_id",
          "FROM a JOIN b USING id",
        ],
        answer: "FROM a INNER JOIN b ON a.id = b.a_id",
        explanation: "JOIN ... ON specifică condiția de join. INNER e opțional (JOIN implicit = INNER JOIN). ON e obligatoriu (fără el → CROSS JOIN).",
        difficulty: "easy",
      },
      {
        number: 4,
        name: "LEFT JOIN NULL pattern",
        question: "Cum găsești userii care NU au nicio comandă?",
        options: [
          "WHERE user_id NOT IN (SELECT user_id FROM comenzi)",
          "LEFT JOIN comenzi ON user_id = id WHERE comenzi.id IS NULL",
          "Ambele variante de mai sus sunt corecte",
          "INNER JOIN cu NOT",
        ],
        answer: "Ambele variante de mai sus sunt corecte",
        explanation: "LEFT JOIN + WHERE dreapta IS NULL e pattern-ul clasic pentru anti-join. NOT IN cu subquery e alternativa — mai puțin eficientă dacă subquery-ul e mare.",
        difficulty: "medium",
      },
      {
        number: 5,
        name: "SELF JOIN",
        question: "Pentru ce tip de date e util SELF JOIN?",
        options: [
          "Date numerice",
          "Ierarhii și relații în aceeași tabelă — ex: angajat-manager",
          "Date temporale",
          "Tabele cu multe coloane",
        ],
        answer: "Ierarhii și relații în aceeași tabelă — ex: angajat-manager",
        explanation: "SELF JOIN = tabela joined cu ea însăși. Util pentru arbori: categorii cu subcategorii, angajat-manager, comentarii cu răspunsuri.",
        difficulty: "medium",
      },
      {
        number: 6,
        name: "ON vs WHERE in LEFT JOIN",
        question: "Ce se întâmplă când pui un filtru pe tabela dreaptă în WHERE la un LEFT JOIN?",
        options: [
          "Funcționează identic cu ON",
          "WHERE transformă efectiv LEFT JOIN în INNER JOIN — rândurile fără potrivire dispar",
          "Produce eroare",
          "Se aplică după JOIN",
        ],
        answer: "WHERE transformă efectiv LEFT JOIN în INNER JOIN — rândurile fără potrivire dispar",
        explanation: "NULL > 100 este NULL (false) → rândurile fără potrivire sunt eliminate de WHERE. Filtrul pe tabela dreaptă merge în ON, nu WHERE.",
        difficulty: "hard",
      },
      {
        number: 7,
        name: "JOIN cu GROUP BY",
        question: "Cum găsești numărul de comenzi per user (afișând și userii cu 0 comenzi)?",
        options: [
          "FROM comenzi c INNER JOIN utilizatori u ON ... GROUP BY u.id",
          "FROM utilizatori u LEFT JOIN comenzi c ON ... GROUP BY u.id",
          "FROM utilizatori u RIGHT JOIN comenzi c ON ... GROUP BY c.id",
          "Nu se poate, necesită subquery",
        ],
        answer: "FROM utilizatori u LEFT JOIN comenzi c ON ... GROUP BY u.id",
        explanation: "LEFT JOIN de la utilizatori + GROUP BY u.id include toți userii. COUNT(c.id) returnează 0 (nu NULL) pentru userii fără comenzi.",
        difficulty: "medium",
      },
      {
        number: 8,
        name: "CROSS JOIN",
        question: "Dacă tabela A are 100 rânduri și B are 50, câte rânduri produce CROSS JOIN?",
        options: ["150", "50", "5000", "100"],
        answer: "5000",
        explanation: "CROSS JOIN = produsul cartezian. Fiecare rând din A combinat cu fiecare din B: 100 × 50 = 5000.",
        difficulty: "medium",
      },
      {
        number: 9,
        name: "Index pe FK",
        question: "De ce e important să ai un index pe coloana de FOREIGN KEY (ex: comenzi.user_id)?",
        options: [
          "E obligatoriu sintactic",
          "Face JOIN-urile mult mai rapide — baza de date nu scanează toată tabela",
          "Previne valorile duplicate",
          "Nu are impact semnificativ",
        ],
        answer: "Face JOIN-urile mult mai rapide — baza de date nu scanează toată tabela",
        explanation: "Fără index pe FK, JOIN-ul face un full table scan la fiecare rând. Cu index, face lookup O(log n). Pe milioane de rânduri diferența e de 100x+.",
        difficulty: "medium",
      },
      {
        number: 10,
        name: "JOIN aliasuri",
        question: "De ce e recomandat să folosești aliasuri de tabelă (ex: FROM utilizatori u)?",
        options: [
          "E obligatoriu cu JOIN",
          "Scurtează query-ul și clarifică de unde vine fiecare coloană — esențial când ai mai multe JOIN-uri",
          "Îmbunătățește performanța",
          "Evită erorile de SQL",
        ],
        answer: "Scurtează query-ul și clarifică de unde vine fiecare coloană — esențial când ai mai multe JOIN-uri",
        explanation: "u.email vs utilizatori.email — cu 3-4 JOIN-uri, aliasurile scurte (u, c, p) fac query-ul mult mai lizibil.",
        difficulty: "easy",
      },
    ],
  },
  {
    slug: "sql-subqueries",
    title: "5. Subquery-uri și CTE",
    order: 5,
    theory: [
      {
        order: 1,
        title: "Subquery-uri în WHERE și FROM",
        content: "Un **subquery** e un query în interiorul altui query — ca o întrebare în interiorul unei alte întrebări:\n\n**Subquery în WHERE:**\n```sql\n-- Produsele mai scumpe decât media:\nSELECT id, nume, pret\nFROM produse\nWHERE pret > (SELECT AVG(pret) FROM produse);\n-- Subquery-ul returnează un număr, WHERE compară cu el\n\n-- Userii care au plasat cel puțin o comandă:\nSELECT id, nume\nFROM utilizatori\nWHERE id IN (\n    SELECT DISTINCT user_id FROM comenzi\n);\n\n-- Produsele care NU au fost niciodată comandate:\nSELECT id, nume\nFROM produse\nWHERE id NOT IN (\n    SELECT DISTINCT produs_id FROM comenzi\n);\n-- ATENȚIE: NOT IN cu NULL produce rezultate greșite!\n-- Dacă subquery returnează NULL, NOT IN devine false pentru TOATE!\n-- Preferă NOT EXISTS (mai sigur)\n```\n\n**Subquery în FROM — tabele derivate:**\n```sql\n-- Media comenzilor per user, apoi filtrează:\nSELECT user_id, medie_comenzi\nFROM (\n    SELECT user_id, AVG(total) AS medie_comenzi\n    FROM comenzi\n    GROUP BY user_id\n) AS statistici_user  -- trebuie să dai alias subquery-ului!\nWHERE medie_comenzi > 200;\n```",
      },
      {
        order: 2,
        title: "EXISTS, ANY, ALL — subquery-uri corelate",
        content: "**EXISTS** — verifică dacă subquery-ul returnează cel puțin un rând:\n```sql\n-- Userii care au comenzi (mai eficient decât IN pentru tabele mari):\nSELECT id, nume\nFROM utilizatori u\nWHERE EXISTS (\n    SELECT 1 FROM comenzi c\n    WHERE c.user_id = u.id  -- corelat cu tabela exterioară!\n);\n\n-- NOT EXISTS — userii fără comenzi:\nSELECT id, nume\nFROM utilizatori u\nWHERE NOT EXISTS (\n    SELECT 1 FROM comenzi c\n    WHERE c.user_id = u.id\n);\n-- NOT EXISTS e mai sigur decât NOT IN — tratează NULL corect\n```\n\n**ANY / ALL:**\n```sql\n-- Produse mai scumpe decât ORICARE produs din categoria 'furniture':\nSELECT * FROM produse\nWHERE pret > ANY (\n    SELECT pret FROM produse WHERE categorie = 'furniture'\n);\n-- ANY = mai mare decât cel mai mic din grup\n\n-- Produse mai scumpe decât TOATE produsele din 'furniture':\nSELECT * FROM produse\nWHERE pret > ALL (\n    SELECT pret FROM produse WHERE categorie = 'furniture'\n);\n-- ALL = mai mare decât cel mai mare din grup\n```\n\n**Subquery corelat** — referă tabela exterioară (recalculat pentru fiecare rând):\n```sql\n-- Angajații cu salar > media departamentului lor:\nSELECT e.id, e.nume, e.salar, e.dept_id\nFROM angajati e\nWHERE e.salar > (\n    SELECT AVG(a2.salar)\n    FROM angajati a2\n    WHERE a2.dept_id = e.dept_id  -- corelat cu e\n);\n```",
      },
      {
        order: 3,
        title: "CTE — WITH — subquery-uri reutilizabile",
        content: "**CTE (Common Table Expression)** — definești un subquery cu nume, îl poți folosi de mai multe ori:\n\n```sql\n-- CTE simplu — alternativa la subquery în FROM:\nWITH statistici AS (\n    SELECT\n        user_id,\n        COUNT(*) AS nr_comenzi,\n        SUM(total) AS total_cheltuit\n    FROM comenzi\n    GROUP BY user_id\n)\nSELECT\n    u.nume,\n    s.nr_comenzi,\n    s.total_cheltuit\nFROM utilizatori u\nJOIN statistici s ON s.user_id = u.id\nORDER BY s.total_cheltuit DESC;\n\n-- Multiple CTE:\nWITH\ncomenzi_2024 AS (\n    SELECT * FROM comenzi WHERE YEAR(creat_la) = 2024\n),\ntop_useri AS (\n    SELECT user_id, SUM(total) AS suma\n    FROM comenzi_2024\n    GROUP BY user_id\n    ORDER BY suma DESC\n    LIMIT 10\n)\nSELECT u.nume, t.suma\nFROM utilizatori u\nJOIN top_useri t ON t.user_id = u.id;\n```\n\n**Avantajele CTE față de subquery:**\n```\n1. Mai lizibil — dai un nume expresiv subquery-ului\n2. Reutilizabil — îl poți referi de mai multe ori în query\n3. Recursiv — poți traversa ierarhii (WITH RECURSIVE)\n4. Debugging mai ușor — testezi CTE-ul separat\n```",
      },
      {
        order: 4,
        title: "CTE recursiv — traversare ierarhii",
        content: "**WITH RECURSIVE** permite traversarea structurilor ierarhice — categorii cu subcategorii, organigramă, arbori:\n\n```sql\n-- Tabelă categorii cu ierarhie:\n-- id | nume        | parent_id\n-- 1  | Electronics | NULL\n-- 2  | Phones      | 1\n-- 3  | Laptops     | 1\n-- 4  | Smartphones | 2\n\nWITH RECURSIVE ierarhie AS (\n    -- Caz de bază — rădăcina:\n    SELECT id, nume, parent_id, 0 AS nivel, CAST(nume AS VARCHAR(500)) AS path\n    FROM categorii\n    WHERE parent_id IS NULL\n    \n    UNION ALL\n    \n    -- Caz recursiv — copiii:\n    SELECT c.id, c.nume, c.parent_id, i.nivel + 1, CONCAT(i.path, ' > ', c.nume)\n    FROM categorii c\n    JOIN ierarhie i ON c.parent_id = i.id\n)\nSELECT id, nume, nivel, path\nFROM ierarhie\nORDER BY path;\n\n-- Rezultat:\n-- Electronics (nivel 0, path: 'Electronics')\n-- Laptops     (nivel 1, path: 'Electronics > Laptops')\n-- Phones      (nivel 1, path: 'Electronics > Phones')\n-- Smartphones (nivel 2, path: 'Electronics > Phones > Smartphones')\n```\n\n**La interviu:** Cunoașterea CTE recursiv arată experiență serioasă cu SQL.",
      },
    ],
    tasks: [
      {
        number: 1,
        name: "Subquery scalar",
        question: "Ce returnează subquery-ul din: `SELECT * FROM produse WHERE pret > (SELECT AVG(pret) FROM produse)`?",
        options: [
          "Un set de rânduri",
          "O singură valoare — media prețurilor",
          "Un boolean",
          "O eroare",
        ],
        answer: "O singură valoare — media prețurilor",
        explanation: "AVG() returnează o valoare scalară (un număr). Subquery-ul scalar returnează exact un rând cu o coloană.",
        difficulty: "medium",
      },
      {
        number: 2,
        name: "IN cu subquery",
        question: "Ce face `WHERE id IN (SELECT user_id FROM comenzi)`?",
        options: [
          "Filtrează userii care NU au comenzi",
          "Filtrează userii al căror id apare în coloan user_id din comenzi",
          "Returnează comenzile",
          "Produce eroare",
        ],
        answer: "Filtrează userii al căror id apare în coloan user_id din comenzi",
        explanation: "IN cu subquery verifică dacă valoarea există în setul returnat. Echivalent cu un JOIN + DISTINCT.",
        difficulty: "easy",
      },
      {
        number: 3,
        name: "EXISTS vs IN",
        question: "De ce e NOT EXISTS mai sigur decât NOT IN când subquery-ul poate returna NULL?",
        options: [
          "NOT EXISTS e mai rapid",
          "NOT IN cu NULL în setul returnat face condiția false pentru TOATE rândurile",
          "NOT EXISTS ignoră valorile NULL",
          "Nu există diferență",
        ],
        answer: "NOT IN cu NULL în setul returnat face condiția false pentru TOATE rândurile",
        explanation: "NULL IN (1, 2, NULL) = NULL (nu false). NOT IN returnează NOT NULL = NULL = false. Rezultat: 0 rânduri. NOT EXISTS nu are această problemă.",
        difficulty: "hard",
      },
      {
        number: 4,
        name: "CTE WITH",
        question: "Care e avantajul principal al unui CTE (WITH) față de un subquery în FROM?",
        options: [
          "E mai rapid",
          "Poate fi reutilizat și e mai lizibil — dai un nume expresiv",
          "Funcționează în mai multe baze de date",
          "Nu are avantaje",
        ],
        answer: "Poate fi reutilizat și e mai lizibil — dai un nume expresiv",
        explanation: "CTE-ul poate fi referit de mai multe ori în query și îmbunătățește lizibilitatea. Un subquery în FROM e anonim și nu se poate reutiliza.",
        difficulty: "medium",
      },
      {
        number: 5,
        name: "Subquery corelat",
        question: "Ce face un subquery corelat față de unul obișnuit?",
        options: [
          "Se execută o singură dată",
          "Se execută pentru fiecare rând al query-ului exterior — referă tabela exterioară",
          "Nu poate folosi funcții agregate",
          "E mai rapid",
        ],
        answer: "Se execută pentru fiecare rând al query-ului exterior — referă tabela exterioară",
        explanation: "Subquery-ul corelat are o referință la tabela exterioară (ex: WHERE dept_id = e.dept_id). Se recalculează pentru fiecare rând exterior.",
        difficulty: "hard",
      },
      {
        number: 6,
        name: "CTE recursiv uzual",
        question: "Pentru ce tip de date e folosit WITH RECURSIVE?",
        options: [
          "Date numerice repetitive",
          "Ierarhii — organigramă, categorii cu subcategorii, arbori de date",
          "Date temporale",
          "Tabele cu multe coloane",
        ],
        answer: "Ierarhii — organigramă, categorii cu subcategorii, arbori de date",
        explanation: "CTE recursiv permite traversarea structurilor arbore stocate în baze de date relaționale (parent_id referă același tabel).",
        difficulty: "medium",
      },
      {
        number: 7,
        name: "Alias subquery FROM",
        question: "De ce trebuie să dai alias unui subquery folosit în FROM?",
        options: [
          "E opțional — poate fi fără alias",
          "SQL cere un alias pentru tabela derivată — fără el produce eroare de sintaxă",
          "Îmbunătățește performanța",
          "Evită ambiguitatea coloanelor",
        ],
        answer: "SQL cere un alias pentru tabela derivată — fără el produce eroare de sintaxă",
        explanation: "FROM (SELECT ...) AS alias_obligatoriu — fără alias SQL nu știe cum să refere tabelă derivată în restul query-ului.",
        difficulty: "medium",
      },
      {
        number: 8,
        name: "ANY vs ALL",
        question: "Ce returnează `WHERE pret > ALL (SELECT pret FROM produse WHERE cat='A')`?",
        options: [
          "Produse mai scumpe decât orice produs din A",
          "Produse mai scumpe decât cel mai ieftin produs din A",
          "Produse mai ieftine decât toate produsele din A",
          "Eroare",
        ],
        answer: "Produse mai scumpe decât orice produs din A",
        explanation: "> ALL = mai mare decât MAXIMUM din set. > ANY = mai mare decât MINIMUM din set.",
        difficulty: "hard",
      },
      {
        number: 9,
        name: "Subquery SELECT",
        question: "Un subquery scalar în SELECT se evaluează:",
        options: [
          "O singură dată pentru tot query-ul",
          "O dată pentru fiecare rând returnat",
          "Niciodată — e optimizat",
          "Depinde de indexuri",
        ],
        answer: "O dată pentru fiecare rând returnat",
        explanation: "Un subquery corelat în SELECT se execută per rând exterior — poate fi lent dacă ai milioane de rânduri. Preferă JOIN când e posibil.",
        difficulty: "hard",
      },
      {
        number: 10,
        name: "Multiple CTE",
        question: "Cum definești 2 CTE-uri care se referă unul pe celălalt?",
        options: [
          "WITH cte1 AS (...) WITH cte2 AS (...) SELECT ...",
          "WITH cte1 AS (...), cte2 AS (...) SELECT ...",
          "Nu e posibil — fiecare WITH e separat",
          "DEFINE cte1 ... DEFINE cte2 ...",
        ],
        answer: "WITH cte1 AS (...), cte2 AS (...) SELECT ...",
        explanation: "Multiple CTE-uri se separă prin virgulă după WITH. Ordinea contează — un CTE poate referi CTE-urile definite înaintea lui.",
        difficulty: "medium",
      },
    ],
  },
  {
    slug: "sql-create-table",
    title: "6. CREATE TABLE, tipuri de date și relații",
    order: 6,
    theory: [
      {
        order: 1,
        title: "CREATE TABLE — designul schemei",
        content: "**CREATE TABLE** definește structura — coloanele, tipurile lor și constrângerile:\n\n```sql\nCREATE TABLE utilizatori (\n    id          INT          NOT NULL AUTO_INCREMENT,\n    email       VARCHAR(255) NOT NULL UNIQUE,\n    username    VARCHAR(50)  NOT NULL UNIQUE,\n    password_hash CHAR(60)   NOT NULL,  -- bcrypt produce fix 60 chars\n    nume        VARCHAR(100),\n    varsta      TINYINT UNSIGNED CHECK(varsta >= 13),\n    rol         ENUM('user', 'editor', 'admin') NOT NULL DEFAULT 'user',\n    activ       BOOLEAN      NOT NULL DEFAULT TRUE,\n    creat_la    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    actualizat  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n    PRIMARY KEY (id)\n);\n```\n\n**Modificare tabelă existentă:**\n```sql\n-- Adaugă coloană:\nALTER TABLE utilizatori ADD COLUMN telefon VARCHAR(20);\n\n-- Modifică tipul:\nALTER TABLE utilizatori MODIFY COLUMN nume VARCHAR(200);\n\n-- Redenumire:\nALTER TABLE utilizatori RENAME COLUMN username TO user_slug;\n\n-- Adaugă constrângere:\nALTER TABLE utilizatori ADD CONSTRAINT check_varsta CHECK(varsta >= 0);\n\n-- Șterge coloană:\nALTER TABLE utilizatori DROP COLUMN telefon;\n\n-- Șterge tabelă:\nDROP TABLE IF EXISTS utilizatori;\n```",
      },
      {
        order: 2,
        title: "Tipuri de date — alege corect pentru performanță",
        content: "Alegerea tipului de date afectează spațiul și viteza. Folosește cel mai mic tip care acoperă datele:\n\n**Numere întregi:**\n```sql\nTINYINT    -128..127 (1 byte)  — vârstă, stele review 1-5\nSMALLINT   -32K..32K (2 bytes) — cod poștal\nMEDIUMINT  -8M..8M   (3 bytes)\nINT        -2B..2B   (4 bytes) — ID, count — cel mai comun\nBIGINT     ±9×10^18  (8 bytes) — timestamps Unix, ID-uri foarte mari\n\n-- UNSIGNED dublează maximul pozitiv:\nINT UNSIGNED: 0 .. 4,294,967,295\n```\n\n**Text:**\n```sql\nCHAR(n)       — lungime fixă, completat cu spații. Util: cod ISO, hash\nVARCHAR(n)    — lungime variabilă, max n. Cel mai uzual: VARCHAR(255)\nTEXT          — text lung (64KB). Blog post, descriere produs\nMEDIUMTEXT    — 16MB. Conținut articole\nLONGTEXT      — 4GB. Rar necesar\nJSON          — date JSON (MySQL 5.7+, indexabil)\n```\n\n**Date și timp:**\n```sql\nDATE          — 'YYYY-MM-DD'                   — data nașterii\nTIME          — 'HH:MM:SS'                     — ora\nDATETIME      — 'YYYY-MM-DD HH:MM:SS'          — nu ține cont de timezone!\nTIMESTAMP     — seconds since 1970 (4 bytes)   — creat_la, actualizat_la\n                ← TIMESTAMP se convertește automat la UTC, DATETIME nu!\n```\n\n**Sfat important:**\n```sql\n-- E-mail: VARCHAR(255) — standardul permite max 254 caractere\n-- Preț: DECIMAL(10, 2) — NU FLOAT! (floating point imprecis: 9.99 ≠ 9.99 în float)\n-- Hash parole: CHAR(60) pentru bcrypt fix\n-- IP Address: VARCHAR(45) sau INT UNSIGNED (mai eficient)\n-- URL: VARCHAR(2048)\n```",
      },
      {
        order: 3,
        title: "Relații între tabele — 1:1, 1:N, M:N",
        content: "**1:1 (One-to-One)** — un rând din A corespunde cu un rând din B:\n```sql\n-- User ↔ Profil extins\nCREATE TABLE profiluri (\n    user_id    INT PRIMARY KEY,  -- FK și PK simultan!\n    bio        TEXT,\n    avatar_url VARCHAR(500),\n    FOREIGN KEY (user_id) REFERENCES utilizatori(id) ON DELETE CASCADE\n);\n```\n\n**1:N (One-to-Many)** — cel mai comun: un user poate face mai multe comenzi:\n```sql\nCREATE TABLE comenzi (\n    id       INT PRIMARY KEY AUTO_INCREMENT,\n    user_id  INT NOT NULL,\n    total    DECIMAL(10, 2),\n    FOREIGN KEY (user_id) REFERENCES utilizatori(id) ON DELETE RESTRICT\n);\n```\n\n**M:N (Many-to-Many)** — un student la mai multe cursuri, un curs cu mai mulți studenți:\n```sql\n-- Tabela de legătură (junction table):\nCREATE TABLE inscrieri (\n    student_id INT NOT NULL,\n    curs_id    INT NOT NULL,\n    data_inscriere DATE DEFAULT (CURRENT_DATE),\n    nota       DECIMAL(4, 2),\n    PRIMARY KEY (student_id, curs_id),  -- PK compus!\n    FOREIGN KEY (student_id) REFERENCES studenti(id),\n    FOREIGN KEY (curs_id)    REFERENCES cursuri(id)\n);\n\n-- Query M:N:\nSELECT s.nume, c.titlu, i.nota\nFROM studenti s\nJOIN inscrieri i ON i.student_id = s.id\nJOIN cursuri c   ON c.id = i.curs_id;\n```",
      },
      {
        order: 4,
        title: "Indecși — cheia performanței",
        content: "Un **index** e ca indexul din finalul unei cărți — în loc să citești toată cartea, mergi direct la pagina dorită.\n\n```sql\n-- Fără index: scanare completă (Full Table Scan) — O(n)\n-- Cu index: lookup rapid — O(log n) sau O(1)\n\n-- Creare index:\nCREATE INDEX idx_email ON utilizatori(email);\nCREATE INDEX idx_pret ON produse(pret);\n\n-- Index compus — pentru query-uri cu mai multe condiții:\nCREATE INDEX idx_cat_pret ON produse(categorie, pret);\n-- Util pentru: WHERE categorie = 'X' AND pret < 100\n-- SAU:         WHERE categorie = 'X' ORDER BY pret\n-- NU pentru:  WHERE pret < 100 (fără filtru categorie)\n-- Regula leftmost prefix — folosești de la stânga!\n\n-- Index unic:\nCREATE UNIQUE INDEX idx_slug ON articole(slug);\n\n-- Șterge index:\nDROP INDEX idx_email ON utilizatori;\n\n-- Vizualizează indecșii:\nSHOW INDEX FROM utilizatori;\n```\n\n**Când NU să pui index:**\n```\n- Coloane cu cardinalitate mică (ex: boolean, gen_sex) — puțin util\n- Tabele mici (< 1000 rânduri) — overhead mai mare decât beneficiul\n- Coloane modificate frecvent — fiecare UPDATE/INSERT recalculează indexul\n```\n\n**La interviu:** *„Ce e un index compus și regula leftmost prefix?\"*\nRăspuns: Un index pe (A, B, C) ajută query-urile care filtrează A, sau A+B, sau A+B+C, dar NU B singur sau C singur.",
      },
    ],
    tasks: [
      {
        number: 1,
        name: "CREATE TABLE sintaxă",
        question: "Cum creezi o tabelă `produse` cu id auto-increment și nume obligatoriu?",
        options: [
          "NEW TABLE produse (id AUTO, nume NOT NULL)",
          "CREATE TABLE produse (id INT AUTO_INCREMENT PRIMARY KEY, nume VARCHAR(100) NOT NULL)",
          "MAKE TABLE produse ...",
          "CREATE TABLE produse {id: AUTO, nume: STRING}",
        ],
        answer: "CREATE TABLE produse (id INT AUTO_INCREMENT PRIMARY KEY, nume VARCHAR(100) NOT NULL)",
        explanation: "Sintaxa standard: coloana tip constrângere. AUTO_INCREMENT generează ID unic automat.",
        difficulty: "easy",
      },
      {
        number: 2,
        name: "VARCHAR vs CHAR",
        question: "Când folosești CHAR(n) în loc de VARCHAR(n)?",
        options: [
          "Când textul e lung",
          "Când valorile au întotdeauna aceeași lungime fixă — ex: cod ISO țară CHAR(2), hash bcrypt CHAR(60)",
          "VARCHAR e întotdeauna mai bun",
          "CHAR e mai sigur",
        ],
        answer: "Când valorile au întotdeauna aceeași lungime fixă — ex: cod ISO țară CHAR(2), hash bcrypt CHAR(60)",
        explanation: "CHAR(n) alocă fix n bytes, mai rapid pentru valori cu lungime fixă. VARCHAR(n) e variabil, mai eficient pentru text de lungimi diferite.",
        difficulty: "medium",
      },
      {
        number: 3,
        name: "DECIMAL vs FLOAT",
        question: "De ce folosești DECIMAL(10,2) pentru prețuri și NU FLOAT?",
        options: [
          "DECIMAL e mai rapid",
          "FLOAT are imprecizie — 9.99 poate fi stocat ca 9.98999... Banii necesită precizie exactă",
          "FLOAT nu suportă zecimale",
          "Nu există diferență semnificativă",
        ],
        answer: "FLOAT are imprecizie — 9.99 poate fi stocat ca 9.98999... Banii necesită precizie exactă",
        explanation: "FLOAT folosește reprezentare binară cu erori de rotunjire. DECIMAL(10,2) stochează exact 2 zecimale fără erori — obligatoriu pentru bani.",
        difficulty: "medium",
      },
      {
        number: 4,
        name: "Relație M:N",
        question: "Cum implementezi relația M:N între studenți și cursuri?",
        options: [
          "Coloana array în una din tabele",
          "Tabela de legătură (junction table) cu FK la ambele",
          "Duplicarea datelor în ambele tabele",
          "Nu se poate în SQL relațional",
        ],
        answer: "Tabela de legătură (junction table) cu FK la ambele",
        explanation: "Tabela inscrieri(student_id, curs_id) cu FK la ambele tabele. PK compus pe ambele coloane garantează unicitatea înscrierii.",
        difficulty: "medium",
      },
      {
        number: 5,
        name: "ON DELETE CASCADE",
        question: "Ce face `ON DELETE CASCADE` la o FOREIGN KEY?",
        options: [
          "Interzice ștergerea dacă există FK",
          "Șterge automat rândurile copil când se șterge rândul parinte",
          "Setează FK la NULL",
          "Copiează datele",
        ],
        answer: "Șterge automat rândurile copil când se șterge rândul parinte",
        explanation: "DELETE CASCADE: dacă ștergi un user, se șterg automat toate comenzile lui. RESTRICT (implicit) blochează ștergerea dacă există copii.",
        difficulty: "easy",
      },
      {
        number: 6,
        name: "Index compus",
        question: "Un index pe (categorie, pret) ajută query-ul `WHERE pret < 100` fără filtru pe categorie?",
        options: [
          "Da, orice index ajută",
          "Nu — regula leftmost prefix: indexul (A, B) ajută numai dacă filtrezi și A",
          "Depinde de baza de date",
          "Da, dar mai lent",
        ],
        answer: "Nu — regula leftmost prefix: indexul (A, B) ajută numai dacă filtrezi și A",
        explanation: "Indexul compus (categorie, pret) ajută: WHERE categorie=X, sau WHERE categorie=X AND pret<100. NU ajută WHERE pret<100 singur.",
        difficulty: "hard",
      },
      {
        number: 7,
        name: "ALTER TABLE",
        question: "Cum adaugi coloana `telefon VARCHAR(20)` la o tabelă existentă?",
        options: [
          "UPDATE TABLE utilizatori ADD telefon VARCHAR(20)",
          "ALTER TABLE utilizatori ADD COLUMN telefon VARCHAR(20)",
          "MODIFY TABLE utilizatori ADD telefon VARCHAR(20)",
          "INSERT COLUMN telefon VARCHAR(20) INTO utilizatori",
        ],
        answer: "ALTER TABLE utilizatori ADD COLUMN telefon VARCHAR(20)",
        explanation: "ALTER TABLE modifică structura tabelei. ADD COLUMN adaugă o coloană nouă. COLUMN e opțional în unele dialecte.",
        difficulty: "easy",
      },
      {
        number: 8,
        name: "TIMESTAMP vs DATETIME",
        question: "De ce TIMESTAMP e preferabil DATETIME pentru coloana `creat_la`?",
        options: [
          "TIMESTAMP e mai precis",
          "TIMESTAMP se convertește automat la UTC și e mai eficient (4 vs 8 bytes)",
          "DATETIME nu suportă DEFAULT",
          "Nu există diferență",
        ],
        answer: "TIMESTAMP se convertește automat la UTC și e mai eficient (4 vs 8 bytes)",
        explanation: "TIMESTAMP stochează UTC intern și convertește la timezone-ul clientului. Crucial pentru aplicații globale. DATETIME stochează ora exactă fără timezone.",
        difficulty: "medium",
      },
      {
        number: 9,
        name: "Index cardinalitate",
        question: "De ce indexul pe o coloană boolean (`activ BOOLEAN`) e de obicei inutil?",
        options: [
          "Boolean nu poate fi indexat",
          "Cardinalitate mică — numai 2 valori. Indexul nu elimină suficiente rânduri vs full scan",
          "Nu se poate filtra după boolean",
          "E mai eficient fără index",
        ],
        answer: "Cardinalitate mică — numai 2 valori. Indexul nu elimină suficiente rânduri vs full scan",
        explanation: "Un index eficient trebuie să aibă cardinalitate mare (multe valori distincte). Pe o coloană cu 2 valori, indexul nu ajută — dacă 90% sunt activ=1, scanezi oricum 90%.",
        difficulty: "hard",
      },
      {
        number: 10,
        name: "PK compus M:N",
        question: "De ce e util PRIMARY KEY (student_id, curs_id) în tabela de legătură?",
        options: [
          "E obligatoriu la M:N",
          "Garantează că același student nu se poate înscrie de 2 ori la același curs",
          "Face JOIN-urile mai rapide",
          "Nu are beneficii speciale",
        ],
        answer: "Garantează că același student nu se poate înscrie de 2 ori la același curs",
        explanation: "PK compus = UNIQUE pe combinația ambelor coloane. Previne duplicatele (aceeași pereche student+curs nu poate apărea de 2 ori).",
        difficulty: "medium",
      },
    ],
  },
  {
    slug: "sql-window-functions",
    title: "7. Window Functions și funcții avansate",
    order: 7,
    theory: [
      {
        order: 1,
        title: "Window Functions — agregate fără GROUP BY",
        content: "**Window functions** calculează o valoare pentru fiecare rând bazată pe un set de rânduri (fereastra) — fără a pierde detaliile rândurilor individuale:\n\n```sql\n-- Fără window function:\nSELECT categorie, SUM(vanzari)\nFROM vanzari\nGROUP BY categorie;  -- 1 rând per categorie (detaliile dispar)\n\n-- Cu window function:\nSELECT\n    id,\n    categorie,\n    vanzari,\n    SUM(vanzari) OVER (PARTITION BY categorie) AS total_categorie,\n    vanzari / SUM(vanzari) OVER (PARTITION BY categorie) * 100 AS procent\nFROM vanzari;\n-- Fiecare rând individual RĂMÂNE, dar are și totalul categoriei\n```\n\n**Structura:**\n```sql\nFUNCTIE() OVER (\n    PARTITION BY coloana    -- împarte în grupuri (optional)\n    ORDER BY coloana        -- ordinea în fereastră (optional)\n    ROWS/RANGE ...          -- dimensiunea ferestrei (optional)\n)\n```\n\n**Funcții agregate ca window:**\n```sql\nSELECT\n    id, data, total,\n    SUM(total)   OVER (ORDER BY data)      AS running_total,  -- curent\n    AVG(total)   OVER (PARTITION BY user_id) AS avg_user,\n    COUNT(*)     OVER ()                   AS total_comenzi   -- toate\nFROM comenzi;\n```",
      },
      {
        order: 2,
        title: "ROW_NUMBER, RANK, DENSE_RANK, NTILE",
        content: "**Funcții de ranking** — cele mai cerute la interviuri SQL:\n\n```sql\nSELECT\n    id,\n    nume,\n    pret,\n    ROW_NUMBER()  OVER (ORDER BY pret DESC) AS pozitie,\n    RANK()        OVER (ORDER BY pret DESC) AS rank_,\n    DENSE_RANK()  OVER (ORDER BY pret DESC) AS dense_rank_,\n    NTILE(4)      OVER (ORDER BY pret DESC) AS quartil\nFROM produse;\n\n-- Exemplu cu prețuri: 3500, 1800, 1800, 1200, 800, 120\n-- ROW_NUMBER:  1,    2,    3,    4,    5,   6   — întotdeauna unice\n-- RANK:        1,    2,    2,    4,    5,   6   — gap la egalitate (sare 3)\n-- DENSE_RANK:  1,    2,    2,    3,    4,   5   — fără gap la egalitate\n-- NTILE(4):    1,    1,    2,    2,    3,   4   — împarte în 4 grupe egale\n```\n\n**TOP N per grup — clasic la interviuri:**\n```sql\n-- Primele 3 produse din fiecare categorie după preț:\nWITH ranked AS (\n    SELECT\n        id, nume, pret, categorie,\n        ROW_NUMBER() OVER (PARTITION BY categorie ORDER BY pret DESC) AS rn\n    FROM produse\n)\nSELECT id, nume, pret, categorie\nFROM ranked\nWHERE rn <= 3;  -- primele 3 per categorie\n```\n\n**LAG și LEAD** — accesează rândul anterior/următor:\n```sql\nSELECT\n    data,\n    total,\n    LAG(total)  OVER (ORDER BY data) AS vanzare_anterioara,\n    LEAD(total) OVER (ORDER BY data) AS vanzare_urmatoare,\n    total - LAG(total) OVER (ORDER BY data) AS crestere_fata_de_ieri\nFROM vanzari_zilnice;\n```",
      },
      {
        order: 3,
        title: "CASE, COALESCE, NULLIF, CAST",
        content: "**CASE** — if/else în SQL:\n```sql\n-- CASE simplu:\nSELECT\n    id, pret,\n    CASE\n        WHEN pret < 100  THEN 'ieftin'\n        WHEN pret < 500  THEN 'mediu'\n        WHEN pret < 2000 THEN 'scump'\n        ELSE 'premium'\n    END AS categoria_pret\nFROM produse;\n\n-- CASE ca pivot (tabele pivot dinamice):\nSELECT\n    user_id,\n    SUM(CASE WHEN MONTH(creat_la) = 1 THEN total ELSE 0 END) AS ian,\n    SUM(CASE WHEN MONTH(creat_la) = 2 THEN total ELSE 0 END) AS feb,\n    SUM(CASE WHEN MONTH(creat_la) = 3 THEN total ELSE 0 END) AS mar\nFROM comenzi\nGROUP BY user_id;\n```\n\n**COALESCE și NULLIF:**\n```sql\n-- COALESCE — primul non-NULL:\nSELECT\n    COALESCE(telefon, email, 'Fără contact') AS contact,\n    COALESCE(reducere, 0) AS reducere_sau_zero  -- NULL → 0\nFROM utilizatori;\n\n-- NULLIF — returnează NULL dacă valorile sunt egale:\nSELECT\n    total,\n    discount,\n    total / NULLIF(discount, 0) AS ratio  -- evită împărțirea la zero!\nFROM comenzi;\n\n-- CAST — conversie tip:\nSELECT\n    CAST('2024-01-15' AS DATE)  AS data,\n    CAST(pret AS CHAR)          AS pret_text,\n    CAST('42' AS INT)           AS numar\nFROM produse;\n```",
      },
      {
        order: 4,
        title: "VIEW — tabele virtuale reutilizabile",
        content: "Un **VIEW** e un query salvat cu un nume — se comportă ca o tabelă dar datele sunt calculate la cerere:\n\n```sql\n-- Creează view:\nCREATE VIEW vw_comenzi_cu_useri AS\nSELECT\n    c.id,\n    c.total,\n    c.creat_la,\n    u.email,\n    u.nume AS user_nume\nFROM comenzi c\nJOIN utilizatori u ON u.id = c.user_id;\n\n-- Folosești view ca o tabelă:\nSELECT * FROM vw_comenzi_cu_useri WHERE total > 500;\n\n-- Actualizează view:\nCREATE OR REPLACE VIEW vw_comenzi_cu_useri AS ...;\n\n-- Șterge view:\nDROP VIEW IF EXISTS vw_comenzi_cu_useri;\n```\n\n**Avantajele view-urilor:**\n```\n1. Securitate — expune numai coloanele necesare (ascunde parole, date sensibile)\n2. Simplitate — query-uri complexe devin simple\n3. Consistență — dacă query-ul de bază se schimbă, toate interogările se actualizează\n4. Reutilizare — un singur loc, folosit oriunde\n```\n\n**Materialized View** (PostgreSQL) — datele sunt cache-uite:\n```sql\nCREATE MATERIALIZED VIEW mv_statistici_zilnice AS\nSELECT DATE(creat_la), COUNT(*), SUM(total)\nFROM comenzi\nGROUP BY DATE(creat_la);\n\nREFRESH MATERIALIZED VIEW mv_statistici_zilnice;  -- actualizează\n```",
      },
    ],
    tasks: [
      {
        number: 1,
        name: "OVER() sintaxă",
        question: "Ce face `SUM(total) OVER (PARTITION BY user_id)` față de `SUM(total) GROUP BY user_id`?",
        options: [
          "Sunt identice",
          "OVER() calculează suma per user DAR păstrează toate rândurile individuale — GROUP BY reduce la 1 rând per user",
          "OVER() e mai rapid",
          "GROUP BY poate fi înlocuit întotdeauna cu OVER()",
        ],
        answer: "OVER() calculează suma per user DAR păstrează toate rândurile individuale — GROUP BY reduce la 1 rând per user",
        explanation: "Window functions nu colapsează rândurile. Fiecare rând rămâne, dar primește o valoare calculată pe fereastra lui.",
        difficulty: "medium",
      },
      {
        number: 2,
        name: "RANK vs DENSE_RANK",
        question: "La prețuri 100, 100, 50: ce produce RANK vs DENSE_RANK?",
        options: [
          "RANK: 1,1,2 — DENSE_RANK: 1,1,2",
          "RANK: 1,1,3 — DENSE_RANK: 1,1,2",
          "RANK: 1,2,3 — DENSE_RANK: 1,1,2",
          "Identice",
        ],
        answer: "RANK: 1,1,3 — DENSE_RANK: 1,1,2",
        explanation: "RANK sare numerele după egalitate (1,1,3 — sare rangul 2). DENSE_RANK nu sare (1,1,2). ROW_NUMBER nu are egalitate (1,2,3).",
        difficulty: "hard",
      },
      {
        number: 3,
        name: "LAG",
        question: "Ce face `LAG(total) OVER (ORDER BY data)`?",
        options: [
          "Calculează media",
          "Returnează valoarea `total` din rândul PRECEDENT (cu o poziție în urmă)",
          "Returnează valoarea din primul rând",
          "Sortează după total",
        ],
        answer: "Returnează valoarea `total` din rândul PRECEDENT (cu o poziție în urmă)",
        explanation: "LAG(col, n) returnează valoarea coloanei din n rânduri în urmă (implicit n=1). LEAD face invers — rândul următor.",
        difficulty: "medium",
      },
      {
        number: 4,
        name: "CASE WHEN",
        question: "Ce returnează: `CASE WHEN pret < 100 THEN 'ieftin' WHEN pret < 500 THEN 'mediu' ELSE 'scump' END` pentru pret=200?",
        options: ["ieftin", "mediu", "scump", "NULL"],
        answer: "mediu",
        explanation: "CASE evaluează condițiile în ordine. 200 < 100 = false, 200 < 500 = true → 'mediu'. Se oprește la prima condiție adevărată.",
        difficulty: "easy",
      },
      {
        number: 5,
        name: "COALESCE",
        question: "Ce returnează `COALESCE(NULL, NULL, 'default')`?",
        options: ["NULL", "default", "Eroare", "0"],
        answer: "default",
        explanation: "COALESCE returnează primul argument non-NULL. Primele două sunt NULL, al treilea 'default' → returnează 'default'.",
        difficulty: "easy",
      },
      {
        number: 6,
        name: "NULLIF",
        question: "De ce `total / NULLIF(discount, 0)` e mai sigur decât `total / discount`?",
        options: [
          "NULLIF e mai rapid",
          "NULLIF(discount, 0) returnează NULL când discount=0, evitând împărțirea la zero care aruncă eroare",
          "Nu există diferență",
          "discount poate fi NULL oricum",
        ],
        answer: "NULLIF(discount, 0) returnează NULL când discount=0, evitând împărțirea la zero care aruncă eroare",
        explanation: "Împărțirea la zero = eroare în SQL. NULLIF(val, 0) întoarce NULL dacă val=0, iar total/NULL = NULL (nu eroare).",
        difficulty: "medium",
      },
      {
        number: 7,
        name: "ROW_NUMBER top N",
        question: "Cum obții primele 3 produse din fiecare categorie după preț?",
        options: [
          "SELECT * FROM produse GROUP BY categorie LIMIT 3",
          "CTE cu ROW_NUMBER() OVER (PARTITION BY categorie ORDER BY pret DESC) AS rn, WHERE rn <= 3",
          "SELECT TOP 3 * FROM produse ORDER BY categorie, pret",
          "Nu se poate cu SQL standard",
        ],
        answer: "CTE cu ROW_NUMBER() OVER (PARTITION BY categorie ORDER BY pret DESC) AS rn, WHERE rn <= 3",
        explanation: "PARTITION BY categorie creează numerotare separată per categorie. Filtrezi rn<=3 pentru primele 3 din fiecare.",
        difficulty: "hard",
      },
      {
        number: 8,
        name: "VIEW",
        question: "Ce e un VIEW în SQL?",
        options: [
          "O copie fizică a datelor",
          "Un query SQL salvat cu un nume — se comportă ca o tabelă virtuală",
          "Un index special",
          "O procedură stocată",
        ],
        answer: "Un query SQL salvat cu un nume — se comportă ca o tabelă virtuală",
        explanation: "VIEW nu stochează date — la fiecare SELECT pe view, se execută query-ul de bază. Datele sunt live.",
        difficulty: "easy",
      },
      {
        number: 9,
        name: "Running total",
        question: "Ce calculează `SUM(total) OVER (ORDER BY data)`?",
        options: [
          "Suma totală a tuturor rândurilor",
          "Suma cumulativă (running total) — suma de la primul rând până la rândul curent",
          "Media cumulativă",
          "Suma ultimelor 7 zile",
        ],
        answer: "Suma cumulativă (running total) — suma de la primul rând până la rândul curent",
        explanation: "SUM cu ORDER BY (fără PARTITION) creează o sumă cumulativă. Rândul 3 va conține suma rândurilor 1+2+3.",
        difficulty: "medium",
      },
      {
        number: 10,
        name: "Materialized View",
        question: "Diferența dintre VIEW și MATERIALIZED VIEW?",
        options: [
          "VIEW stochează date, MATERIALIZED nu",
          "VIEW recalculează live la fiecare acces; MATERIALIZED VIEW e cache-uit pe disk",
          "Sunt identice",
          "MATERIALIZED VIEW nu poate fi actualizat",
        ],
        answer: "VIEW recalculează live la fiecare acces; MATERIALIZED VIEW e cache-uit pe disk",
        explanation: "Materialized View stochează datele fizic — extrem de rapid la citire, dar trebuie refreshed manual/periodic. Util pentru rapoarte complexe.",
        difficulty: "hard",
      },
    ],
  },
  {
    slug: "sql-optimizare-interview",
    title: "8. Optimizare + Întrebări clasice de interviu",
    order: 8,
    theory: [
      {
        order: 1,
        title: "EXPLAIN — citirea planului de execuție",
        content: "**EXPLAIN** îți arată CUM baza de date execută query-ul — e primul instrument la optimizare:\n\n```sql\nEXPLAIN SELECT * FROM comenzi WHERE user_id = 5;\n```\n\nColoane importante în output-ul EXPLAIN (MySQL):\n```\ntype:          ALL = full scan (BAD!)\n               ref = index lookup (BINE)\n               const = acces prin PK/UNIQUE (IDEAL)\n\npossible_keys: indexurile disponibile\nkey:           indexul FOLOSIT efectiv (NULL = nu folosește index)\nrows:          estimare câte rânduri scanează (mai mic = mai bun)\nExtra:         Using index, Using filesort, Using temporary\n```\n\n**Exemplu interpretare:**\n```sql\nEXPLAIN SELECT * FROM comenzi\nWHERE user_id = 5\nORDER BY creat_la DESC;\n\n-- Dacă type=ALL → full scan pe toate comenzile — adaugă index!\n-- Dacă key=NULL → nu folosește niciun index\n\n-- Fix:\nCREATE INDEX idx_user_data ON comenzi(user_id, creat_la);\n-- Acum: type=ref, key=idx_user_data — mult mai rapid!\n\n-- EXPLAIN ANALYZE (PostgreSQL) rulează și query-ul:\nEXPLAIN ANALYZE SELECT ...;  -- arată și timpii reali\n```",
      },
      {
        order: 2,
        title: "Normalizare — 1NF, 2NF, 3NF",
        content: "**Normalizarea** elimină redundanța datelor prin împărțirea în tabele mai mici:\n\n**1NF — Prima Formă Normală:**\n```\nReguile:\n✓ Fiecare coloană conține valori atomice (nu liste!)\n✓ Nu există coloane repetitive (culori1, culori2, culori3...)\n✓ Există cheie primară\n\nViolat:\nid | nume  | culori              ← coloane cu liste\n1  | Tricou | roșu,verde,albastru\n\nCorect (1NF):\nid | produs_id | culoare\n1  |     1     | roșu\n2  |     1     | verde\n3  |     1     | albastru\n```\n\n**2NF — A Doua Formă Normală (necesită 1NF):**\n```\nRegula: Fiecare atribut non-cheie depinde de ÎNTREAGA cheie primară\n\nViolat (PK compus: student_id + curs_id):\nstudent_id | curs_id | nota | student_nume  ← student_nume depinde numai de student_id!\n\nCorect (2NF): Mută student_nume în tabela studenti\n```\n\n**3NF — A Treia Formă Normală (necesită 2NF):**\n```\nRegula: Fără dependențe tranzitive (A→B→C → A→C indirect)\n\nViolat:\ncod_postal | oras    | judet  ← judet depinde de oras, nu de cod_postal direct\n\nCorect (3NF): Separă coduri_postale și judete\n```\n\n**Denormalizare** — uneori intenționată pentru performanță (tabele de raportare, data warehouses).",
      },
      {
        order: 3,
        title: "Probleme clasice de interviu SQL",
        content: "**1. Al doilea cel mai mare salariu:**\n```sql\n-- Varianta cu LIMIT OFFSET:\nSELECT DISTINCT salariu\nFROM angajati\nORDER BY salariu DESC\nLIMIT 1 OFFSET 1;\n\n-- Varianta cu subquery (funcționează pe orice DB):\nSELECT MAX(salariu) AS al_doilea_salariu\nFROM angajati\nWHERE salariu < (SELECT MAX(salariu) FROM angajati);\n\n-- Varianta cu DENSE_RANK:\nWITH ranked AS (\n    SELECT salariu, DENSE_RANK() OVER (ORDER BY salariu DESC) AS rk\n    FROM angajati\n)\nSELECT salariu FROM ranked WHERE rk = 2;\n```\n\n**2. Găsire duplicate:**\n```sql\n-- Email-uri duplicate:\nSELECT email, COUNT(*) AS aparitii\nFROM utilizatori\nGROUP BY email\nHAVING COUNT(*) > 1;\n\n-- Șterge duplicate, păstrează cel mai nou:\nDELETE FROM utilizatori\nWHERE id NOT IN (\n    SELECT MAX(id)\n    FROM utilizatori\n    GROUP BY email\n);\n```\n\n**3. Angajați cu salar > media departamentului:**\n```sql\nSELECT a.id, a.nume, a.salar, a.dept_id\nFROM angajati a\nWHERE a.salar > (\n    SELECT AVG(a2.salar)\n    FROM angajati a2\n    WHERE a2.dept_id = a.dept_id\n);\n```",
      },
      {
        order: 4,
        title: "Optimizări practice și anti-pattern-uri",
        content: "**Anti-pattern-uri comune care fac query-urile lente:**\n\n```sql\n-- 1. SELECT * — transferă date inutile:\n-- Slab:\nSELECT * FROM utilizatori WHERE id = 5;\n-- Bine:\nSELECT id, email, nume FROM utilizatori WHERE id = 5;\n\n-- 2. Funcție pe coloana indexată în WHERE — dezactivează indexul!:\n-- Slab (indexul pe creat_la e ignorat):\nSELECT * FROM comenzi WHERE YEAR(creat_la) = 2024;\n-- Bine:\nSELECT * FROM comenzi\nWHERE creat_la >= '2024-01-01' AND creat_la < '2025-01-01';\n\n-- 3. OR pe coloane diferite — probleme cu indexuri:\n-- Slab:\nSELECT * FROM t WHERE col_a = 1 OR col_b = 2;\n-- Mai bine:\nSELECT * FROM t WHERE col_a = 1\nUNION ALL\nSELECT * FROM t WHERE col_b = 2 AND col_a != 1;\n\n-- 4. Subquery corelat în SELECT — N+1 problem:\n-- Slab (se execută o dată per user!):\nSELECT u.id,\n    (SELECT COUNT(*) FROM comenzi c WHERE c.user_id = u.id) AS nr\nFROM utilizatori u;\n\n-- Bine (un singur JOIN):\nSELECT u.id, COUNT(c.id) AS nr\nFROM utilizatori u\nLEFT JOIN comenzi c ON c.user_id = u.id\nGROUP BY u.id;\n```\n\n**Checklist optimizare:**\n```\n1. Rulează EXPLAIN — identifică full scans\n2. Adaugă indexuri pe coloanele din WHERE, JOIN ON, ORDER BY\n3. Evită funcții pe coloane indexate în WHERE\n4. Folosește LIMIT când nu ai nevoie de toate datele\n5. Evită SELECT * în producție\n6. Înlocuiește subquery-uri corelate cu JOIN-uri când posibil\n```",
      },
    ],
    tasks: [
      {
        number: 1,
        name: "EXPLAIN type ALL",
        question: "Ce înseamnă `type: ALL` în output-ul EXPLAIN?",
        options: [
          "Query-ul e optim",
          "Baza de date face un full table scan — citește toate rândurile",
          "Se folosesc toate indexurile",
          "Toate condițiile sunt satisfăcute",
        ],
        answer: "Baza de date face un full table scan — citește toate rândurile",
        explanation: "type=ALL = cel mai slab. Baza de date scanează fiecare rând. Fix: adaugă index pe coloana filtrată.",
        difficulty: "medium",
      },
      {
        number: 2,
        name: "Al doilea salariu",
        question: "Cum găsești al 2-lea cel mai mare salariu distinct?",
        options: [
          "SELECT MAX(salariu) - 1 FROM angajati",
          "SELECT MAX(salariu) FROM angajati WHERE salariu < (SELECT MAX(salariu) FROM angajati)",
          "SELECT salariu FROM angajati ORDER BY salariu DESC LIMIT 1, 1",
          "Ambele variante B și C sunt corecte",
        ],
        answer: "Ambele variante B și C sunt corecte",
        explanation: "Subquery cu MAX și LIMIT OFFSET ambele rezolvă corect. La interviu, arată ambele variante și explică DENSE_RANK pentru n-lea salariu.",
        difficulty: "hard",
      },
      {
        number: 3,
        name: "Funcție pe index",
        question: "De ce `WHERE YEAR(creat_la) = 2024` e mai lent decât `WHERE creat_la >= '2024-01-01'`?",
        options: [
          "YEAR() e o funcție lentă",
          "Funcția pe coloana indexată dezactivează indexul — forțează full scan",
          "Nu există diferență",
          "YEAR() nu funcționează în toate DB-urile",
        ],
        answer: "Funcția pe coloana indexată dezactivează indexul — forțează full scan",
        explanation: "Când aplici o funcție pe o coloană indexată în WHERE, baza de date nu poate folosi indexul. Rescrie cu interval explicit.",
        difficulty: "hard",
      },
      {
        number: 4,
        name: "1NF",
        question: "Care tabelă respectă Prima Formă Normală (1NF)?",
        options: [
          "user(id, email, telefoane_multiple)",
          "user(id, email, tel1, tel2, tel3)",
          "user(id, email) + telefoane(id, user_id, numar)",
          "Ambele A și B respectă 1NF",
        ],
        answer: "user(id, email) + telefoane(id, user_id, numar)",
        explanation: "1NF cere valori atomice — nu liste și nu coloane repetitive. Telefoanele multiple se separă într-o tabelă separată.",
        difficulty: "medium",
      },
      {
        number: 5,
        name: "Găsire duplicate",
        question: "Cum găsești emailurile care apar de mai mult de o dată?",
        options: [
          "SELECT * FROM u WHERE email DUPLICATE",
          "SELECT email, COUNT(*) FROM u GROUP BY email HAVING COUNT(*) > 1",
          "SELECT DISTINCT email FROM u",
          "SELECT email FROM u WHERE id != id",
        ],
        answer: "SELECT email, COUNT(*) FROM u GROUP BY email HAVING COUNT(*) > 1",
        explanation: "GROUP BY email + HAVING COUNT(*) > 1 identifică valorile cu apariții multiple.",
        difficulty: "medium",
      },
      {
        number: 6,
        name: "N+1 problem",
        question: "De ce subquery corelat în SELECT e mai lent decât un JOIN?",
        options: [
          "Subquery-ul nu poate folosi indexuri",
          "Subquery-ul se execută o dată per rând exterior (N execuții) vs JOIN care procesează totul o dată",
          "JOIN e întotdeauna mai lent",
          "Nu există diferență de performanță",
        ],
        answer: "Subquery-ul se execută o dată per rând exterior (N execuții) vs JOIN care procesează totul o dată",
        explanation: "Cu 10.000 useri: subquery corelat în SELECT = 10.000 query-uri separate. JOIN = 1 singur query. Asta e problema N+1.",
        difficulty: "hard",
      },
      {
        number: 7,
        name: "3NF",
        question: "Care dependență violează 3NF?",
        options: [
          "id → email",
          "cod_postal → oras → judet (dependență tranzitivă: cod_postal → judet prin oras)",
          "student_id → nota",
          "produs_id → pret",
        ],
        answer: "cod_postal → oras → judet (dependență tranzitivă: cod_postal → judet prin oras)",
        explanation: "3NF interzice dependențele tranzitive. judet depinde de oras, nu direct de cod_postal → separă într-o tabelă orase(id, judet).",
        difficulty: "hard",
      },
      {
        number: 8,
        name: "Index pe ORDER BY",
        question: "Dacă ai frecvent `ORDER BY creat_la DESC`, ce index ajută?",
        options: [
          "Index pe id",
          "Index pe creat_la",
          "Index compus pe (user_id, creat_la) dacă filtrezi și user_id",
          "Nu ajută niciun index",
        ],
        answer: "Index compus pe (user_id, creat_la) dacă filtrezi și user_id",
        explanation: "Dacă query-ul e WHERE user_id = X ORDER BY creat_la, indexul (user_id, creat_la) ajută ambele operații. Ordinea din index trebuie să corespundă cu ordinea din query.",
        difficulty: "hard",
      },
      {
        number: 9,
        name: "UNION vs UNION ALL",
        question: "Diferența dintre UNION și UNION ALL?",
        options: [
          "Identice",
          "UNION elimină duplicatele (mai lent), UNION ALL le păstrează (mai rapid)",
          "UNION ALL funcționează pe mai multe tabele",
          "UNION e pentru SELECT, UNION ALL pentru INSERT",
        ],
        answer: "UNION elimină duplicatele (mai lent), UNION ALL le păstrează (mai rapid)",
        explanation: "UNION face DISTINCT implicit — overhead suplimentar. UNION ALL păstrează tot. Folosește UNION ALL când știi că nu ai duplicate sau nu contează.",
        difficulty: "medium",
      },
      {
        number: 10,
        name: "Angajat > media dept",
        question: "Cum găsești angajații cu salar mai mare decât media departamentului lor?",
        options: [
          "WHERE salar > (SELECT AVG(salar) FROM angajati)",
          "WHERE salar > (SELECT AVG(salar) FROM angajati WHERE dept_id = a.dept_id)",
          "HAVING salar > AVG(salar) GROUP BY dept_id",
          "JOIN pe AVG(salar) GROUP BY dept_id WHERE salar > medie",
        ],
        answer: "WHERE salar > (SELECT AVG(salar) FROM angajati WHERE dept_id = a.dept_id)",
        explanation: "Subquery corelat: pentru fiecare angajat, calculează media departamentului LUI. Alternativa e JOIN cu CTE care calculează media per dept.",
        difficulty: "hard",
      },
    ],
  },
];

module.exports = { sqlLessons };
