// Lecții suplimentare C — lecțiile 12-25

const cMore = [
  {
    slug: "c-functii-pointer",
    title: "12. Funcții — pointeri la funcții",
    order: 12,
    theory: [
      { order: 1, title: "Pointeri la funcții — sintaxă", content: "```c\n// Un pointer la funcție stochează adresa unei funcții:\nint aduna(int a, int b) { return a + b; }\nint scade(int a, int b) { return a - b; }\n\nint main() {\n    // Sintaxa: tip_return (*nume)(param1, param2)\n    int (*operatie)(int, int);\n\n    operatie = aduna;\n    printf(\"%d\\n\", operatie(5, 3)); // 8\n\n    operatie = scade;\n    printf(\"%d\\n\", operatie(5, 3)); // 2\n\n    return 0;\n}\n```" },
      { order: 2, title: "Array de pointeri la funcții — meniu", content: "```c\n#include <stdio.h>\n\nvoid optiune1() { printf(\"Ai ales optiunea 1\\n\"); }\nvoid optiune2() { printf(\"Ai ales optiunea 2\\n\"); }\nvoid optiune3() { printf(\"Ai ales optiunea 3\\n\"); }\n\nint main() {\n    void (*meniu[3])() = { optiune1, optiune2, optiune3 };\n\n    int alegere;\n    printf(\"Alege (1-3): \");\n    scanf(\"%d\", &alegere);\n\n    if (alegere >= 1 && alegere <= 3) {\n        meniu[alegere - 1](); // apel prin pointer\n    }\n\n    return 0;\n}\n```" },
      { order: 3, title: "qsort — funcție de comparare ca parametru", content: "```c\n#include <stdio.h>\n#include <stdlib.h>\n\nint compara(const void *a, const void *b) {\n    return (*(int*)a - *(int*)b); // crescator\n    // return (*(int*)b - *(int*)a); // descrescator\n}\n\nint main() {\n    int arr[] = {5, 2, 8, 1, 9, 3};\n    int n = 6;\n\n    qsort(arr, n, sizeof(int), compara);\n\n    for (int i = 0; i < n; i++)\n        printf(\"%d \", arr[i]); // 1 2 3 5 8 9\n\n    return 0;\n}\n```\n\nqsort din `<stdlib.h>` sortează orice array. Primește funcția de comparare ca pointer." },
      { order: 4, title: "typedef pentru pointer la funcție", content: "```c\n// typedef simplifică sintaxa:\ntypedef int (*Operatie)(int, int);\n\nint inmulteste(int a, int b) { return a * b; }\nint impart(int a, int b) { return b != 0 ? a / b : 0; }\n\nvoid aplica(int a, int b, Operatie op) {\n    printf(\"Rezultat: %d\\n\", op(a, b));\n}\n\nint main() {\n    aplica(10, 5, inmulteste); // 50\n    aplica(10, 5, impart);    // 2\n\n    Operatie ops[] = { inmulteste, impart };\n    for (int i = 0; i < 2; i++)\n        aplica(20, 4, ops[i]);\n\n    return 0;\n}\n```" },
    ],
    tasks: [
      { number: 1, name: "Sintaxa pointer functie", question: "Care e sintaxa corectă pentru un pointer la funcție care primește int,int și returnează int?", options: ["int *func(int, int)", "int (*func)(int, int)", "int *(*func)(int, int)", "func *int(int, int)"], answer: "int (*func)(int, int)", explanation: "Parantezele în jurul *func sunt obligatorii! Fără ele, int *func(int,int) declară o funcție care returnează int*.", difficulty: "medium" },
      { number: 2, name: "qsort comparator", question: "Ce returnează funcția de comparare pentru qsort dacă a < b?", options: ["1", "-1 sau negativ", "0", "true"], answer: "-1 sau negativ", explanation: "Comparatorul pentru qsort: negativ dacă a < b, 0 dacă egale, pozitiv dacă a > b.", difficulty: "medium" },
      { number: 3, name: "Apel prin pointer", question: "Dacă ptr = aduna, cum apelezi funcția prin pointer?", options: ["ptr->aduna(5,3)", "ptr(5, 3)", "*ptr(5, 3)", "call ptr(5, 3)"], answer: "ptr(5, 3)", explanation: "Un pointer la funcție se apelează direct ca o funcție normală: ptr(arg1, arg2).", difficulty: "easy" },
      { number: 4, name: "typedef scop", question: "De ce folosești typedef pentru pointer la funcție?", options: ["Performanță mai mare", "Simplifică sintaxa complexă și mărește lizibilitatea", "Obligatoriu în C99", "Evită erori de linking"], answer: "Simplifică sintaxa complexă și mărește lizibilitatea", explanation: "typedef Operatie poate fi folosit ca tip simplu în loc de int (*)(int,int) repetat.", difficulty: "easy" },
    ],
  },
  {
    slug: "c-struct-avansat",
    title: "13. Structuri avansate — nested, typedef",
    order: 13,
    theory: [
      { order: 1, title: "Structuri imbricate (nested structs)", content: "```c\n#include <stdio.h>\n\ntypedef struct {\n    int zi, luna, an;\n} Data;\n\ntypedef struct {\n    char nume[50];\n    int varsta;\n    Data dataNastere; // struct în struct\n} Persoana;\n\nint main() {\n    Persoana p = {\n        .nume = \"Ana\",\n        .varsta = 25,\n        .dataNastere = { .zi = 15, .luna = 3, .an = 2000 }\n    };\n\n    printf(\"%s, %d/%d/%d\\n\",\n        p.nume,\n        p.dataNastere.zi,\n        p.dataNastere.luna,\n        p.dataNastere.an);\n\n    return 0;\n}\n```" },
      { order: 2, title: "Pointer la structuri — operatorul ->", content: "```c\ntypedef struct {\n    char marca[30];\n    int an;\n    float pret;\n} Masina;\n\nvoid afiseaza(const Masina *m) { // pointer la struct\n    printf(\"%s (%d) - %.2f RON\\n\",\n           m->marca, m->an, m->pret);\n    // m->x este echivalent cu (*m).x\n}\n\nvoid scumpeste(Masina *m, float procent) {\n    m->pret *= (1 + procent / 100); // modifică original\n}\n\nint main() {\n    Masina mea = { \"BMW\", 2022, 50000 };\n    afiseaza(&mea);\n    scumpeste(&mea, 10);\n    afiseaza(&mea);\n    return 0;\n}\n```" },
      { order: 3, title: "Array de structuri", content: "```c\n#include <stdio.h>\n#include <string.h>\n\ntypedef struct {\n    char nume[50];\n    float nota;\n} Student;\n\nvoid sorteaza_dupa_nota(Student *s, int n) {\n    for (int i = 0; i < n-1; i++)\n        for (int j = i+1; j < n; j++)\n            if (s[i].nota < s[j].nota) {\n                Student tmp = s[i];\n                s[i] = s[j];\n                s[j] = tmp;\n            }\n}\n\nint main() {\n    Student cls[] = {\n        {\"Ana\", 9.5},\n        {\"Ion\", 7.0},\n        {\"Maria\", 10.0},\n    };\n    int n = 3;\n    sorteaza_dupa_nota(cls, n);\n    for (int i = 0; i < n; i++)\n        printf(\"%d. %s: %.1f\\n\", i+1, cls[i].nume, cls[i].nota);\n    return 0;\n}\n```" },
      { order: 4, title: "Structuri auto-referențiale (linked list preview)", content: "```c\n// Structura care conține pointer la ea însăși:\ntypedef struct Nod {\n    int valoare;\n    struct Nod *urmator; // NU poți folosi typedef Nod aici\n} Nod;\n\nNod* creeaza_nod(int val) {\n    Nod *n = (Nod*)malloc(sizeof(Nod));\n    n->valoare = val;\n    n->urmator = NULL;\n    return n;\n}\n\nint main() {\n    Nod *n1 = creeaza_nod(10);\n    Nod *n2 = creeaza_nod(20);\n    n1->urmator = n2;\n\n    printf(\"%d -> %d\\n\", n1->valoare, n1->urmator->valoare);\n\n    free(n2);\n    free(n1);\n    return 0;\n}\n```" },
    ],
    tasks: [
      { number: 1, name: "Operator ->", question: "Cum accesezi câmpul 'pret' printr-un pointer Masina *m?", options: ["m.pret", "m->pret", "*m.pret", "m[pret]"], answer: "m->pret", explanation: "Operatorul -> accesează câmpul unui struct prin pointer. Echivalent cu (*m).pret.", difficulty: "easy" },
      { number: 2, name: "Typedef struct", question: "Ce avantaj oferă typedef struct {} Masina;?", options: ["Mai rapid", "Poți scrie Masina m; în loc de struct Masina m;", "Mai puțin memorie", "Acces mai rapid"], answer: "Poți scrie Masina m; în loc de struct Masina m;", explanation: "typedef creează un alias de tip — elimini cuvântul struct din declarații.", difficulty: "easy" },
      { number: 3, name: "Struct in struct", question: "Cum accesezi ziua din dataNastere a unei Persoana p?", options: ["p.zi", "p.dataNastere->zi", "p.dataNastere.zi", "p->dataNastere.zi"], answer: "p.dataNastere.zi", explanation: "p e o structură (nu pointer), deci . pentru ambele nivele: p.dataNastere.zi.", difficulty: "medium" },
      { number: 4, name: "Struct auto-referentiala", question: "De ce struct Nod *urmator folosește struct Nod și nu Nod?", options: ["E greșit", "typedef Nod nu e disponibil în corpul propriei structuri", "E mai rapid", "E convenție"], answer: "typedef Nod nu e disponibil în corpul propriei structuri", explanation: "typedef e definit după structură. În interiorul structurii, trebuie să folosești numele complet struct Nod.", difficulty: "hard" },
    ],
  },
  {
    slug: "c-file-io",
    title: "14. Fișiere — File I/O",
    order: 14,
    theory: [
      { order: 1, title: "Deschidere și închidere fișiere", content: "```c\n#include <stdio.h>\n\nint main() {\n    // Moduri de deschidere:\n    // \"r\"  — citire (fișierul trebuie să existe)\n    // \"w\"  — scriere (creare nouă sau suprascrie)\n    // \"a\"  — append (adaugă la final)\n    // \"rb\", \"wb\" — binar\n    // \"r+\" — citire+scriere\n\n    FILE *f = fopen(\"date.txt\", \"w\");\n    if (f == NULL) {\n        perror(\"Eroare la deschidere\");\n        return 1;\n    }\n\n    fprintf(f, \"Salut, fișier!\\n\");\n    fprintf(f, \"Linia 2\\n\");\n\n    fclose(f); // OBLIGATORIU!\n    return 0;\n}\n```" },
      { order: 2, title: "Citire din fișier", content: "```c\n#include <stdio.h>\n\nint main() {\n    FILE *f = fopen(\"date.txt\", \"r\");\n    if (!f) { perror(\"Nu găsesc fișierul\"); return 1; }\n\n    // fscanf — format:\n    int nr; char cuvant[50];\n    fscanf(f, \"%d %s\", &nr, cuvant);\n\n    // fgets — linie cu linie (mai sigur):\n    char linie[256];\n    while (fgets(linie, sizeof(linie), f) != NULL) {\n        printf(\"%s\", linie); // include \\n\n    }\n\n    // fgetc — caracter cu caracter:\n    int c;\n    rewind(f); // reset la început\n    while ((c = fgetc(f)) != EOF) {\n        putchar(c);\n    }\n\n    fclose(f);\n    return 0;\n}\n```" },
      { order: 3, title: "Fișiere binare — fread/fwrite", content: "```c\n#include <stdio.h>\n\ntypedef struct {\n    char nume[50];\n    int varsta;\n    float nota;\n} Student;\n\nint main() {\n    Student s1 = {\"Ana\", 20, 9.5};\n\n    // Scriere binară:\n    FILE *f = fopen(\"studenti.bin\", \"wb\");\n    fwrite(&s1, sizeof(Student), 1, f);\n    fclose(f);\n\n    // Citire binară:\n    Student s2;\n    f = fopen(\"studenti.bin\", \"rb\");\n    fread(&s2, sizeof(Student), 1, f);\n    fclose(f);\n\n    printf(\"%s, %d, %.1f\\n\", s2.nume, s2.varsta, s2.nota);\n    return 0;\n}\n```\n\nFișierele binare sunt mai rapide și mai compacte pentru date structurate." },
      { order: 4, title: "fseek, ftell — poziționare", content: "```c\n#include <stdio.h>\n\nint main() {\n    FILE *f = fopen(\"date.bin\", \"rb\");\n\n    // ftell — poziția curentă:\n    long pos = ftell(f); // 0 la început\n\n    // fseek(f, offset, origin):\n    // SEEK_SET — față de început\n    // SEEK_CUR — față de poziția curentă\n    // SEEK_END — față de sfârșit\n\n    fseek(f, 0, SEEK_END);\n    long size = ftell(f); // dimensiunea fișierului\n    printf(\"Dimensiune: %ld bytes\\n\", size);\n\n    fseek(f, 0, SEEK_SET); // rewind manual\n    rewind(f); // echivalent cu fseek(f, 0, SEEK_SET)\n\n    fclose(f);\n    return 0;\n}\n```" },
    ],
    tasks: [
      { number: 1, name: "fopen moduri", question: "Care mod deschide fișierul pentru ADĂUGARE la final?", options: ["\"w\"", "\"r\"", "\"a\"", "\"rw\""], answer: "\"a\"", explanation: "Modul \"a\" (append) deschide fișierul și scrie la final. Nu suprascrie conținutul existent.", difficulty: "easy" },
      { number: 2, name: "fclose obligatoriu", question: "De ce e fclose() obligatoriu?", options: ["Altfel fișierul e corupt", "Flushează buffer-ul și eliberează resursele sistemului", "E opțional", "Previne memory leak doar"], answer: "Flushează buffer-ul și eliberează resursele sistemului", explanation: "fclose() flushează buffer-ul de scriere (altfel date pot fi pierdute) și eliberează FILE* alocate de OS.", difficulty: "medium" },
      { number: 3, name: "NULL check", question: "Cum verifici că fopen a reușit?", options: ["if (f > 0)", "if (f != NULL)", "if (!errno)", "if (f == OK)"], answer: "if (f != NULL)", explanation: "fopen returnează NULL la eșec. Verifici mereu înainte de a folosi FILE*.", difficulty: "easy" },
      { number: 4, name: "fread/fwrite avantaj", question: "De ce sunt fread/fwrite mai bune pentru structuri față de fprintf?", options: ["Sunt mai ușor de citit", "Stochează exact bytes-urile structurii — rapid și precis", "Suportă text formatat", "Sunt cross-platform"], answer: "Stochează exact bytes-urile structurii — rapid și precis", explanation: "fread/fwrite copiază memorie brută — perfect pentru structuri. Nu conversia text↔număr.", difficulty: "medium" },
    ],
  },
  {
    slug: "c-linked-list",
    title: "15. Liste înlănțuite (Linked Lists)",
    order: 15,
    theory: [
      { order: 1, title: "Structura unui nod", content: "```c\n#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct Nod {\n    int data;\n    struct Nod *next;\n} Nod;\n\nNod* nod_nou(int val) {\n    Nod *n = (Nod*)malloc(sizeof(Nod));\n    if (!n) { perror(\"malloc\"); exit(1); }\n    n->data = val;\n    n->next = NULL;\n    return n;\n}\n\nvoid afiseaza(Nod *cap) {\n    while (cap) {\n        printf(\"%d -> \", cap->data);\n        cap = cap->next;\n    }\n    printf(\"NULL\\n\");\n}\n```" },
      { order: 2, title: "Inserare la început și la final", content: "```c\nNod* insereaza_inceput(Nod *cap, int val) {\n    Nod *n = nod_nou(val);\n    n->next = cap;\n    return n; // noul cap\n}\n\nvoid insereaza_final(Nod **cap, int val) {\n    Nod *n = nod_nou(val);\n    if (*cap == NULL) {\n        *cap = n;\n        return;\n    }\n    Nod *curent = *cap;\n    while (curent->next) curent = curent->next;\n    curent->next = n;\n}\n\nint main() {\n    Nod *lista = NULL;\n    insereaza_final(&lista, 1);\n    insereaza_final(&lista, 2);\n    lista = insereaza_inceput(lista, 0);\n    afiseaza(lista); // 0 -> 1 -> 2 -> NULL\n    return 0;\n}\n```" },
      { order: 3, title: "Ștergere nod", content: "```c\nNod* sterge_val(Nod *cap, int val) {\n    if (!cap) return NULL;\n\n    // Șterg primul nod:\n    if (cap->data == val) {\n        Nod *tmp = cap->next;\n        free(cap);\n        return tmp;\n    }\n\n    // Caut în restul listei:\n    Nod *curent = cap;\n    while (curent->next && curent->next->data != val)\n        curent = curent->next;\n\n    if (curent->next) {\n        Nod *tmp = curent->next;\n        curent->next = tmp->next;\n        free(tmp);\n    }\n    return cap;\n}\n\nvoid elibereaza(Nod *cap) {\n    while (cap) {\n        Nod *tmp = cap;\n        cap = cap->next;\n        free(tmp);\n    }\n}\n```" },
      { order: 4, title: "Avantaje și dezavantaje vs array", content: "**Linked List:**\n✅ Inserare/ștergere O(1) la capăt (cu referință)\n✅ Dimensiune dinamică — crește/scade oricând\n❌ Accesul la element i: O(n) — traversare\n❌ Cache miss — nodurile sunt răspândite în memorie\n❌ Memorie suplimentară pentru pointer next\n\n**Array:**\n✅ Acces direct la index: O(1)\n✅ Cache-friendly — memorie contiguă\n❌ Dimensiune fixă (array static) sau realocare costisitoare\n❌ Inserare/ștergere la mijloc: O(n) shiftare\n\n```c\n// Când să folosești:\n// Array: acces aleator frecvent, dimensiune cunoscută\n// Lista: inserări/ștergeri frecvente, dimensiune necunoscută\n```" },
    ],
    tasks: [
      { number: 1, name: "Capul listei", question: "Cum verifici că o listă e goală?", options: ["lista.size == 0", "lista == NULL", "lista->next == NULL", "isEmpty(lista)"], answer: "lista == NULL", explanation: "O lista goală e reprezentată prin NULL — pointer-ul cap este NULL.", difficulty: "easy" },
      { number: 2, name: "Acces element", question: "Care e complexitatea accesului la elementul i dintr-o linked list?", options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], answer: "O(n)", explanation: "Trebuie traversat de la cap până la nodul i — O(n) în cel mai rău caz.", difficulty: "medium" },
      { number: 3, name: "free obligatoriu", question: "De ce trebuie să free() nodurile la ștergere?", options: ["E opțional", "Previne memory leak — memory alocată cu malloc trebuie eliberată", "Altfel lista se corupe", "E stilistic"], answer: "Previne memory leak — memory alocată cu malloc trebuie eliberată", explanation: "malloc alocă din heap. Dacă nu eliberezi cu free, memoria rămâne ocupată până la terminarea programului.", difficulty: "medium" },
      { number: 4, name: "Pointer la pointer", question: "De ce insereaza_final primește Nod **cap (dublu pointer)?", options: ["E greșit", "Ca să poată modifica pointerul cap din exterior (schimba unde pointează)", "Performanță", "E opțional"], answer: "Ca să poată modifica pointerul cap din exterior (schimba unde pointează)", explanation: "Nod **cap permite modificarea lui *cap (pointer-ul cap din funcția apelantă). Un singur * ar modifica doar copia locală.", difficulty: "hard" },
    ],
  },
  {
    slug: "c-stiva-coada",
    title: "16. Stivă și Coadă (Stack și Queue)",
    order: 16,
    theory: [
      { order: 1, title: "Stivă cu array — LIFO", content: "```c\n#include <stdio.h>\n#define MAX 100\n\ntypedef struct {\n    int date[MAX];\n    int top;\n} Stiva;\n\nvoid init(Stiva *s) { s->top = -1; }\nint goala(Stiva *s) { return s->top == -1; }\nint plina(Stiva *s) { return s->top == MAX - 1; }\n\nvoid push(Stiva *s, int val) {\n    if (plina(s)) { printf(\"Stack overflow!\\n\"); return; }\n    s->date[++s->top] = val;\n}\n\nint pop(Stiva *s) {\n    if (goala(s)) { printf(\"Stack underflow!\\n\"); return -1; }\n    return s->date[s->top--];\n}\n\nint peek(Stiva *s) {\n    return goala(s) ? -1 : s->date[s->top];\n}\n\nint main() {\n    Stiva s;\n    init(&s);\n    push(&s, 1); push(&s, 2); push(&s, 3);\n    while (!goala(&s)) printf(\"%d \", pop(&s)); // 3 2 1\n    return 0;\n}\n```" },
      { order: 2, title: "Coadă cu array circular — FIFO", content: "```c\n#define MAX 5\n\ntypedef struct {\n    int date[MAX];\n    int fata, spate, nr;\n} Coada;\n\nvoid initC(Coada *q) { q->fata = q->spate = q->nr = 0; }\nint goalaC(Coada *q) { return q->nr == 0; }\nint plina_C(Coada *q) { return q->nr == MAX; }\n\nvoid enqueue(Coada *q, int val) {\n    if (plina_C(q)) return;\n    q->date[q->spate] = val;\n    q->spate = (q->spate + 1) % MAX; // circular!\n    q->nr++;\n}\n\nint dequeue(Coada *q) {\n    if (goalaC(q)) return -1;\n    int val = q->date[q->fata];\n    q->fata = (q->fata + 1) % MAX; // circular!\n    q->nr--;\n    return val;\n}\n```" },
      { order: 3, title: "Aplicații practice", content: "**Stivă (LIFO — Last In First Out):**\n• Undo/Redo în editori\n• Call stack în programe (recursivitate)\n• Evaluare expresii aritmetice\n• Parcurgere DFS (grafuri)\n• Verificare paranteze balansate: `(){}[]`\n\n**Coadă (FIFO — First In First Out):**\n• Scheduling (procese în OS)\n• Bufferele de mesaje\n• Parcurgere BFS (grafuri)\n• Print queue, task queue\n\n```c\n// Verificare paranteze cu stivă:\nint verifica(char *expr) {\n    Stiva s; init(&s);\n    for (int i = 0; expr[i]; i++) {\n        if (expr[i] == '(' || expr[i] == '[' || expr[i] == '{')\n            push(&s, expr[i]);\n        else if (expr[i] == ')' || expr[i] == ']' || expr[i] == '}') {\n            if (goala(&s)) return 0;\n            pop(&s);\n        }\n    }\n    return goala(&s);\n}\n```" },
      { order: 4, title: "Stivă și coadă cu linked list", content: "```c\n// Stivă cu linked list — fără limită de mărime:\ntypedef struct Nod { int val; struct Nod *next; } Nod;\ntypedef struct { Nod *top; } Stiva2;\n\nvoid push2(Stiva2 *s, int val) {\n    Nod *n = malloc(sizeof(Nod));\n    n->val = val;\n    n->next = s->top;\n    s->top = n;\n}\n\nint pop2(Stiva2 *s) {\n    if (!s->top) return -1;\n    int val = s->top->val;\n    Nod *tmp = s->top;\n    s->top = s->top->next;\n    free(tmp);\n    return val;\n}\n```" },
    ],
    tasks: [
      { number: 1, name: "LIFO", question: "Care e ordinea de extragere dintr-o stivă: push(1), push(2), push(3)?", options: ["1, 2, 3", "3, 2, 1", "2, 1, 3", "Aleatoriu"], answer: "3, 2, 1", explanation: "LIFO (Last In First Out) — ultimul intrat, primul ieșit. push(3) ultimul → pop() returnează 3 primul.", difficulty: "easy" },
      { number: 2, name: "FIFO", question: "Care e ordinea de extragere dintr-o coadă: enqueue(1), enqueue(2), enqueue(3)?", options: ["3, 2, 1", "1, 2, 3", "2, 1, 3", "Aleatoriu"], answer: "1, 2, 3", explanation: "FIFO (First In First Out) — primul intrat, primul ieșit. Ca o coadă la magazin.", difficulty: "easy" },
      { number: 3, name: "Circular array", question: "De ce folosim array circular pentru coadă?", options: ["E mai simplu", "Evită mutarea elementelor și reutilizează spațiul eliberat", "E mai rapid la push", "Nu există alt mod"], answer: "Evită mutarea elementelor și reutilizează spațiul eliberat", explanation: "Array circular cu modulo (%) reutilizează spațiul din față după dequeue, fără shiftare.", difficulty: "medium" },
      { number: 4, name: "Aplicatie stiva", question: "Care dintre acestea e o aplicație clasică a stivei?", options: ["Scheduling procese", "Undo/Redo în editoare", "Print queue", "BFS în grafuri"], answer: "Undo/Redo în editoare", explanation: "Undo/Redo folosesc o stivă — ultima acțiune e pe top, undo = pop.", difficulty: "easy" },
    ],
  },
  {
    slug: "c-sortare-cautare",
    title: "17. Sortare și Căutare",
    order: 17,
    theory: [
      { order: 1, title: "Bubble Sort și Selection Sort", content: "```c\n// Bubble Sort — O(n²):\nvoid bubble(int *a, int n) {\n    for (int i = 0; i < n-1; i++)\n        for (int j = 0; j < n-i-1; j++)\n            if (a[j] > a[j+1]) {\n                int t = a[j]; a[j] = a[j+1]; a[j+1] = t;\n            }\n}\n\n// Selection Sort — O(n²):\nvoid selection(int *a, int n) {\n    for (int i = 0; i < n-1; i++) {\n        int minIdx = i;\n        for (int j = i+1; j < n; j++)\n            if (a[j] < a[minIdx]) minIdx = j;\n        if (minIdx != i) {\n            int t = a[i]; a[i] = a[minIdx]; a[minIdx] = t;\n        }\n    }\n}\n```" },
      { order: 2, title: "Insertion Sort și QuickSort", content: "```c\n// Insertion Sort — O(n²) worst, O(n) best:\nvoid insertion(int *a, int n) {\n    for (int i = 1; i < n; i++) {\n        int key = a[i], j = i-1;\n        while (j >= 0 && a[j] > key) {\n            a[j+1] = a[j]; j--;\n        }\n        a[j+1] = key;\n    }\n}\n\n// QuickSort — O(n log n) average:\nvoid quicksort(int *a, int lo, int hi) {\n    if (lo < hi) {\n        int pivot = a[hi], i = lo - 1;\n        for (int j = lo; j < hi; j++)\n            if (a[j] <= pivot) {\n                i++;\n                int t = a[i]; a[i] = a[j]; a[j] = t;\n            }\n        int t = a[i+1]; a[i+1] = a[hi]; a[hi] = t;\n        int p = i + 1;\n        quicksort(a, lo, p-1);\n        quicksort(a, p+1, hi);\n    }\n}\n```" },
      { order: 3, title: "Binary Search — căutare binară", content: "```c\n// Binar Search — O(log n) — array-ul TREBUIE sortat!\nint binary_search(int *a, int n, int target) {\n    int lo = 0, hi = n - 1;\n    while (lo <= hi) {\n        int mid = lo + (hi - lo) / 2; // previne overflow\n        if (a[mid] == target) return mid;\n        if (a[mid] < target) lo = mid + 1;\n        else hi = mid - 1;\n    }\n    return -1; // nu e în array\n}\n\n// Varianta recursivă:\nint bs_rec(int *a, int lo, int hi, int target) {\n    if (lo > hi) return -1;\n    int mid = lo + (hi - lo) / 2;\n    if (a[mid] == target) return mid;\n    if (a[mid] < target) return bs_rec(a, mid+1, hi, target);\n    return bs_rec(a, lo, mid-1, target);\n}\n```" },
      { order: 4, title: "Complexitate — rezumat", content: "| Algoritm | Best | Average | Worst | Stabil? |\n|---|---|---|---|---|\n| Bubble Sort | O(n) | O(n²) | O(n²) | Da |\n| Selection Sort | O(n²) | O(n²) | O(n²) | Nu |\n| Insertion Sort | O(n) | O(n²) | O(n²) | Da |\n| Quick Sort | O(n log n) | O(n log n) | O(n²) | Nu |\n| Merge Sort | O(n log n) | O(n log n) | O(n log n) | Da |\n| Binary Search | O(1) | O(log n) | O(log n) | N/A |\n\n**Regula practică:**\n• Array mic (n < 20): insertion sort\n• Array general: qsort() din stdlib.h\n• Nevoie de stabilitate: merge sort" },
    ],
    tasks: [
      { number: 1, name: "Binary search precondition", question: "Ce condiție trebuie îndeplinită pentru Binary Search?", options: ["Array de numere", "Array sortat", "Array cu elemente unice", "Array de minim 10 elemente"], answer: "Array sortat", explanation: "Binary Search funcționează NUMAI pe array sortat — altfel comparațiile mid nu sunt valide.", difficulty: "easy" },
      { number: 2, name: "Complexitate binary search", question: "Care e complexitatea Binary Search?", options: ["O(n)", "O(n²)", "O(log n)", "O(1)"], answer: "O(log n)", explanation: "La fiecare pas, jumătate din spațiu e eliminat. log₂(1000000) ≈ 20 pași.", difficulty: "easy" },
      { number: 3, name: "QuickSort complexitate", question: "Care e complexitatea medie a QuickSort?", options: ["O(n²)", "O(n log n)", "O(n)", "O(log n)"], answer: "O(n log n)", explanation: "QuickSort are average O(n log n). Worst case O(n²) când pivot-ul e mereu cel mai mic/mare.", difficulty: "medium" },
      { number: 4, name: "Insertion best case", question: "Cand e Insertion Sort O(n)?", options: ["Niciodată", "Când array-ul e sortat descrescător", "Când array-ul e deja sortat", "Când are doar duplicate"], answer: "Când array-ul e deja sortat", explanation: "Pe array sortat, inner while nu execută nicio mutare. O(n) comparații, 0 schimburi.", difficulty: "medium" },
    ],
  },
  {
    slug: "c-recursivitate",
    title: "18. Recursivitate",
    order: 18,
    theory: [
      { order: 1, title: "Principiul recursivității", content: "O funcție e **recursivă** dacă se apelează pe ea însăși. Necesită:\n1. **Caz de bază** (oprire) — fără recursivitate\n2. **Caz recursiv** — apel cu problemă mai mică\n\n```c\nint factorial(int n) {\n    // Caz de bază:\n    if (n <= 1) return 1;\n    // Caz recursiv:\n    return n * factorial(n - 1);\n}\n\n// Cum funcționează factorial(4):\n// factorial(4) → 4 * factorial(3)\n// factorial(3) → 3 * factorial(2)\n// factorial(2) → 2 * factorial(1)\n// factorial(1) → 1 (caz de baza)\n// Înapoi: 2, 6, 24\n\nint fibonacci(int n) {\n    if (n <= 1) return n;\n    return fibonacci(n-1) + fibonacci(n-2);\n    // Atenție: exponential O(2^n) fără memoizare!\n}\n```" },
      { order: 2, title: "Recursivitate vs Iterație", content: "```c\n// Factorial iterativ — O(n) timp, O(1) spațiu:\nlong factorial_iter(int n) {\n    long rez = 1;\n    for (int i = 2; i <= n; i++) rez *= i;\n    return rez;\n}\n\n// Factorial recursiv — O(n) timp, O(n) spațiu (stack frames)!\nlong factorial_rec(int n) {\n    if (n <= 1) return 1;\n    return n * factorial_rec(n-1);\n}\n\n// Când recursivitate e mai clară:\n// - Structuri arborescente (traversare arbore)\n// - Divide and conquer (merge sort, quick sort)\n// - Probleme cu backtracking\n\n// Stack overflow dacă recursivitatea e prea adâncă!\n// (limita tipică: ~1000-10000 niveluri)\n```" },
      { order: 3, title: "Turnurile din Hanoi", content: "```c\n#include <stdio.h>\n\nvoid hanoi(int n, char din, char la, char via) {\n    if (n == 1) {\n        printf(\"Muta disc 1 din %c la %c\\n\", din, la);\n        return;\n    }\n    hanoi(n-1, din, via, la); // muta n-1 discuri din → via\n    printf(\"Muta disc %d din %c la %c\\n\", n, din, la);\n    hanoi(n-1, via, la, din); // muta n-1 discuri via → la\n}\n\nint main() {\n    hanoi(3, 'A', 'C', 'B');\n    // Număr minim mutări = 2^n - 1\n    return 0;\n}\n```\n\nHanoi e un exemplu clasic unde recursivitatea e infinit mai clară decât iterația." },
      { order: 4, title: "Recursivitate pe tablouri și stringuri", content: "```c\n// Suma recursivă a unui array:\nint suma(int *a, int n) {\n    if (n == 0) return 0;\n    return a[0] + suma(a + 1, n - 1); // pointer aritmetică\n}\n\n// Lungimea unui string recursiv:\nint lung(char *s) {\n    if (*s == '\\0') return 0;\n    return 1 + lung(s + 1);\n}\n\n// Inversarea unui string:\nvoid inverseaza(char *s, int lo, int hi) {\n    if (lo >= hi) return;\n    char t = s[lo]; s[lo] = s[hi]; s[hi] = t;\n    inverseaza(s, lo+1, hi-1);\n}\n```" },
    ],
    tasks: [
      { number: 1, name: "Caz de baza", question: "Ce se întâmplă dacă o funcție recursivă nu are caz de bază?", options: ["Funcționează mai repede", "Stack overflow — recursivitate infinită", "Returnează 0", "Eroare de compilare"], answer: "Stack overflow — recursivitate infinită", explanation: "Fără caz de bază, funcția se apelează la infinit până stack-ul se umple (Stack Overflow).", difficulty: "easy" },
      { number: 2, name: "Fibonacci complexitate", question: "Care e complexitatea fibonacci recursiv naiv?", options: ["O(n)", "O(n log n)", "O(2^n)", "O(n²)"], answer: "O(2^n)", explanation: "fibonacci(n) apelează fibonacci(n-1) și fibonacci(n-2) — se dubleaza la fiecare nivel = O(2^n).", difficulty: "medium" },
      { number: 3, name: "Stack frames", question: "Recursivitatea consumă mai multă memorie decât iterația?", options: ["Nu, e identic", "Da — fiecare apel adaugă un frame pe call stack", "Depinde de compilator", "Nu, iterația e mai mare"], answer: "Da — fiecare apel adaugă un frame pe call stack", explanation: "Fiecare apel recursiv adaugă variabile locale + adresa de return pe stack — O(n) spațiu.", difficulty: "medium" },
      { number: 4, name: "Hanoi mutari", question: "Câte mutări necesită Turnurile din Hanoi pentru n discuri?", options: ["n", "n²", "n log n", "2^n - 1"], answer: "2^n - 1", explanation: "Formula exactă: 2^n - 1 mutări. Für 3 discuri = 7 mutări.", difficulty: "medium" },
    ],
  },
  {
    slug: "c-malloc-avansat",
    title: "19. Alocare dinamică avansată",
    order: 19,
    theory: [
      { order: 1, title: "malloc, calloc, realloc", content: "```c\n#include <stdlib.h>\n\n// malloc — alocă n bytes (conținut nedefinit):\nint *arr = (int*)malloc(10 * sizeof(int));\n\n// calloc — alocă și inițializează cu 0:\nint *arr2 = (int*)calloc(10, sizeof(int));\n\n// realloc — mărește/micșorează alocare:\narr = (int*)realloc(arr, 20 * sizeof(int));\n// Dacă realloc eșuează, returnează NULL\n// DAR pointer-ul original e PIERDUT dacă nu ai grijă!\nint *tmp = (int*)realloc(arr, 30 * sizeof(int));\nif (!tmp) { free(arr); exit(1); } // gestionare eroare\narr = tmp;\n\n// Verifică mereu:\nif (!arr) { perror(\"malloc\"); exit(1); }\n```" },
      { order: 2, title: "Array 2D alocat dinamic", content: "```c\n#include <stdio.h>\n#include <stdlib.h>\n\nint** creeaza_matrice(int r, int c) {\n    int **m = (int**)malloc(r * sizeof(int*));\n    for (int i = 0; i < r; i++)\n        m[i] = (int*)calloc(c, sizeof(int));\n    return m;\n}\n\nvoid elibereaza_matrice(int **m, int r) {\n    for (int i = 0; i < r; i++) free(m[i]);\n    free(m);\n}\n\nint main() {\n    int **mat = creeaza_matrice(3, 4);\n    mat[1][2] = 42;\n    printf(\"%d\\n\", mat[1][2]);\n    elibereaza_matrice(mat, 3);\n    return 0;\n}\n```" },
      { order: 3, title: "Common bugs: memory leak și dangling pointer", content: "```c\n// Memory Leak — alocat dar niciodată eliberat:\nvoid leak() {\n    int *p = malloc(100); // alocăm\n    // ... uităm de free!\n    // La ieșire din funcție, p dispare dar memoria rămâne alocată!\n}\n\n// Dangling Pointer — folosit după free:\nvoid dangling() {\n    int *p = malloc(sizeof(int));\n    *p = 42;\n    free(p);\n    *p = 10; // ❌ UNDEFINED BEHAVIOR — p e dangling!\n    p = NULL; // ✅ setează la NULL după free\n}\n\n// Double Free — eliberat de două ori:\nvoid double_free() {\n    int *p = malloc(sizeof(int));\n    free(p);\n    free(p); // ❌ CRASH sau heap corruption!\n    // ✅ p = NULL după primul free previne\n}\n```" },
      { order: 4, title: "Instrumente: Valgrind și sanitizers", content: "```bash\n# Valgrind — detectează memory leaks:\nvalgrind --leak-check=full ./program\n\n# AddressSanitizer (compilare cu GCC/Clang):\ngcc -fsanitize=address -g -o prog prog.c\n./prog\n# Detectează: use-after-free, buffer overflow, memory leaks\n\n# Pattern bun — eliberare sigură:\nvoid safe_free(void **ptr) {\n    if (ptr && *ptr) {\n        free(*ptr);\n        *ptr = NULL;\n    }\n}\n```\n\n**Regula de aur:** fiecare malloc/calloc are un free corespunzător. Setează la NULL după free." },
    ],
    tasks: [
      { number: 1, name: "calloc vs malloc", question: "Diferența dintre calloc și malloc?", options: ["calloc e mai rapid", "calloc inițializează memoria cu 0, malloc nu", "calloc alocă mai puțin", "malloc e deprecated"], answer: "calloc inițializează memoria cu 0, malloc nu", explanation: "malloc alocă bytes nedefiniti (conținut aleatoriu). calloc setează toți bytes la 0.", difficulty: "easy" },
      { number: 2, name: "realloc pericol", question: "De ce e periculos arr = realloc(arr, size)?", options: ["Niciun pericol", "La eșec, returnează NULL dar arr original e pierdut (memory leak)", "realloc nu există", "Schimbă tipul datelor"], answer: "La eșec, returnează NULL dar arr original e pierdut (memory leak)", explanation: "Dacă realloc eșuează returnează NULL. Dacă ai suprascris arr cu NULL, ai pierdut referința la memoria originală.", difficulty: "hard" },
      { number: 3, name: "Dangling pointer fix", question: "Cum previi dangling pointer după free(p)?", options: ["Nu poți", "p = NULL imediat după free", "p = 0", "Ambele b și c"], answer: "p = NULL imediat după free", explanation: "Setând p = NULL după free, orice acces ulterior la *p va cauda crash predictibil (NULL deref), nu UB.", difficulty: "medium" },
      { number: 4, name: "Matrix allocation", question: "De câte ori chemi free pentru o matrice int **m cu 3 rânduri?", options: ["1", "3", "4", "9"], answer: "4", explanation: "free pentru fiecare rând (3x) + free pentru array-ul de pointeri (1x) = 4 free-uri totale.", difficulty: "medium" },
    ],
  },
  {
    slug: "c-preprocessor",
    title: "20. Preprocesor C — macros și directivele",
    order: 20,
    theory: [
      { order: 1, title: "#define — constante și macros", content: "```c\n#include <stdio.h>\n\n// Constante:\n#define MAX 100\n#define PI 3.14159\n#define ADEVARAT 1\n\n// Macros cu parametri:\n#define PATRAT(x) ((x) * (x))    // paranteze importante!\n#define MAX2(a, b) ((a) > (b) ? (a) : (b))\n#define ABS(x) ((x) >= 0 ? (x) : -(x))\n\nint main() {\n    printf(\"%d\\n\", PATRAT(5));  // 25\n    printf(\"%d\\n\", PATRAT(2+3)); // 25 (corect cu paranteze)\n    // Fără paranteze: PATRAT(2+3) = 2+3*2+3 = 11 (bug!)\n\n    int arr[MAX];\n    printf(\"%d\\n\", MAX2(4, 7)); // 7\n    return 0;\n}\n```" },
      { order: 2, title: "#include, #ifdef — compilare condițională", content: "```c\n#include <stdio.h>   // bibliotecă sistem <>\n#include \"mylib.h\"  // fișier local \"\"\n\n// Include guard — previne includere dublă:\n#ifndef MYLIB_H\n#define MYLIB_H\n\n// ... conținutul header-ului\n\n#endif\n\n// Compilare condițională:\n#define DEBUG 1\n\nint main() {\n#ifdef DEBUG\n    printf(\"[DEBUG] Intrat în main\\n\");\n#endif\n\n    int x = 42;\n\n#if DEBUG == 1\n    printf(\"[DEBUG] x = %d\\n\", x);\n#endif\n\n    return 0;\n}\n\n// La compilare: gcc -DDEBUG=1 prog.c\n// Activezi DEBUG fără a modifica codul!\n```" },
      { order: 3, title: "#pragma și predefined macros", content: "```c\n// Macros predefinite de compilator:\nprintf(\"Fișier: %s\\n\", __FILE__);\nprintf(\"Linie: %d\\n\", __LINE__);\nprintf(\"Funcție: %s\\n\", __func__);\nprintf(\"Data compilare: %s\\n\", __DATE__);\n\n// Macro de logging cu locație:\n#define LOG(msg) printf(\"[%s:%d] %s\\n\", __FILE__, __LINE__, msg)\nLOG(\"Eroare la alocare\"); // [main.c:25] Eroare la alocare\n\n// #pragma once — alternativă la include guard:\n#pragma once\n// (Nu e standard C, dar e suportat de GCC/MSVC/Clang)\n\n// #pragma pack — aliniament structuri:\n#pragma pack(1) // fără padding\ntypedef struct { char a; int b; } Packed;\n#pragma pack() // reset\n```" },
      { order: 4, title: "Macros vs inline functions", content: "```c\n// Macro — substitutie textuala, fara tip:\n#define DUBLU(x) ((x) * 2)\n\n// Inline function — tipizat, mai sigur:\nstatic inline int dublu(int x) { return x * 2; }\n\n// Problema macro:\n#define INCR(x) (++(x))\nint a = 5;\nint b = INCR(a) + INCR(a); // a++ de 2 ori! Bug!\n\n// Inline e mai sigur — argumentul evaluat O SINGURA DATĂ.\n// Macro: fiecare apariție a x în corpul macroului\n// poate fi evaluată de mai multe ori!\n\n// Regula modernă:\n// const int MAX = 100;   // în loc de #define MAX 100\n// inline int max(int a, int b) { return a > b ? a : b; }\n```" },
    ],
    tasks: [
      { number: 1, name: "Paranteze macro", question: "De ce scriem #define PATRAT(x) ((x)*(x)) cu paranteze extra?", options: ["E stil personal", "Evită bug-uri de precedență — PATRAT(2+3) altfel = 2+3*2+3", "Compilatorul o cere", "E mai eficient"], answer: "Evită bug-uri de precedență — PATRAT(2+3) altfel = 2+3*2+3", explanation: "Substitutia textuala: PATRAT(2+3) devine (2+3)*(2+3) = 25 cu paranteze, dar 2+3*2+3=11 fără.", difficulty: "medium" },
      { number: 2, name: "Include guard", question: "La ce servesc #ifndef/#define/#endif în header?", options: ["Compilare condițională generală", "Previne includerea dublă a aceluiași header", "Ascunde codul", "Optimizare"], answer: "Previne includerea dublă a aceluiași header", explanation: "Include guards asigură că header-ul e procesat o singură dată, evitând erori de redefinire.", difficulty: "medium" },
      { number: 3, name: "__FILE__", question: "Ce conține macro-ul __FILE__?", options: ["Conținutul fișierului", "Numele fișierului sursă curent (string)", "Dimensiunea fișierului", "Data ultimei modificări"], answer: "Numele fișierului sursă curent (string)", explanation: "__FILE__ e înlocuit la compilare cu string-ul numelui fișierului sursă curent.", difficulty: "easy" },
      { number: 4, name: "Macro vs inline", question: "De ce inline function e preferată față de macro pentru funcții?", options: ["E mai rapidă", "E tipizată și argumentele sunt evaluate o singură dată", "E portabilă", "E mai scurtă"], answer: "E tipizată și argumentele sunt evaluate o singură dată", explanation: "Macro face substitutie textuala — argumente pot fi evaluate multiplu și nu există verificare de tip.", difficulty: "medium" },
    ],
  },
  {
    slug: "c-bitwise",
    title: "21. Operații pe biți (Bitwise)",
    order: 21,
    theory: [
      { order: 1, title: "Operatori bitwise", content: "```c\n// & — AND bitwise:\n5 & 3 = 0101 & 0011 = 0001 = 1\n\n// | — OR bitwise:\n5 | 3 = 0101 | 0011 = 0111 = 7\n\n// ^ — XOR bitwise (diferit = 1):\n5 ^ 3 = 0101 ^ 0011 = 0110 = 6\n\n// ~ — NOT bitwise (complementul față de 1):\n~5 = ~00000101 = 11111010 = -6 (în two's complement)\n\n// << — shift stânga (înmulțire cu 2^n):\n5 << 2 = 0101 << 2 = 010100 = 20  (5 * 4)\n\n// >> — shift dreapta (împărțire cu 2^n):\n20 >> 2 = 010100 >> 2 = 000101 = 5 (20 / 4)\n\n#include <stdio.h>\nint main() {\n    printf(\"%d\\n\", 5 & 3);  // 1\n    printf(\"%d\\n\", 5 | 3);  // 7\n    printf(\"%d\\n\", 5 ^ 3);  // 6\n    printf(\"%d\\n\", 1 << 4); // 16 (2^4)\n    return 0;\n}\n```" },
      { order: 2, title: "Flags și bitmasks", content: "```c\n// Bitflags — stochezi mai multe opțiuni într-un singur int:\n#define FLAG_READ    (1 << 0)  // 001 = 1\n#define FLAG_WRITE   (1 << 1)  // 010 = 2\n#define FLAG_EXECUTE (1 << 2)  // 100 = 4\n\nint permisiuni = FLAG_READ | FLAG_WRITE; // 011 = 3\n\n// Verificare flag:\nif (permisiuni & FLAG_READ) printf(\"Poate citi\\n\");\nif (permisiuni & FLAG_EXECUTE) printf(\"Poate executa\\n\"); // nu\n\n// Setare flag:\npermisiuni |= FLAG_EXECUTE; // adaugă exec\n\n// Ștergere flag:\npermisiuni &= ~FLAG_WRITE; // elimină write\n\n// Toggle flag:\npermisiuni ^= FLAG_READ; // inversează read\n```" },
      { order: 3, title: "Manipulări utile", content: "```c\n// Verifică dacă n e par:\nif (n & 1) printf(\"impar\");\nelse printf(\"par\");\n// Ultimul bit: 0=par, 1=impar\n\n// Putere a lui 2?\nint is_pow2 = (n > 0) && !(n & (n-1));\n// 8: 1000 & 0111 = 0 ✓\n// 6: 0110 & 0101 = 0100 ≠ 0 ✗\n\n// Swap fără variabilă temporară (XOR swap):\na ^= b;\nb ^= a;\na ^= b;\n\n// Extrage bitul k:\nint bit = (n >> k) & 1;\n\n// Setează bitul k:\nn |= (1 << k);\n\n// Șterge bitul k:\nn &= ~(1 << k);\n```" },
      { order: 4, title: "Tipuri pentru biți: bit fields", content: "```c\n// Bit fields în struct:\ntypedef struct {\n    unsigned int citire   : 1; // 1 bit\n    unsigned int scriere  : 1;\n    unsigned int executie : 1;\n    unsigned int rezervat : 5; // 5 biți\n} Permisiuni;\n\nPermisiuni p = { .citire = 1, .scriere = 1, .executie = 0 };\nprintf(\"Citire: %d\\n\", p.citire);    // 1\nprintf(\"Exec: %d\\n\", p.executie);   // 0\n\n// sizeof(Permisiuni) = 4 bytes (tipic)\n// DAR nu e standardizat ordering în memorie!\n// Bitmasks manuale sunt mai portabile pentru protocoale.\n```" },
    ],
    tasks: [
      { number: 1, name: "AND bitwise", question: "5 & 3 este?", options: ["8", "7", "1", "15"], answer: "1", explanation: "5 = 0101, 3 = 0011. AND: 0101 & 0011 = 0001 = 1.", difficulty: "medium" },
      { number: 2, name: "Shift stanga", question: "1 << 3 este?", options: ["3", "6", "8", "4"], answer: "8", explanation: "Shift stânga cu 3 = 1 * 2^3 = 8.", difficulty: "easy" },
      { number: 3, name: "Verificare par", question: "Cum verifici dacă n e par cu operatoare bitwise?", options: ["n % 2 == 0", "n & 1 == 0", "n >> 1 == 0", "~n & 1"], answer: "n & 1 == 0", explanation: "Ultimul bit e 0 pentru numere pare, 1 pentru impare. n & 1 == 0 înseamnă par.", difficulty: "easy" },
      { number: 4, name: "Flag set", question: "Cum adaugi FLAG_EXECUTE la variabila permisiuni?", options: ["permisiuni + FLAG_EXECUTE", "permisiuni |= FLAG_EXECUTE", "permisiuni &= FLAG_EXECUTE", "permisiuni = FLAG_EXECUTE"], answer: "permisiuni |= FLAG_EXECUTE", explanation: "OR (|) setează biții — |= adaugă flag-ul fără a afecta ceilalți biți.", difficulty: "medium" },
    ],
  },
  {
    slug: "c-compilare-linking",
    title: "22. Compilare, Linking și Makefile",
    order: 22,
    theory: [
      { order: 1, title: "Etapele compilării C", content: "**4 etape distincte:**\n\n```bash\n# 1. Preprocesor — expandează #include, #define\ngcc -E main.c -o main.i\n\n# 2. Compilare — generează assembly\ngcc -S main.i -o main.s\n\n# 3. Asamblare — generează object file (.o)\ngcc -c main.c -o main.o\n\n# 4. Linking — combină .o files în executabil\ngcc main.o utils.o -o program\n\n# Totul dintr-o dată:\ngcc main.c utils.c -o program\n\n# Cu optimizări:\ngcc -O2 main.c -o program\n\n# Cu debug info:\ngcc -g main.c -o program\n```\n\nLinking combină funcțiile din mai multe .o files și leagă biblioteca standard (libc)." },
      { order: 2, title: "Header files și separarea codului", content: "```c\n// utils.h — declarații (interfața):\n#ifndef UTILS_H\n#define UTILS_H\n\nint aduna(int a, int b);\nint inmulteste(int a, int b);\nvoid afiseaza_array(int *arr, int n);\n\n#endif\n\n// utils.c — implementarea:\n#include \"utils.h\"\n\nint aduna(int a, int b) { return a + b; }\nint inmulteste(int a, int b) { return a * b; }\nvoid afiseaza_array(int *arr, int n) {\n    for (int i = 0; i < n; i++) printf(\"%d \", arr[i]);\n    printf(\"\\n\");\n}\n\n// main.c:\n#include <stdio.h>\n#include \"utils.h\"\n\nint main() {\n    printf(\"%d\\n\", aduna(3, 4));\n    return 0;\n}\n```" },
      { order: 3, title: "Makefile — automatizare build", content: "```makefile\n# Makefile:\nCC = gcc\nCFLAGS = -Wall -Wextra -g\n\n# Target: dependințe\n#     comandă (TAB obligatoriu!)\n\nall: program\n\nprogram: main.o utils.o\n\t$(CC) $(CFLAGS) main.o utils.o -o program\n\nmain.o: main.c utils.h\n\t$(CC) $(CFLAGS) -c main.c\n\nutils.o: utils.c utils.h\n\t$(CC) $(CFLAGS) -c utils.c\n\nclean:\n\trm -f *.o program\n\n.PHONY: all clean\n```\n\n```bash\nmake        # compilează tot (doar ce s-a schimbat)\nmake clean  # șterge compilatele\n```" },
      { order: 4, title: "Biblioteci statice și dinamice", content: "```bash\n# Bibliotecă STATICĂ (.a) — linkată în executabil:\nar rcs libutils.a utils.o\ngcc main.c -L. -lutils -o program\n# Executabilul conține codul bibliotecii\n\n# Bibliotecă DINAMICĂ (.so/.dll) — linkată la rulare:\ngcc -shared -fPIC utils.c -o libutils.so\ngcc main.c -L. -lutils -Wl,-rpath,. -o program\n# Executabilul este mai mic, biblioteca e separată\n\n# Biblioteci sistem comune:\n# -lm    — math (sqrt, sin etc)\n# -lpthread — threading\n# -lcurl — HTTP requests\n\ngcc prog.c -lm -o prog  # pentru sqrt()\n```" },
    ],
    tasks: [
      { number: 1, name: "Object file", question: "Ce generează gcc -c main.c?", options: ["Executabilul", "main.o — object file (cod compilat, nelinkuit)", "main.s — assembly", "main.i — preprocessat"], answer: "main.o — object file (cod compilat, nelinkuit)", explanation: "Flag -c compilează fără linking — generează .o. Linking se face separat pentru a combina mai multe .o.", difficulty: "easy" },
      { number: 2, name: "Header guard", question: "La ce servesc #ifndef/#define/#endif în header?", options: ["Eficiență", "Previne includerea multiplă a aceluiași header", "Compilare condițională generală", "Definire macro"], answer: "Previne includerea multiplă a aceluiași header", explanation: "Include guards asigură că un header e procesat o singură dată, chiar dacă e inclus din mai multe fișiere.", difficulty: "easy" },
      { number: 3, name: "Makefile separator", question: "Ce trebuie să folosești înainte de comandă în Makefile?", options: ["Spații (4)", "TAB (obligatoriu)", "Două spații", "//"], answer: "TAB (obligatoriu)", explanation: "Makefile-urile sunt sensibile la TAB vs spaces. Comenzile TREBUIE să înceapă cu TAB, nu spații.", difficulty: "medium" },
      { number: 4, name: "Static vs dinamic", question: "Avantajul bibliotecii statice față de cea dinamică?", options: ["Dimensiune mai mică", "Executabilul nu depinde de .so la runtime — totul inclus", "Mai rapidă la loading", "Mai ușor de updatat"], answer: "Executabilul nu depinde de .so la runtime — totul inclus", explanation: "Biblioteca statică e inclusă în executabil — nici o dependență externă la rulare. Dezavantaj: executabil mai mare.", difficulty: "medium" },
    ],
  },
  {
    slug: "c-debugging",
    title: "23. Debugging — GDB și tehnici",
    order: 23,
    theory: [
      { order: 1, title: "GDB — GNU Debugger basics", content: "```bash\n# Compilează cu debug info:\ngcc -g -o prog main.c\n\n# Pornire GDB:\ngdb prog\n\n# Comenzi esențiale GDB:\n# (gdb) run                  — pornire program\n# (gdb) run arg1 arg2        — cu argumente\n# (gdb) break main.c:15      — breakpoint pe linia 15\n# (gdb) break functie        — breakpoint pe funcție\n# (gdb) next  (sau n)        — execută o linie (skip funcții)\n# (gdb) step  (sau s)        — intră în funcție\n# (gdb) continue (sau c)     — continuă până la următor breakpoint\n# (gdb) print x              — afișează variabila x\n# (gdb) print *ptr           — dereferențiază pointer\n# (gdb) info locals          — toate variabilele locale\n# (gdb) backtrace (sau bt)   — call stack\n# (gdb) quit (sau q)         — ieșire\n```" },
      { order: 2, title: "Debuggarea memoriei cu Valgrind", content: "```bash\n# Valgrind — detectare memory errors:\nvalgrind ./prog\n\n# Raport detaliat leaks:\nvalgrind --leak-check=full --show-leak-kinds=all ./prog\n\n# Ce detectează:\n# - Memory leaks (malloc fără free)\n# - Use after free\n# - Buffer overflow (citire/scriere în afara alocatiei)\n# - Use of uninitialized memory\n# - Invalid reads/writes\n\n# AddressSanitizer (mai rapid, integrat în compilator):\ngcc -fsanitize=address,undefined -g -o prog main.c\n./prog\n\n# MemorySanitizer (detectează variabile neinițializate):\nclang -fsanitize=memory -g -o prog main.c\n```" },
      { order: 3, title: "Tehnici de debugging manual", content: "```c\n// fprintf(stderr, ...) — nu buffered, apare imediat:\nfprintf(stderr, \"[DEBUG] x = %d\\n\", x);\n\n// assert — verifică invarianți:\n#include <assert.h>\nassert(ptr != NULL);      // crash dacă ptr e NULL\nassert(n > 0 && n < 100);\n\n// Compilare fără assert:\n// gcc -DNDEBUG prog.c  (dezactivează assert)\n\n// Macro de debug condiționat:\n#ifdef DEBUG\n#define DBG(fmt, ...) fprintf(stderr, \"[DBG %s:%d] \" fmt \"\\n\", __func__, __LINE__, ##__VA_ARGS__)\n#else\n#define DBG(fmt, ...) ((void)0)\n#endif\n\nDBG(\"Valoarea x = %d\", x);\n// Compilare: gcc -DDEBUG prog.c\n```" },
      { order: 4, title: "Bug-uri comune și cum le găsești", content: "**1. Segmentation Fault:**\n- Cauze: NULL pointer deref, buffer overflow, stack overflow\n- GDB: backtrace după crash\n\n**2. Memory Leak:**\n- Cauze: malloc fără free, pierderea referinței\n- Tool: Valgrind, ASan\n\n**3. Comportament nedefinit (UB):**\n- Cauze: signed integer overflow, pointer aritmetică invalidă\n- Tool: -fsanitize=undefined\n\n**4. Race condition (multi-thread):**\n- Tool: ThreadSanitizer (-fsanitize=thread)\n\n**5. Logic bug:**\n- Metodă: printf debugging, GDB watchpoints\n\n```bash\n# Workflow recomandat:\n# 1. gcc -g -fsanitize=address,undefined\n# 2. Rulează și verifică output sanitizer\n# 3. Dacă crash, rulează în GDB\n```" },
    ],
    tasks: [
      { number: 1, name: "GDB flag", question: "Ce flag trebuie la compilare pentru a folosi GDB?", options: ["-O2", "-g", "-Wall", "-static"], answer: "-g", explanation: "Flag -g include debug info (simboluri, numere de linie) în executabil. Necesar pentru GDB.", difficulty: "easy" },
      { number: 2, name: "GDB backtrace", question: "La ce folosești comanda backtrace (bt) în GDB?", options: ["Vizualizezi variabilele", "Oprești execuția", "Văd call stack-ul (ce funcții s-au apelat)", "Navighezi în memorie"], answer: "Văd call stack-ul (ce funcții s-au apelat)", explanation: "backtrace arată lanțul de apeluri — util pentru a înțelege contextul unui crash.", difficulty: "easy" },
      { number: 3, name: "Valgrind scop", question: "Ce detectează Valgrind?", options: ["Erori de sintaxă", "Memory leaks și accesuri invalide de memorie", "Logică greșită", "Erori de I/O"], answer: "Memory leaks și accesuri invalide de memorie", explanation: "Valgrind detectează: memory leaks, use-after-free, buffer overflow, uninit memory etc.", difficulty: "easy" },
      { number: 4, name: "assert scop", question: "La ce folosești assert(ptr != NULL)?", options: ["Optimizare", "Verificare invariant — crash imediat dacă condiția e falsă", "Afișare valoare", "Skip la NULL"], answer: "Verificare invariant — crash imediat dacă condiția e falsă", explanation: "assert verifică o condiție așteptată. Dacă e falsă, oprește programul cu un mesaj clar — mai bun decât crash misterios mai târziu.", difficulty: "easy" },
    ],
  },
  {
    slug: "c-mini-proiect-calculator",
    title: "24. Mini-proiect: Calculator în C",
    order: 24,
    theory: [
      { order: 1, title: "Arhitectura proiectului", content: "Vom construi un **calculator interactiv** în C cu:\n• Operații: +, -, *, /, %, putere\n• Memorie (store/recall)\n• Istoric operații\n• Input validat\n• Fișier de structuri cu funcții separate\n\n```\ncalculator/\n├── main.c\n├── calculator.h\n├── calculator.c\n├── history.h\n└── history.c\n```\n\n```c\n// calculator.h:\n#ifndef CALCULATOR_H\n#define CALCULATOR_H\n\ntypedef struct {\n    double memoria;\n    int are_memorie;\n} Calculator;\n\nvoid init(Calculator *c);\ndouble calculeaza(double a, double b, char op);\nvoid memorie_store(Calculator *c, double val);\ndouble memorie_recall(const Calculator *c);\n\n#endif\n```" },
      { order: 2, title: "Implementare calculator.c", content: "```c\n#include <stdio.h>\n#include <math.h>\n#include \"calculator.h\"\n\nvoid init(Calculator *c) {\n    c->memoria = 0;\n    c->are_memorie = 0;\n}\n\ndouble calculeaza(double a, double b, char op) {\n    switch (op) {\n        case '+': return a + b;\n        case '-': return a - b;\n        case '*': return a * b;\n        case '/':\n            if (b == 0) {\n                fprintf(stderr, \"Eroare: împărțire la zero!\\n\");\n                return 0;\n            }\n            return a / b;\n        case '%': return fmod(a, b);\n        case '^': return pow(a, b);\n        default:\n            fprintf(stderr, \"Operator necunoscut: %c\\n\", op);\n            return 0;\n    }\n}\n\nvoid memorie_store(Calculator *c, double val) {\n    c->memoria = val;\n    c->are_memorie = 1;\n    printf(\"Stocat în memorie: %g\\n\", val);\n}\n\ndouble memorie_recall(const Calculator *c) {\n    if (!c->are_memorie) {\n        fprintf(stderr, \"Memoria e goală!\\n\");\n        return 0;\n    }\n    return c->memoria;\n}\n```" },
      { order: 3, title: "Istoric cu array dinamic", content: "```c\n// history.h:\n#ifndef HISTORY_H\n#define HISTORY_H\n\n#define HISTORY_MAX 20\n\ntypedef struct {\n    char intrari[HISTORY_MAX][64];\n    int nr;\n} Istoric;\n\nvoid hist_init(Istoric *h);\nvoid hist_adauga(Istoric *h, double a, char op, double b, double rez);\nvoid hist_afiseaza(const Istoric *h);\nvoid hist_salveaza(const Istoric *h, const char *fisier);\n\n#endif\n\n// history.c:\nvoid hist_adauga(Istoric *h, double a, char op, double b, double rez) {\n    if (h->nr >= HISTORY_MAX) {\n        // Shiftăm — ștergem cel mai vechi:\n        for (int i = 0; i < HISTORY_MAX - 1; i++)\n            strcpy(h->intrari[i], h->intrari[i+1]);\n        h->nr = HISTORY_MAX - 1;\n    }\n    snprintf(h->intrari[h->nr++], 64, \"%.4g %c %.4g = %.4g\",\n             a, op, b, rez);\n}\n```" },
      { order: 4, title: "Main loop — REPL", content: "```c\n// main.c:\n#include <stdio.h>\n#include <string.h>\n#include \"calculator.h\"\n#include \"history.h\"\n\nint main() {\n    Calculator c;\n    Istoric hist;\n    init(&c);\n    hist_init(&hist);\n\n    double a, b, rez;\n    char op;\n\n    printf(\"Calculator C | exit, mem, hist, save\\n\");\n\n    while (1) {\n        printf(\"\\n> \");\n        char cmd[64];\n        if (fgets(cmd, sizeof(cmd), stdin) == NULL) break;\n\n        if (strncmp(cmd, \"exit\", 4) == 0) break;\n        if (strncmp(cmd, \"hist\", 4) == 0) { hist_afiseaza(&hist); continue; }\n        if (strncmp(cmd, \"save\", 4) == 0) { hist_salveaza(&hist, \"calc_hist.txt\"); continue; }\n\n        if (sscanf(cmd, \"%lf %c %lf\", &a, &op, &b) == 3) {\n            rez = calculeaza(a, b, op);\n            printf(\"= %g\\n\", rez);\n            hist_adauga(&hist, a, op, b, rez);\n            memorie_store(&c, rez); // auto-store în memorie\n        } else {\n            printf(\"Format: număr operator număr (ex: 5 + 3)\\n\");\n        }\n    }\n\n    return 0;\n}\n```" },
    ],
    tasks: [
      { number: 1, name: "Separare fișiere", question: "Care e scopul fișierelor .h (header)?", options: ["Conțin implementarea", "Declară interfața — funcții/tipuri disponibile fără implementare", "Sunt executabile", "Conțin date"], answer: "Declară interfața — funcții/tipuri disponibile fără implementare", explanation: "Header-urile declară semnăturile (nu implementarea). Alte .c includ .h pentru a ști ce funcții există.", difficulty: "easy" },
      { number: 2, name: "snprintf securitate", question: "De ce snprintf e mai sigur decât sprintf?", options: ["E mai rapid", "Limitează numărul de caractere scrise — previne buffer overflow", "Suportă mai multe formate", "Nu necesită \\0"], answer: "Limitează numărul de caractere scrise — previne buffer overflow", explanation: "snprintf(buf, n, ...) scrie maxim n-1 caractere + '\\0', prevenind overflow-ul față de sprintf.", difficulty: "medium" },
      { number: 3, name: "sscanf utilizare", question: "La ce servește sscanf(cmd, \"%lf %c %lf\", &a, &op, &b)?", options: ["Afișează formatat", "Parsează string-ul cmd și extrage valorile a, op, b", "Citește de la stdin", "Formatează un string"], answer: "Parsează string-ul cmd și extrage valorile a, op, b", explanation: "sscanf citește din string (nu stdin) și parsează valorile ca scanf normal.", difficulty: "medium" },
      { number: 4, name: "fmod utilizare", question: "De ce folosești fmod(a, b) pentru % pe double?", options: ["E mai rapid", "Operatorul % nu funcționează pe double în C", "E o convenție", "Returnează int"], answer: "Operatorul % nu funcționează pe double în C", explanation: "Operatorul % este pentru int/long în C. Pentru double, echivalentul e fmod() din <math.h>.", difficulty: "medium" },
    ],
  },
  {
    slug: "c-best-practices",
    title: "25. Bune Practici C — Recap Final",
    order: 25,
    theory: [
      { order: 1, title: "Reguli de siguranță a memoriei", content: "```c\n// 1. Verifică întotdeauna rezultatul malloc/calloc:\nvoid *p = malloc(n * sizeof(int));\nif (!p) { perror(\"malloc\"); exit(EXIT_FAILURE); }\n\n// 2. Setează la NULL după free:\nfree(p);\np = NULL;\n\n// 3. Nu pasa NULL unde nu e așteptat:\n// Adaugă validare la intrare:\nvoid proceseaza(int *arr, int n) {\n    if (!arr || n <= 0) return;\n    // ...\n}\n\n// 4. Evită VLA (variable-length arrays) mari:\n// int arr[n]; // riscant pentru n mare → stack overflow\n// Preferă malloc pentru n necunoscut/mare.\n\n// 5. Limitează lungimile string-urilor:\nchar buf[256];\nfgets(buf, sizeof(buf), stdin); // nu gets()!\nstrncpy(dst, src, sizeof(dst) - 1);\ndst[sizeof(dst) - 1] = '\\0'; // garantezi terminare\n```" },
      { order: 2, title: "Stilul codului și convenții", content: "```c\n// Convenții de denumire:\n// snake_case pentru funcții și variabile\n// UPPER_CASE pentru constante/macros\n// CamelCase (sau snake) pentru typedef struct\n\n// Structura unui fișier .c:\n// 1. Include-uri sistem\n// 2. Include-uri locale\n// 3. Macros și constante\n// 4. Declarații forward (dacă necesar)\n// 5. Implementări funcții\n// 6. main() la final\n\n// Funcțiile scurte — single responsibility:\n// Maxim ~50 linii per funcție\n// Un singur nivel de indentare\n\n// Comentarii utile:\n// Explică DE CE, nu CE (codul arată ce)\n// Comentează invarianți neobvioși\n```" },
      { order: 3, title: "Portabilitate și standard", content: "```c\n// Folosește tipuri precise din <stdint.h>:\n#include <stdint.h>\n\nuint8_t  byte;    // exact 8 biți unsigned\nint16_t  short2;  // exact 16 biți signed\nuint32_t count;   // exact 32 biți unsigned\nint64_t  big;     // exact 64 biți signed\n\n// Nu te baza pe sizeof(int) = 4!\n// int poate fi 2 sau 4 sau mai mult bytes.\n\n// Folosește size_t pentru indici și dimensiuni:\nfor (size_t i = 0; i < n; i++) { ... }\n\n// Include guard sau #pragma once în TOATE header-urile.\n\n// Compilare cu warnings:\n// gcc -Wall -Wextra -Wpedantic -std=c11\n// -std=c11 sau c17 pentru standard modern\n```" },
      { order: 4, title: "Resurse pentru continuare", content: "**Cărți recomandate:**\n• K&R — The C Programming Language (clasică)\n• \"Expert C Programming\" — Peter van der Linden\n• \"C Programming: A Modern Approach\" — K.N. King\n\n**Practică:**\n• LeetCode (algoritmi în C)\n• Exercism.io (exerciții C cu feedback)\n• Projekturi open source în C (Linux kernel, SQLite, Redis)\n\n**Next steps:**\n• C++ — OOP peste baza C\n• Embedded C — microcontrolere (Arduino, STM32)\n• OS Programming — syscalls, procese, threads\n• Algoritmi și structuri de date aprofundate\n\nC rămâne limbajul fundamental — performanță maximă, control total. Felicitări pentru parcurgerea celor 25 lecții!" },
    ],
    tasks: [
      { number: 1, name: "gets pericol", question: "De ce nu trebuie să folosești gets()?", options: ["E deprecated vizual", "Nu verifică lungimea buffer-ului — buffer overflow garantat", "E prea lentă", "Nu există în C11"], answer: "Nu verifică lungimea buffer-ului — buffer overflow garantat", explanation: "gets() citește fără limită — orice input mai lung decât buffer-ul suprascrie memoria. Eliminată din C11.", difficulty: "medium" },
      { number: 2, name: "uint32_t avantaj", question: "De ce preferăm uint32_t față de unsigned int?", options: ["E mai rapid", "Garantează exact 32 biți pe orice platformă", "E mai scurt", "E standard vechi"], answer: "Garantează exact 32 biți pe orice platformă", explanation: "sizeof(unsigned int) poate varia. uint32_t din <stdint.h> garantează exact 32 biți.", difficulty: "medium" },
      { number: 3, name: "Wall flag", question: "Ce face gcc -Wall?", options: ["Activează optimizări", "Activează toate warning-urile importante la compilare", "Setează standard C", "Generează executabil pentru Windows"], answer: "Activează toate warning-urile importante la compilare", explanation: "-Wall activează un set extins de warning-uri — bugs potențiale detectate la compilare.", difficulty: "easy" },
      { number: 4, name: "Single responsibility", question: "Ce înseamnă single responsibility pentru funcții?", options: ["O singură linie de cod", "Fiecare funcție face UN singur lucru bine", "Fără parametri", "Fără valoare de return"], answer: "Fiecare funcție face UN singur lucru bine", explanation: "Funcțiile cu un singur scop sunt mai ușor de testat, înțeles și reutilizat.", difficulty: "easy" },
    ],
  },
];

module.exports = { cMore };
